### ISSUE TITLE
OSX backend: Modifier Keys broken, including Command + C/V/Z

### ISSUE THREAD

**Issue by richardlalancetteyoui** [ocornut/imgui#4253] opened 2021-06-21 15:30 UTC
**Version/Branch of Dear ImGui:**

Version: 1.83
Branch: master (98876b4dc233d4b2cea22cc9a6d3e49a6ac2d59d)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_osx, imgui_impl_opengl2
Compiler: Apple Clang
Operating System: 
![Screen Shot 2021-06-21 at 11 12 50 AM](https://user-images.githubusercontent.com/42980705/122785738-a1142c00-d281-11eb-8b0f-3ab953381dcd.png)

**My Issue/Question:**
Copy/Paste broken?
The issue I am seeing is using Command+C and Command+V.
Instead of copying to the clipboard and pasting from the clipboard, a `C` and a `V` are inserted into the text.

I am convince this is related to `ResetKeys()` in `imgui_impl_osx.mm`

**Screenshots/Video**
Command C/V/Z busted here.

https://user-images.githubusercontent.com/42980705/122788006-e20d4000-d283-11eb-835b-6f2e130586a0.mov

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
![Screen Shot 2021-06-21 at 11 18 49 AM](https://user-images.githubusercontent.com/42980705/122786596-770f3980-d282-11eb-9b09-3c6fcb1fcd30.png)

**Comment by richardlalancetteyoui** [comment] 2021-06-21 15:34
Narrowed down to this line.

```    //io.KeyCtrl = io.KeyShift = io.KeyAlt = io.KeySuper = false;
```

**Comment by ocornut** [comment] 2021-06-21 16:35
6d5388448 added the modifiers clear which triggered the bug, but it's merely consistent with clearing the keys.
That backend is a severe mess (partly because of a limitation in the IO system, which will be lifted by io_queue work), generally we recommend people using the SDL or GLFW backend on OSX.

In earlier e54b61aa (second to initial commit)
- in `ImGui_ImplOSX_HandleEvent()` the "// We must reset in case we're pressing a sequence of special keys while keeping the command pressed" block was modified by, either version are equally bizarre.
- `NSEventTypeFlagsChanged` handling also calls `resetKeys()`

Someone would need to do a deep dive in figuring out why the code was designed this way with the `resetKeys()` calls.

**Comment by richardlalancetteyoui** [comment] 2021-06-21 21:03
OK, got little further.

This is getting called multiple times.

```io.GetClipboardTextFn = [](void *) -> const char * {
        g_pasteEventCount++;
        NSPasteboard *pasteboard = [NSPasteboard generalPasteboard];
        NSString *available = [pasteboard availableTypeFromArray:[NSArray arrayWithObject:NSPasteboardTypeString]];
        if (![available isEqualToString:NSPasteboardTypeString])
            return NULL;
        NSString *string = [pasteboard stringForType:NSPasteboardTypeString];
        if (string == nil)
            return NULL;
        const char *string_c = (const char *)[string UTF8String];
        size_t string_len = strlen(string_c);
        static ImVector<char> s_clipboard;
        s_clipboard.resize((int)string_len + 1);
        strcpy(s_clipboard.Data, string_c);
        ///[NSPasteboard generalPasteboard].clearContents;
        return s_clipboard.Data;
    };```

**Comment by richardlalancetteyoui** [comment] 2021-06-22 03:24
Little further:

The following seems to be set to allow repeat by default. If I pass in false to the repeat parameter, the bug goes away.
But that causes successive COMMAND+V to work only once.
...

```const bool is_paste = ((is_shortcut_key && IsKeyPressedMap(ImGuiKey_V, false)) || (is_shift_key_only && IsKeyPressedMap(ImGuiKey_Insert))) && !is_readonly;```

**Comment by ocornut** [comment] 2021-06-22 12:13
I think the issue is strictly at the imgui_impl_osx.mm level and you can look at the inputs provided by the backend in `Demo>Inputs, Navigation & Focus>Keyboard State`

**Comment by rokups** [comment] 2021-06-23 13:30
The fix (https://github.com/ocornut/imgui/commit/0b8a2470743f89d19ab2d5920606434b604b529e) was merged. Funny story. Turns out we had `KeyCtrl` and `KeySuper` mixed up in a shortcut check. But it did work when code was first added, because older version of sample swapped these keys to get PC-like shortcuts on a Mac. Eventually that change was lost and this function broke and nobody noticed for a long while since this backend is hardly used. It really is better idea to use SDL/GLFW as @ocornut said. 👍🏻

**Comment by ocornut** [comment] 2021-06-23 13:32
Closing as fixed, Richard let us know if you find other problems this is backend.

**Closed by ocornut** 2021-06-23 13:32 UTC
Labels: backend/binding, bug, osx/ios

**Comment by richardlalancetteyoui** [comment] 2021-06-23 14:53
Great!  @rokups thank you so much!
Merci Omar.

**Comment by richardlalancetteyoui** [comment] 2021-06-23 17:26
Yup, fixed!
Onto next issue. Thanks guys.

**Comment by richardlalancetteyoui** [comment] 2021-06-23 17:51
Going to use this thread to continue with the root issue that brought me to update.
```        const bool is_paste = ((is_shortcut_key && IsKeyPressedMap(ImGuiKey_V)) || (is_shift_key_only && IsKeyPressedMap(ImGuiKey_Insert))) && !is_readonly;
```
When I release `ImGuiKey_V`, and leave `Command` Down, `is_paste` returns true still. Because I dive in, is it possible that `g.IO.KeyMap` would also need clearing?
This is used in `    inline bool             IsKeyPressedMap(ImGuiKey key, bool repeat = true)           { ImGuiContext& g = *GImGui; const int key_index = g.IO.KeyMap[key]; return (key_index >= 0) ? IsKeyPressed(key_index, repeat) : false; }
`?

**Comment by ocornut** [comment] 2021-06-23 18:00
On Windows holding paste has typematic style auto-repeat. Do you suggest it isn’t the case on Mac?

**Comment by richardlalancetteyoui** [comment] 2021-06-23 18:05
Auto-repeat is fine, but the V is not down.

**Comment by richardlalancetteyoui** [comment] 2021-06-23 18:08
Ah ok. I suspect something is happening in here.

```bool ImGui::IsKeyPressed(int user_key_index, bool repeat)
{
    ImGuiContext& g = *GImGui;
    if (user_key_index < 0)
        return false;
    IM_ASSERT(user_key_index >= 0 && user_key_index < IM_ARRAYSIZE(g.IO.KeysDown));
    const float t = g.IO.KeysDownDuration[user_key_index];
    if (t == 0.0f)
        return true;
    if (repeat && t > g.IO.KeyRepeatDelay)
        return GetKeyPressedAmount(user_key_index, g.IO.KeyRepeatDelay, g.IO.KeyRepeatRate) > 0;
    return false;
}```

**Comment by ocornut** [comment] 2021-06-23 18:09
This is a backend issue so there’s little point is digging into InputText code. If you can confirm the key state are wrong when displayed in the demo window, we have to look at the backend.

**Comment by richardlalancetteyoui** [comment] 2021-06-23 18:10
Ah gotcha!

**Comment by richardlalancetteyoui** [comment] 2021-06-24 17:11
Yup, looks like this is never called.

```-(void)keyUp:(NSEvent *)event```
Breakpoint won't get hit.

Onward!

**Comment by richardlalancetteyoui** [comment] 2021-06-24 20:52
Fixed with this, if you guys want to bring this in.

```-(void)updateAndDrawDemoView
{
    // Start the Dear ImGui frame
	ImGui_ImplOpenGL2_NewFrame();
	ImGui_ImplOSX_NewFrame(self);
    ImGui::NewFrame();

    [NSEvent addLocalMonitorForEventsMatchingMask:NSEventMaskKeyUp handler:^NSEvent*(NSEvent *event)
    {
        ImGuiIO& io = ImGui::GetIO();

        if (io.KeySuper)
        {
            memset(io.KeysDown, 0, sizeof(io.KeysDown));
        }

        return event;
    }];```

**Comment by ocornut** [comment] 2021-06-25 09:44
Instead the apple+opengl2 example didn't have the same events registration as apple+metal
Fixed by https://github.com/ocornut/imgui_private/commit/2a6870be2ff6bb32642a984b72d3cadb69e7112a

There are still too many differences between both examples, we should aim to reduce them.
