### ISSUE TITLE
Multicolored elements in text

### ISSUE THREAD

**Issue by darkgnostic** [ocornut/imgui#1335] opened 2017-09-25 10:53 UTC
Is it possible to have multicolored elements text? I know it is possible to color the text, I'm asking if there is a possibility to have white text for example, and certain words in different color.

**Comment by ocornut** [comment] 2017-09-25 17:58
Hello,
Closing this as duplicate of #902 (which is still open).
There's no trivial or standard way to do it without custom code at the moment, but that thread should give you some pointers.

**Closed by ocornut** 2017-09-25 17:58 UTC
