### ISSUE TITLE
ImGui::RenderTextEllipsis needs latin glyph

### ISSUE THREAD

**Issue by jpfphil** [ocornut/imgui#4269] opened 2021-06-25 10:57 UTC
**Version/Branch of Dear ImGui:**

Version: 1.83WIP
Branch: Unknown (Dear ImGui version provided by https://github.com/eliasdaler/imgui-sfml)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx10.cpp + imgui_impl_win32.cpp
Compiler: MSVC 192930038
Operating System: Windows 10 Family VERSION(20H2) BUILD(19042.1052) EXPERIENCE(120.2212.2020.0)

**My Issue:**

Currently working with a chinese font, I don't need to push any latin glyph ranges when adding the font to the atlas.
But a latin character is used in the Dear ImGui code when calculating characters width for tables headers.

**The Code**

In `ImGui::RenderTextEllipsis`, `EllipsisChar` returns `65535`
https://github.com/ocornut/imgui/blob/30224fdde0e8846d38ca175b4355fb3c369b56c5/imgui.cpp#L2785
which triggers the next if state to replace the character used
https://github.com/ocornut/imgui/blob/30224fdde0e8846d38ca175b4355fb3c369b56c5/imgui.cpp#L2787
by the dot character
https://github.com/ocornut/imgui/blob/30224fdde0e8846d38ca175b4355fb3c369b56c5/imgui.cpp#L2789

**The Callstack**

`TLN.exe!ImGui::RenderTextEllipsis(ImDrawList * draw_list, const ImVec2 & pos_min, const ImVec2 & pos_max, float clip_max_x, float ellipsis_max_x, const char * text, const char * text_end_full, const ImVec2 * text_size_if_known) Ligne 2784  C++`
`TLN.exe!ImGui::TableHeader(const char * label) Ligne 2946 C++`
`TLN.exe!ImGui::TableHeadersRow() Ligne 2804 C++`
`TLN.exe!CManager_Window::Wnd_Tasks() Ligne 533  C++`
`TLN.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Ligne 53  C++
[external code]`

**Conclusion**

Without the dot character (0x002E) pushed into the glyph ranges used by the font, it crashes.
Use the unknown character (0xFFFD) instead of the dot character (0x002E) seems to be a good alternative :
L2789 `ellipsis_char = (ImWchar)0xFFFD; `

**Comment by ocornut** [comment] 2021-06-25 13:51
I confirmed that this can crash if:
- the font doesn't have an ellipsis char merged (U+2026 or U+0085)
- AND the font doesn't have a replacement `.` character (U+002E)
- AND the font doesn't have a fallback char merged (default to `?` U+003F)

There are two issues here:
- the ellipsis should find other versions of the `.` character. This will be desirable for Asian-only font. Used U+FF0E for now.
- we need a valid fallback char (regardless of ellipsis rendering). I think the code crash because of a lack of fallback. Even without an ellipsis if you rendering a missing character it would crash.

Both issues should be fixed now.
Pushed two changes: 38165f420f235357516c9fbc79f4713c50d65048 + 9440974f66422d63b2ee6c6288e942ecabd6a521

![image](https://user-images.githubusercontent.com/8225057/123432890-2a519880-d5cb-11eb-871d-87dc671170f4.png)

**Closed by ocornut** 2021-06-25 13:51 UTC
Labels: font/text
