### ISSUE TITLE
Missing mouse cursor with multiple contexts

### ISSUE THREAD

**Issue by temcgraw** [ocornut/imgui#939] opened 2016-12-14 22:30 UTC
I am rendering imgui windows to multiple textures, and each texture has its own context. Everything works in all contexts except the software mouse pointer. I use the default context for the first texture:
`g_Context[0] = ImGui::GetCurrentContext();`
and I create a new context for the other 3 textures:
`g_Context[i] = ImGui::CreateContext();
ImGui::SetCurrentContext(g_Context[i]);`
and I set `io.MouseDrawCursor = true;` for all contexts.

At display time, before rendering to each texture I set the context and check the font texture.
```
ImGui::SetCurrentContext(g_Context[i]);
ImGuiIO& io = ImGui::GetIO();
if (!g_FontTexture)
{
	ImGui_Impl_CreateDeviceObjects();
}
else
{
	io.Fonts->TexID = (void *)(intptr_t)g_FontTexture; //FIXME still getting a square block mouse cursor
}
```

The fonts all look fine, but the mouse cursor is just a square in all textures but the first. Any ideas of what I am doing wrong? Thanks.

**Comment by ocornut** [comment] 2018-01-20 18:57
Hello @temcgraw,

My apologies for completely forgetting about this issue. 

I haven't tried to reproduce it yet, but I can very well see the issue in the code: the UV coordinates for the mouse cursor are stored inside the imgui context during the font atlas build, which is a mistake. I will look into fixing it.

**Comment by ocornut** [comment] 2018-01-20 19:33
This should be fixed now.

**Closed by ocornut** 2018-01-20 19:33 UTC
Labels: bug, font, multi contexts

**Comment by temcgraw** [comment] 2018-01-21 00:09
Great, thanks. I was working around it by copying MouseCursorData from the
first context to all others, but I will get the latest version soon.

Best,

-----------------------------------------------------------
Tim McGraw, Ph.D.
Assistant Professor
Computer Graphics Technology
313 Knoy Hall
Purdue University
http://web.ics.purdue.edu/~tmcgraw/

**Comment by n8vm** [comment] 2018-02-02 22:37
Quick Q,

Now that MouseCursorData has been removed, how can we scale the software rendered cursor?
Previously I was doing this:
`imguiContext->MouseCursorData[c].Size = ImVec2(20.0f, 30.0f);`

**Comment by ocornut** [comment] 2018-02-02 22:50
@n8vm Interesting. Any reason why you were scaling it? It is due to hi-dpi?
I wonder if we should automatically scale the cursor by `io.DisplayFramebufferScale` ?

**Comment by n8vm** [comment] 2018-02-02 23:34
Yup, DPI problems. I'm using ImGui + raycasting in an HTC Vive, and need to render textures with a high DPI to make fonts more legible. As I increase the render resolution, my cursor gets smaller, and I was scaling it up to compensate.

**Comment by ocornut** [comment] 2018-02-02 23:42
Would you be happy if we scaled by `io.DisplayFramebufferScale` exactly, or do you think we need to expose another value?

You can confirm it by adding:
`size = size * g.IO.DisplayFramebufferScale;`

In this block:
```
        // Draw software mouse cursor if requested
        ImVec2 offset, size, uv[4];
        if (g.IO.MouseDrawCursor && g.IO.Fonts->GetMouseCursorTexData(g.MouseCursor, &offset, &size, &uv[0], &uv[2]))
        {
            const ImVec2 pos = g.IO.MousePos - offset;
            const ImTextureID tex_id = g.IO.Fonts->TexID;
            size = size * g.IO.DisplayFramebufferScale;
```
If it works I'll commit that.

**Comment by n8vm** [comment] 2018-02-03 00:54
Hmm, DPI vs scale is a little confusing. I suppose this has more to do with the following commands than with DisplayFramebufferScale.
```
ImGuiIO& io = ImGui::GetIO();
ImGuiStyle& style = ImGui::GetStyle();
style.ScaleAllSizes(2.0);
io.FontGlobalScale = 2.0;
```
The above commands don't have an effect on the cursor size, so I was manually scaling the cursor up to compensate. In addition to increasing DPI, having the ability to literally scale elements up in a scene can be helpful in VR. So, if anything, I'd want mouse cursor size to scale with the "ScaleAllSizes" command, and not by g.IO.DisplayFramebufferScale. 

I tried scaling the cursor size with the frame buffer scale, but it seems like this DPI scaling already happens. By increasing the cursor size with frame buffer scale, the cursor grows disproportionately faster than GUI elements.

**Comment by n8vm** [comment] 2018-02-03 01:02
![image](https://user-images.githubusercontent.com/13104331/35761124-74953a50-0842-11e8-9e65-7f2c5b320251.png)

![image](https://user-images.githubusercontent.com/13104331/35761133-9e4da418-0842-11e8-808e-bceec4feb080.png)

Low DPI vs High DPI without any changes seems good.

![image](https://user-images.githubusercontent.com/13104331/35761158-cdfadf5a-0842-11e8-8c47-8fe3c47149aa.png)
After scaling, cursor is disproportionately small compared to GUI.

I think this might be a special case scenario, since on desktop I wouldn't want the cursor to increase in size. However in VR, I'd like to make the cursor larger so that it's easier to see.

I think another value should be exposed.

**Comment by ocornut** [comment] 2018-02-04 11:21
@n8vm I have added a `style.MouseCursorScale` value and it is now scaled by the `ScaleAllSizes()` call.
I however consider this a temporary workaround and will aim to get it removed once we have a better solution.

In that situation we probably want to get the mouse cursor copied to the the texture in double resolution so it stays sharp when renderer with bilinear filtering. This is analogous to the problem with the default font, which looks terrible when scaled twice. I'll have a pass in the future at improving the Hi-DPI and multiple-DPI-on-multiple-screen experience with the default example and font, it's pretty bad at the moment.
