### ISSUE TITLE
How to get empty docking area?

### ISSUE THREAD

**Issue by Cop46** [ocornut/imgui#5921] opened 2022-11-25 17:06 UTC
I would like to know if this is possible to get the position and size of the empty area like in the screenshot (red square) please ?
In advance Thanks !
![RedSquare](https://user-images.githubusercontent.com/32778861/204030614-f41cd362-0645-435f-a9b1-3e43d5a789d5.png)

**Comment by PathogenDavid** [comment] 2022-11-25 19:17
There's two main ways to handle central viewports like this, both require using `imgui_internal.h` (They're internal as they're still being worked on and might change in the future.)

The most straightforward way is to disable docking in the central node and use `DockBuilderGetCentralNode` to get its size:

```cpp
ImGuiID id = ImGui::DockSpaceOverViewport(nullptr, ImGuiDockNodeFlags_NoDockingInCentralNode | ImGuiDockNodeFlags_PassthruCentralNode, nullptr);
ImGuiDockNode* node = ImGui::DockBuilderGetCentralNode(id);

// Draw a red rectangle in the central node just for demonstration purposes
ImGui::GetBackgroundDrawList()->AddRect
(
    node->Pos,
    { node->Pos.x + node->Size.x, node->Pos.y + node->Size.y },
    IM_COL32(255, 0, 0, 255),
    0.f,
    ImDrawFlags_None,
    3.f
);
```

![Screenshot of Dear ImGui example app with windows docked on all sides with a red rectangle in the central node.](https://user-images.githubusercontent.com/278957/204043377-91db8ff1-3d48-4451-8882-cd27d99de0be.png)

-----------------

The alternative approach is to pin a window into the central node and prohibit docking over it:

```cpp
D id = ImGui::DockSpaceOverViewport(nullptr, ImGuiDockNodeFlags_NoDockingInCentralNode | ImGuiDockNodeFlags_PassthruCentralNode, nullptr);
ImGuiDockNode* node = ImGui::DockBuilderGetCentralNode(id);

ImGuiWindowClass centralAlways = {};
centralAlways.DockNodeFlagsOverrideSet |= ImGuiDockNodeFlags_NoTabBar | ImGuiDockNodeFlags_NoDockingOverMe;
ImGui::SetNextWindowClass(&centralAlways);
ImGui::SetNextWindowDockID(node->ID, ImGuiCond_Always);
ImGui::Begin("GH-5921");
ImGui::Text("Central node: (%f, %f)..(%fx%f)", node->Pos.x, node->Pos.y, node->Size.x, node->Size.y);
ImGui::End();
```

(With this approach you'd render your scene to a texture you'd submit to this window using `ImGui::Image`)

![Screenshot of Dear ImGui example app with windows docked on all sides with a window reading 'Central node: (300,0)..(447x361)' in the central node.](https://user-images.githubusercontent.com/278957/204043719-057177a2-aa8a-4757-99ec-8dac135fca43.png)

------------------

See also: https://github.com/ocornut/imgui/issues/4119 https://github.com/ocornut/imgui/issues/4102 https://github.com/ocornut/imgui/issues/2651 https://github.com/ocornut/imgui/issues/2423

**Comment by Cop46** [comment] 2022-11-25 19:49
Many thanks for your answer that help me a lot !

**Comment by ocornut** [comment] 2022-11-28 14:33
Thank you David for your answer! Closing this.

**Closed by ocornut** 2022-11-28 14:33 UTC
Labels: docking

**Comment by jeremyong** [comment] 2023-01-18 12:43
@PathogenDavid Thanks for the snippets! I'm trying the approach where I render the scene to an image and render from the image to a window pinned to the central node as you have there. However, the window created in this way appears to have a scrollbar, and it isn't clear why the dimensions of the central node don't match what's displayed. Do you have any suggestions for diagnosing this?

**Comment by PathogenDavid** [comment] 2023-01-18 13:49
@jeremyong Glad you found them useful!

> However, the window created in this way appears to have a scrollbar

Ah yeah, that's being caused by the window padding. I should've included a call to `PushStyleVar`/`PopStyleVar` to remove it, sorry about that!

I went back and updated the snippet above.

**Comment by jeremyong** [comment] 2023-01-18 14:27
Ah of course, I should have checked that thanks! For some reason I thought the dock node flags might remove other window decorations but it also makes sense that it didn't as well.
