### ISSUE TITLE
Dx9 Swapchain issue

### ISSUE THREAD

**Issue by xMikan09** [ocornut/imgui#2750] opened 2019-08-25 00:21 UTC
**Version/Branch of Dear ImGui:**

Version: 1.63

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp

Operating System: Windows 7

**My Issue/Question:**

I tried creating multiple window version of imgui, but it is unclickable and distorted. It also crashes when I try to resize the window.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/45003438/63643970-2f173e00-c70f-11e9-97fa-cd64b64534ed.png)

1st Window:
      `
void myUI::RenderMainWindow(HWND hwnd, LPDIRECT3DSWAPCHAIN9 swapchain)
{
  LPDIRECT3DSURFACE9 pBackBuffer = NULL;
	swapchain->GetBackBuffer(0, D3DBACKBUFFER_TYPE_MONO, &pBackBuffer);
	g_pd3dDevice->SetRenderTarget(0, pBackBuffer);

	ImGui_ImplDX9_NewFrame();
	ImGui_ImplWin32_NewFrame();
	ImGui::NewFrame();
	Loader->Initialize(Loader->GetLoaderWindowState());
	
	ImGui::EndFrame();
	g_pd3dDevice->Clear(0, NULL, D3DCLEAR_TARGET | D3DCLEAR_ZBUFFER,
		D3DCOLOR_COLORVALUE(1.0f, 0.0f, 0.0f, 1.0f), 1.0f, 0);

	if (g_pd3dDevice->BeginScene() >= 0)
	{
		ImGui::Render();
		ImGui_ImplDX9_RenderDrawData(ImGui::GetDrawData());
		g_pd3dDevice->EndScene();
	}

	HRESULT result = swapchain->Present(NULL, NULL, hwnd, NULL,0);

	pBackBuffer->Release();
}
`

2nd Window:
                `
void myUI::RenderFriendWindow(HWND hwnd, LPDIRECT3DSWAPCHAIN9 swapchain)
{
LPDIRECT3DSURFACE9 pBackBuffer = NULL;
               	swapchain->GetBackBuffer(0, D3DBACKBUFFER_TYPE_MONO, &pBackBuffer);
          	g_pd3dDevice->SetRenderTarget(0, pBackBuffer);
	
	        g_pd3dDevice->Clear(0, NULL, D3DCLEAR_TARGET | D3DCLEAR_ZBUFFER,
		D3DCOLOR_COLORVALUE(0.0f, 1.0f, 0.0f, 1.0f), 1.0f, 0);
		ImGui_ImplDX9_NewFrame();
		ImGui_ImplWin32_NewFrame();
		ImGui::NewFrame();
		if (ImGui::Begin("AAAAAAAADDDAAAA", NULL))
		{
			static bool tbox = false; 
			ImGui::Checkbox("Test Checkbox",&tbox);
			ImGui::End();
		}
		ImGui::EndFrame();
	if (g_pd3dDevice->BeginScene() >= 0)
	{
		ImGui::Render();
		ImGui_ImplDX9_RenderDrawData(ImGui::GetDrawData());
		g_pd3dDevice->EndScene();
	}

	HRESULT result = swapchain->Present(NULL, NULL, hwnd, NULL, 0);

	if (result == D3DERR_DEVICELOST && g_pd3dDevice->TestCooperativeLevel() == D3DERR_DEVICENOTRESET)
	{
		ImGui_ImplDX9_InvalidateDeviceObjects();
		g_pd3dDevice->Reset(&d3dpp);
		ImGui_ImplDX9_CreateDeviceObjects();
	}
	pBackBuffer->Release();
}
`

`
void myUI::Initialize(HINSTANCE hInstance)
{
	MSG        uMsg;
	instance = hInstance;
	memset(&uMsg, 0, sizeof(uMsg));

	winClass.lpszClassName = L"wndClass_KokoroUI";
	winClass.cbSize = sizeof(WNDCLASSEX);
	winClass.style = CS_HREDRAW | CS_VREDRAW;
	winClass.lpfnWndProc = m_WndProc;
	winClass.hInstance = hInstance;
	winClass.hIcon = NULL;
	winClass.hIconSm = NULL;
	winClass.hCursor = LoadCursor(NULL, IDC_ARROW);
	winClass.hbrBackground = (HBRUSH)GetStockObject(BLACK_BRUSH);
	winClass.lpszMenuName = NULL;
	winClass.cbClsExtra = 0;
	winClass.cbWndExtra = 0;

	if (!RegisterClassEx(&winClass))
		return;

	MainWnd = CreateWindowEx(NULL, winClass.lpszClassName,
		L"KokoroUI",
		WS_OVERLAPPEDWINDOW,
		0, 0, 800, 400, NULL, NULL, hInstance, NULL);
	
	int RightPos = WndTools->GetWindowPos(MainWnd).X + WndTools->GetWindowSize(MainWnd).X + 10;
	
	FriendWnd = CreateWindowEx(NULL, winClass.lpszClassName,
		L"Friend List [KokoroUI]",
		WS_OVERLAPPEDWINDOW,
		RightPos, 0, 200, 400, NULL, NULL, hInstance, NULL);
	
	
	if (MainWnd == NULL)
		return;

	ShowWindow(MainWnd, SW_SHOWDEFAULT);
	UpdateWindow(MainWnd);
	ShowWindow(FriendWnd, SW_SHOWDEFAULT);
	UpdateWindow(FriendWnd);
	if ((g_pD3D = Direct3DCreate9(D3D_SDK_VERSION)) == NULL)
	{
		UnregisterClass(winClass.lpszClassName, winClass.hInstance);
		return ;
	}
	D3DDISPLAYMODE d3ddm;

	g_pD3D->GetAdapterDisplayMode(D3DADAPTER_DEFAULT, &d3ddm);

	ZeroMemory(&d3dpp, sizeof(d3dpp));
	d3dpp.Windowed = TRUE;
	d3dpp.SwapEffect = D3DSWAPEFFECT_COPY;
	d3dpp.BackBufferFormat = d3ddm.Format;
	d3dpp.EnableAutoDepthStencil = TRUE;
	d3dpp.AutoDepthStencilFormat = D3DFMT_D16;
	d3dpp.PresentationInterval = D3DPRESENT_INTERVAL_ONE; 
	if (g_pD3D->CreateDevice(D3DADAPTER_DEFAULT, D3DDEVTYPE_HAL,MainWnd, D3DCREATE_HARDWARE_VERTEXPROCESSING/*D3DCREATE_SOFTWARE_VERTEXPROCESSING*/,&d3dpp, &g_pd3dDevice)< 0)
	{
		g_pD3D->Release();
		UnregisterClass(winClass.lpszClassName, winClass.hInstance);
		return;
	}
	g_pd3dDevice->GetSwapChain(0, &g_swapChain_0);
	g_pd3dDevice->CreateAdditionalSwapChain(&d3dpp, &g_swapChain_Frnd);

	IMGUI_CHECKVERSION();
	ImGui::CreateContext();
	ImGuiIO &io = ImGui::GetIO();
	(void)io;
	ImGui_ImplWin32_Init(MainWnd);

	ImGui_ImplDX9_Init(g_pd3dDevice);

	ImGui::StyleColorsDark();

	while (uMsg.message != WM_QUIT)
	{
		if (PeekMessage(&uMsg, NULL, 0, 0, PM_REMOVE))
		{
			TranslateMessage(&uMsg);
			DispatchMessage(&uMsg);
		}
		else
		{
			RenderMainWindow(MainWnd, g_swapChain_0);
			RenderFriendWindow(FriendWnd, g_swapChain_Frnd);
		}
	}

	Uninitialize();

	UnregisterClassW(winClass.lpszClassName, winClass.hInstance);

	return;
}
`

**Comment by ocornut** [comment] 2019-08-25 10:47
Hello,
It is unclear why exactly you are trying to achieve that but you should checkout the latest version of the docking branch with multi-viewports enabled. This is probably going to solve your needs

**Comment by xMikan09** [comment] 2019-08-31 06:43
this is exactly what i'm looking for, but for some reason the ImGui::GetWindowPos() gives the absolute position of the imgui window, instead of a relative position from the window where it was created.
And also, for some odd reason, i'm getting exceptions at DrawIndexPrimitive(image below) when using local windows debugger inside visual studio, but when I run it normally, it works fine.

![image](https://user-images.githubusercontent.com/45003438/64060328-99434d80-cbfd-11e9-8bcd-c42f9e7568f0.png)

**Comment by ocornut** [comment] 2019-08-31 12:53
> this is exactly what i'm looking for

But your attempt/solution highlighted above didn't involve the multi-viewports feature at all?

> for some reason the ImGui::GetWindowPos() gives the absolute position of the imgui window,

This is intended when multi-viewports are enabled. What's the probem with that?

> And also, for some odd reason, i'm getting exceptions at DrawIndexPrimitive(image below) 

Do you get any issue when running `examples/example_win32_directx9/` or are you running your own app? If the example doesn't crash the problem is probably somewhere in your app.

**Comment by xMikan09** [comment] 2019-09-01 03:26
> This is intended when multi-viewports are enabled. What's the probem with that?

is there a way to get the relative position when in multiple viewports mode?

> Do you get any issue when running examples/example_win32_directx9/ or are you running your own app? If the example doesn't crash the problem is probably somewhere in your app.

I found the cause, and it's when the imgui window's start position from the imgui config is outside the HWND, or if I minimize the window while the imgui window is outside. The link below shows how it happens

https://www.youtube.com/watch?v=PlGeZOIF-5A&feature=youtu.be

**Comment by ocornut** [comment] 2019-09-01 05:30
> is there a way to get the relative position when in multiple viewports mode?

You haven’t answered my question.

> I found the cause [...]

You haven’t answered my question.

If you don’t read and answer question it is difficult to help you.

**Comment by xMikan09** [comment] 2019-09-02 02:29
> But your attempt/solution highlighted above didn't involve the multi-viewports feature at all?

I used the io option for the multiple viewports after you recommended the latest version of the docking branch

**Comment by ocornut** [comment] 2019-09-17 13:59
Closing this as you are not answeing questions being asked and it is still unclear what you are trying to do and what your problems are.

**Closed by ocornut** 2019-09-17 13:59 UTC
Labels: backend/binding
