### ISSUE TITLE
Crash while using imgui via RDP

### ISSUE THREAD

**Issue by Remist0** [ocornut/imgui#3065] opened 2020-03-20 06:26 UTC
**Version/Branch of Dear ImGui:**

Version:  v1.74 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Operating System: Windows via RDP

**My Issue/Question:**

Assert triggers when I close my RDP connection while my application still running on remote device.

**Screenshots/Video**

![2b497d490b506437ef7953e59464](https://user-images.githubusercontent.com/2908998/77140522-b8230780-6a9b-11ea-85e7-012b2e2f272b.png)

**Comment by ocornut** [comment] 2020-03-20 06:33
Please provide all information requested by issue template.

Try to debug the updatemonitor function of the backend and see why it is failing to get a monitor list.

Post a comment when information was added and will reopen.

**Comment by rokups** [comment] 2020-03-24 09:01
For what its worth i could not reproduce the issue. Example application keeps running when RDP is disconnected and reconnected.

**Comment by ocornut** [comment] 2020-03-24 09:59
@Remist0 Could you specify which back-end you used and which Windows version?

I can imagine a scenario where number of monitor would drop to zero when not connected. The assert in `NewFrame()` is designed as a documentation, so it would be up to back-end to perhaps disable the `ImGuiBackendFlags_PlatformHasViewports` flag if monitor count is zero. But that's a lossy operation at it means imgui windows would be moved back to main viewport when closing and reopening the RDP connection.

We'd need a repro and probably the problem needs to be tackled separately in all 3 major platform back-ends (win32/sdl/glfw). Maybe they don't have the same problem this is why it's useful to get the missing details from @Remist0.

One possible workaround would be to keep the last sets of monitor if they drop to zero, so e.g. `ImGui_ImplWin32_UpdateMonitors()` would use static vector, empty, push, and only swap with dear imgui's copy if not zero at the end of the frame, with the appropriate dose of comments. 

Specifically in the case of the win32 backend this perhaps could be done only if `GetSystemMetrics(SystemMetric.SM_REMOTESESSION)` to be explicit on the intent.

Either way we probably shouldn't attempt a blind fix without being able to repro on our end.

**Comment by Remist0** [comment] 2020-03-24 17:33
@ocornut We're using win32 platform and Win10Pro.
I'm now discussing this issue with my team, maybe problem lies in our custom imgui wrapper. Will provide you more info after we figure it out.

**Comment by Remist0** [comment] 2020-03-24 18:05
Maybe this can help: we counting monitor devices with DXGI (not EnumDisplayDevices).

**Comment by ocornut** [comment] 2020-03-24 18:24
So you are using a custom back-end.. would have saved time if you specified that in the first message (as requested by the template).

In this case fixing our back-ends won't help you and we can't fix them on our end without a repro.
If you enable multi-viewports you need a monitor list, if you don't have one you can either
(1) disable multi-viewports, trivial, but "lossy"
(2) preserve old monitor list, and avoid rendering all together maybe
But that's all changes in your back-ends or application.

**Comment by ocornut** [comment] 2020-05-09 16:33
Closing as not our code. If we can replicate the issue with imgui_impl_win32.cpp or other standard  back-ends we'll come up with a solution (e.g. preserve monitors temporarily).

**Closed by ocornut** 2020-05-09 16:33 UTC
Labels: backend/binding, multi-viewport
