### ISSUE TITLE
ImVector erase assertion failure

### ISSUE THREAD

**Issue by sigmareaver** [ocornut/imgui#5009] opened 2022-02-12 01:52 UTC
**Version/Branch of Dear ImGui:**

Version: 1.87 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl2.cpp
Compiler: MSVC v142 C++ (x86 Debug configuration)
Operating System: Windows 7

**My Issue/Question:**
Assertion failed:
`it >= Data && it < Data + Size && it_last > it && it_last <= Data + Size, file \imgui\imgui.h, line 1807`

Stacktrace:
```
ImVector<ImGuiInputEvent>::erase(const ImGuiInputEvent * it=0x0871fbf0, const ImGuiInputEvent * it_last=0x0871fbf0) Line 1807	C++
ImGui::UpdateInputEvents(bool trickle_fast_inputs=true) Line 7871	C++
ImGui::NewFrame() Line 4329	C++
```

**Screenshot**
[![Capture.png](https://i.postimg.cc/RZWTG994/Capture.png)](https://postimg.cc/PCkZrgPR)
[![Untitled.png](https://i.postimg.cc/28MWkWRN/Untitled.png)](https://postimg.cc/fJ7y5JR8)
[![Untitled2.png](https://i.postimg.cc/HsdYQsw8/Untitled2.png)](https://postimg.cc/Z0szmmDJ)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
The assertion occurred while I was moving a slider (`FrameRounding`) in the `ImGui::ShowStyleEditor();`

This isn't the first time I've had ImGui crash while playing with the built-in style editor, but it's very rare.

So, it's doing `g.InputEventsQueue.erase(g.InputEventsQueue.Data, g.InputEventsQueue.Data + event_n);`
I'm noticing that `g.InputEventsQueue.Data` has an address of `0x0870e2e8` in the frame that is calling `erase`, yet inside of erase, the iterator argument passed in has a different address of `0x0871fbf0`?

**Comment by sigmareaver** [comment] 2022-02-12 19:58
Additional notes:
This crash seems to be happening more frequently. Things I've changed since it started happening frequently are:
- Using ImGui Freetype
- Loading a non-default font

I had it happen in two different finite state machine states. The GUI code I use in each state is completely different except for the StyleEditor window. For testing, I'm using that in both states. This second time it's crashed, I wasn't doing anything except moving the mouse across the application window.

Can this be related to the way I pass events to ImGui?

**Comment by PathogenDavid** [comment] 2022-02-12 23:04
What platform backend are you using?

Can you reproduce this issue in the official demo?

**Comment by sigmareaver** [comment] 2022-02-13 08:55
I'm using OpenGL 1/2. I haven't attempted to reproduce this with the official demo.
I found this:
https://stackoverflow.com/questions/433274/c-parameters-value-changes-between-stack-frames-in-stdvector
I believe this issue is related.

**Comment by thedmd** [comment] 2022-02-13 12:29
It looks like `it_last > it` condition should be `it_last >= it`.

This code should not assert:
```cpp
ImVector<int> foo;
foo.push_back(10);
foo.erase(foo.begin(), foo.begin());
IM_ASSERT(foo.size() == 1);
IM_ASSERT(foo[0] == 10);
```

```diff
 imgui.h | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/imgui.h b/imgui.h
index 2204a86d5..a3e497cf7 100644
--- a/imgui.h
+++ b/imgui.h
@@ -1815,7 +1815,7 @@ struct ImVector
     inline void         pop_back()                          { IM_ASSERT(Size > 0); Size--; }
     inline void         push_front(const T& v)              { if (Size == 0) push_back(v); else insert(Data, v); }
     inline T*           erase(const T* it)                  { IM_ASSERT(it >= Data && it < Data + Size); const ptrdiff_t off = it - Data; memmove(Data + off, Data + off + 1, ((size_t)Size - (size_t)off - 1) * sizeof(T)); Size--; return Data + off; }
-    inline T*           erase(const T* it, const T* it_last){ IM_ASSERT(it >= Data && it < Data + Size && it_last > it && it_last <= Data + Size); const ptrdiff_t count = it_last - it; const ptrdiff_t off = it - Data; memmove(Data + off, Data + off + count, ((size_t)Size - (size_t)off - (size_t)count) * sizeof(T)); Size -= (int)count; return Data + off; }
+    inline T*           erase(const T* it, const T* it_last){ IM_ASSERT(it >= Data && it < Data + Size && it_last >= it && it_last <= Data + Size); const ptrdiff_t count = it_last - it; const ptrdiff_t off = it - Data; memmove(Data + off, Data + off + count, ((size_t)Size - (size_t)off - (size_t)count) * sizeof(T)); Size -= (int)count; return Data + off; }
     inline T*           erase_unsorted(const T* it)         { IM_ASSERT(it >= Data && it < Data + Size);  const ptrdiff_t off = it - Data; if (it < Data + Size - 1) memcpy(Data + off, Data + Size - 1, sizeof(T)); Size--; return Data + off; }
     inline T*           insert(const T* it, const T& v)     { IM_ASSERT(it >= Data && it <= Data + Size); const ptrdiff_t off = it - Data; if (Size == Capacity) reserve(_grow_capacity(Size + 1)); if (off < (int)Size) memmove(Data + off + 1, Data + off, ((size_t)Size - (size_t)off) * sizeof(T)); memcpy(&Data[off], &v, sizeof(v)); Size++; return Data + off; }
     inline bool         contains(const T& v) const          { const T* data = Data;  const T* data_end = Data + Size; while (data < data_end) if (*data++ == v) return true; return false; }
```

**Comment by sigmareaver** [comment] 2022-02-13 19:29
@PathogenDavid Ah, sorry. I'm using a modified version of One Lone Coder Pixel Game Engine. Although it is cross-platform, I'm only developing on Win32. OLC PGE is a single header, and for all intents and purposes can just be considered a Win32 backend.

**Comment by sigmareaver** [comment] 2022-02-15 01:42
I haven't been able to reproduce the behavior, so I have to believe it was due to either ImGui and my project being compiled with different flags, or because of MSVC's iterator debugging. In any case, I'm going to close this issue now.

@thedmd I don't believe that is related to my issue, which involved parameters being passed to `erase()` becoming invalid between stack frames.

Apologies for any inconvenience.

**Comment by sigmareaver** [comment] 2022-02-15 05:00
Well, I guess I spoke too soon. I just had this issue happen again. It's just extremely intermittent. It can happen twice in a row, or I can go a day without it happening at all. That is going to make tracking this down extremely painful I fear. I do not see a way I can create a minimum working example that reproduces this behavior if it simply happens so randomly.

**Comment by thedmd** [comment] 2022-02-15 06:23
> It looks like `it_last > it` condition should be `it_last >= it`.
> 
> This code should not assert:
> 
> ```c++
> ImVector<int> foo;
> foo.push_back(10);
> foo.erase(foo.begin(), foo.begin());
> IM_ASSERT(foo.size() == 1);
> IM_ASSERT(foo[0] == 10);
> ```
> 
> ```diff
>  imgui.h | 2 +-
>  1 file changed, 1 insertion(+), 1 deletion(-)
> 
> diff --git a/imgui.h b/imgui.h
> index 2204a86d5..a3e497cf7 100644
> --- a/imgui.h
> +++ b/imgui.h
> @@ -1815,7 +1815,7 @@ struct ImVector
>      inline void         pop_back()                          { IM_ASSERT(Size > 0); Size--; }
>      inline void         push_front(const T& v)              { if (Size == 0) push_back(v); else insert(Data, v); }
>      inline T*           erase(const T* it)                  { IM_ASSERT(it >= Data && it < Data + Size); const ptrdiff_t off = it - Data; memmove(Data + off, Data + off + 1, ((size_t)Size - (size_t)off - 1) * sizeof(T)); Size--; return Data + off; }
> -    inline T*           erase(const T* it, const T* it_last){ IM_ASSERT(it >= Data && it < Data + Size && it_last > it && it_last <= Data + Size); const ptrdiff_t count = it_last - it; const ptrdiff_t off = it - Data; memmove(Data + off, Data + off + count, ((size_t)Size - (size_t)off - (size_t)count) * sizeof(T)); Size -= (int)count; return Data + off; }
> +    inline T*           erase(const T* it, const T* it_last){ IM_ASSERT(it >= Data && it < Data + Size && it_last >= it && it_last <= Data + Size); const ptrdiff_t count = it_last - it; const ptrdiff_t off = it - Data; memmove(Data + off, Data + off + count, ((size_t)Size - (size_t)off - (size_t)count) * sizeof(T)); Size -= (int)count; return Data + off; }
>      inline T*           erase_unsorted(const T* it)         { IM_ASSERT(it >= Data && it < Data + Size);  const ptrdiff_t off = it - Data; if (it < Data + Size - 1) memcpy(Data + off, Data + Size - 1, sizeof(T)); Size--; return Data + off; }
>      inline T*           insert(const T* it, const T& v)     { IM_ASSERT(it >= Data && it <= Data + Size); const ptrdiff_t off = it - Data; if (Size == Capacity) reserve(_grow_capacity(Size + 1)); if (off < (int)Size) memmove(Data + off + 1, Data + off, ((size_t)Size - (size_t)off) * sizeof(T)); memcpy(&Data[off], &v, sizeof(v)); Size++; return Data + off; }
>      inline bool         contains(const T& v) const          { const T* data = Data;  const T* data_end = Data + Size; while (data < data_end) if (*data++ == v) return true; return false; }
> ```

@ocornut Would you consider patching this assertion condition?

@sigmareaver Assertion is still incorrect.
You may hit it when no events were consumed in current frame, but are still queued. I'm not sure how to craft a repro. I would have to look closer at the code. It does look like fixing assertion should also solve your problem.
Or did you got it with patch I posted earlier applied?

**Comment by sigmareaver** [comment] 2022-02-15 06:44
@thedmd No I did not. I actually currently have unrolled the IM_ASSERT macro so that I could put breakpoints inside. I could add this change and see if the assert still triggers.

**Comment by thedmd** [comment] 2022-02-15 07:48
No, no. The point is call to `erase` when `event_n == 0` should not assert. `event_n == 0` is valid case.
Adding `if (event_n > 0)` in `UpdateInputEvent()` is workaround, does not fix the underlying issue.

I'm following the assumption that `ImVector::erase` API should not be surprising and should have same preconditions like `std::vector::erase`.

**Comment by ocornut** [comment] 2022-02-15 07:55
Will fix, thanks both for looking into it.

**Comment by ocornut** [comment] 2022-02-15 10:17
I merged the fix suggested by thedmd.

I however can't see how it is possible for `event_n` to be 0 here without a some form of data corruption and missing asserts, so I'm pretty sure you also have a problem on your end, which our fix may contribute hiding.

**Closed by ocornut** 2022-02-15 10:17 UTC

**Comment by ocornut** [comment] 2022-02-16 18:52
Apologies, the previous commit actually missed the change (I did some revert to ensure new tests were failing and lost that change). Actual fix now pushed.
