### ISSUE TITLE
Losing drag and drop when clipped or source item becomes not visible / or not submitted anymore

### ISSUE THREAD

**Issue by e3dos** [ocornut/imgui#1725] opened 2018-04-06 06:43 UTC
Hi! I'm implementing a list where I can reorder the elements of the list.
It's working quite ok, but the problem is when I have a big list. If I want to drag the first element to the bottom of the list, I need to use the scroll while holding the left mouse button. While scrolling with the mouse I lose the payload.
Funny fact is that, the only payload that is not lost while scrolling is the first element of the list. The rest of the elements get lost after they go out of screen;
I think that the ImGuiListClipper is causing that. Is there a way to have the element of BeginDragDropSource() alive while scrolling like the first one?

**Comment by ocornut** [comment] 2018-04-06 06:52
Interesting- yeah, it is quite possible that the list clipper would get in the way there.

Just in case, which kind of item are you dragging? Do they have a explicit ID or not? (asking because it also has an effect on dragging).

**Comment by exsec** [comment] 2018-04-06 15:35
I'm using

`ImGui::TreePush("spaceTops");
ImGui::Unindent(ImGui::GetTreeNodeToLabelSpacing());
ImGui::Dummy(ImVec2(ImGui::GetWindowWidth()*0.92, 3));
ImGui::Indent(ImGui::GetTreeNodeToLabelSpacing());

			if (ImGui::BeginDragDropTarget())	
				{

					if (!(i == ((int*)payload->Data)[1]) && !(i == ((int*)payload->Data)[1] + 1)) {
						int destinyIndex = i > ((int*)payload->Data)[1] ? i - 1 : i;

						(*objList).erase((*objList).begin() + ((int*)payload->Data)[1]);
						(*objList).emplace((*objList).begin() + destinyIndex, ((int*)payload->Data)[0]);

					}
				}
				ImGui::EndDragDropTarget();
			}
			ImGui::TreePop();

			ImGui::TreeNodeEx((void*)(intptr_t)i, node_flags, object->getObjName().c_str());

			if (ImGui::BeginDragDropSource())
			{
				int data[2];
				data[0] = (*objList)[i]; //id
				data[1] = i; //sourceIndex
							 
				ImGui::SetDragDropPayload("objList", &data, sizeof(data));
				ImGui::TextUnformatted(object->getObjName().c_str());
				ImGui::EndDragDropSource();
			}`

**Comment by ocornut** [comment] 2018-04-09 11:47
> Which id are you talking about, the the beginDragDropSource or the node ImGui::TreeNodeEx((void*)(intptr_t)i 

Was talking about the ID of the item being the source, in this case it is a TreeNode and it has an ID (if you use a Text element as a drag source there's specific code that creates an ID for it).

So basically we need to rework the clipper to be able to specify one or more rectangles that needs to be rendered and cannot be clipped, and the code instead of being hardcoded to 2-3 steps will need at each step to figure out how far it is allowed to go during this step.

**Comment by exsec** [comment] 2018-04-09 15:41
Or make a way to set the drag drop payload persist beyond BeginDragDropSource() while holding the mouse.

**Comment by ocornut** [comment] 2018-04-09 15:57
Very good point. The payload already persist for a frame then discarded if the drag source is not resubmitted. Should be possible to make it not expire, with a flag to force fast expiration (if holding eg pointers?)

**Comment by exsec** [comment] 2018-04-09 16:35
Data must be "newed" then, is there a way to run a event to delete them? after a mouse release, or release of payload to somewhere.

**Comment by ocornut** [comment] 2018-04-09 16:37
The payload is already copied into a persistent buffer when you submit it. There’s no need for much more, just making it not expire.

**Comment by ocornut** [comment] 2018-04-09 17:03
I tried it now (changing the expiration rule to poll the mouse). The problem is that the preview tooltip is up to the source so we are losing the preview and it looks broken even though the drop operation can work. 

To fix it we would need to e.g. preserve the content of the window (reuse old vertices, translated), it's technically feasible but really at odd with the sort of thing imgui is typically doing. I think it would be more reasonable to improve the clipper to handle that sort of case.

**Comment by exsec** [comment] 2018-04-10 01:31
I'm fine if we could have that option to persist the payload, even without the tooltip

**Comment by ocornut** [comment] 2018-07-28 18:16
I'm running into the same problem with cross-tabs drag and dropping (which become more frequent and easy with upcoming docking facilities)... and the hypothetical fix on the source (fixing the clipper) becomes inadequate. Really stuck as to how we can possibly solve that..

For the sake of brainstorming: 
- We could allow code to submit drag and drop preview tooltips from a different location as the emitter, by peeking into the current payload. This creates the constraint that the full tooltip contents need to be easily derivable from the payload (which sounds obvious, but currently we have more flexibility than that, e.g. when can display a name associated to the source item that not actually held in the payload).
- Tabs/Docking system could keep the source Tab/Dock "running" but hidden while dragging to ensure the code at the source is still running...

Any other idea? (ping @sherief who seem to fancy drag and drop)

**Comment by ocornut** [comment] 2018-07-28 21:02
Status update (aka rambling out loud): I'm working on this now:

(1) 
Made change to the drag and drop system to allow carrying the payload after the source disappeared.
It's not committed yet as I'm testing and trying to making sure the changes are not bringing in new bugs.

By defaults to a tooltip showing "..." which is not ideal, but this is still a usability improvement over the drag and drop mysteriously failing.
![20180724_drag_inactive_source](https://user-images.githubusercontent.com/8225057/43360551-756626d8-92b7-11e8-8f37-9f2489457570.gif)
(@e3dos Your case with the clipper would be identical.)

(2) 
Working on a system to be able to provide tool-tip describing the source given a payload, so that the tooltip code can optionally be in a separate location. It seems to works, but need to find a suitable API for it, e.g. something like:
`IMGUI_API const ImGuiPayload* BeginDragDropPayloadTooltip(const char* type);`
But needs to be aware of various situations: maybe you don't want to overwrite an existing tooltip? What if function is called earlier in the frame than the `BeginDragDropSource()` call? Would order means that later one wins it?

Maybe upon solving this we could decide that this method is the _preferred_ method for creating a tooltip describing the drag and drop payload, and maybe the current method could be phased out? There's currently a `ImGuiDragDropFlags_SourceNoPreviewTooltip` flag to disable the tooltip which could possibly be the default (but that would be a breaking change) or possibly I could detect it automatically, so BeginDragDropSource() could always begin into a Tooltip but hide it if nothing has been added to it...

EndFrame() will automatically handle the payload tooltip for the types that core imgui is emitting (`IMGUI_PAYLOAD_TYPE_COLOR_3F` and `IMGUI_PAYLOAD_TYPE_COLOR_4F`). For user code, if you are emitting payload of a certain type locally, you can call that hypothetical `BeginDragDropPayloadTooltip(const char* type);` anywhere yourself. If you don't do it and your drag source disappear then you are loosing the tool-tip.

(3) 
The ordering problem in 2) is analogous to another problem I have where I wanted to make it possible for the Target to output a different tooltip than the one emitted by the source. We have an ordering issue here, which I can workaround because it's easy to decide that the Target has higher priority than the source. 

---

I may try to finish (1) and commit that quick because I'm not sure I can spend lots of time on (2) right now. Trying to focus on Docking, it's just that this issue became much more visible with the increasing amount of Tabs in my WIP docking branch.

**Comment by e3dos** [comment] 2018-07-31 18:29
Thanks Omar, these changes are very welcome.

**Comment by ocornut** [comment] 2021-11-04 13:21
As per #3841, ImGuiListClipper was now improved and among other things will automatically include the last focused (`g.NavId`) item so this issue should be solved.

The ideas discussed in https://github.com/ocornut/imgui/issues/1725#issuecomment-408634674 to provide tooltips at a different location than the source are still valid idea and will likely be explored someday on a per-need basis. For now I am closing this specific issue as solved.

**Closed by ocornut** 2021-11-04 13:21 UTC
Labels: in progress, drag drop, clipper
