### ISSUE TITLE
SetColumnWidth(-1, ...) makes other columns non-resizeable

### ISSUE THREAD

**Issue by GreyDodger** [ocornut/imgui#1655] opened 2018-03-02 17:45 UTC
version 1.60

using SetColumnWidth(-1, ...) makes other columns non-resizeable

you can test this by modifying imgui_demo.cpp line 1626 and add ImGui::SetColumnWidth(-1,10); and you can't resize any of the columns, not just the one you're setting the width to

```cpp
            ImGui::Text("With border:");
            ImGui::Columns(4, "mycolumns"); // 4-ways, with border
            ImGui::Separator();
// inserted code here ->
			ImGui::SetColumnWidth(-1,10); ImGui::Text("ID"); ImGui::NextColumn();
            ImGui::Text("Name"); ImGui::NextColumn();
            ImGui::Text("Path"); ImGui::NextColumn();
            ImGui::Text("Hovered"); ImGui::NextColumn();
            ImGui::Separator();
            const char* names[3] = { "One", "Two", "Three" };
            const char* paths[3] = { "/path/one", "/path/two", "/path/three" };
            static int selected = -1;
            for (int i = 0; i < 3; i++)
            {
                char label[32];
                sprintf(label, "%04d", i);
                if (ImGui::Selectable(label, selected == i, ImGuiSelectableFlags_SpanAllColumns))
                    selected = i;
                bool hovered = ImGui::IsItemHovered();
                ImGui::NextColumn();
                ImGui::Text(names[i]); ImGui::NextColumn();
                ImGui::Text(paths[i]); ImGui::NextColumn();
                ImGui::Text("%d", hovered); ImGui::NextColumn();
            }

```

**Comment by ocornut** [comment] 2018-03-02 17:54
I confirmed the bug. Columns are currently a bit of an issue and I don't know when I'll be able to fix them.

The work-around I suggest for now would be to not call `SetColumnWidth()` every frame but only once.

**Comment by GreyDodger** [comment] 2018-03-02 17:58
Thanks for the quick reply!

**Comment by SSBMTonberry** [comment] 2018-10-07 19:02
Just found this post because I'm having the same problem. Any chance this will get fixed anytime soon, or is there a smart way to make this work? I want to make my first column a fixed size, and the rest resizable.

**Comment by r-lyeh** [comment] 2018-10-16 15:38
I also wanted to keep an initial size for the first column (but still resizeable), then second column would fit 100% of remaining space.

Got it to work in my use case for now with following snippet.
Is there any better way?

```c++
ImGui::Columns(2);

    static float initial_spacing = 100.f; if( initial_spacing ) ImGui::SetColumnWidth(0, initial_spacing), initial_spacing = 0;
    ImGui::Text("description");

ImGui::NextColumn();

    ImGui::PushItemWidth(-1);
    ImGui::Text("your widget here");
    ImGui::PopItemWidth();

ImGui::Columns(1);
```

![image](https://user-images.githubusercontent.com/35402248/47028424-ada76480-d169-11e8-8a13-9f6a66bdd478.png)

**Comment by Vyraax** [comment] 2019-05-03 17:25
Hi everyone!

@r-lyeh I had the same issue but your solution didn't worked for me. I found another "trick" based on your initial one, to force it on the initial frame, or more precisely on the second frame (I don't know why..).

`
static unsigned short initial_column_spacing = 0;

if (initial_column_spacing < 2) 
{
    ImGui::SetColumnWidth(0, 70.0f);
    initial_column_spacing++;
}
`

As you can see, i had to set the column width two frames in a row to be taken into account by ImGui.

Hope this can helps,

**Comment by ocornut** [comment] 2022-01-04 18:23
Closing as as Columns API is now a legacy thing and Tables handle that properly AFAIK. :)

**Closed by ocornut** 2022-01-04 18:23 UTC
Labels: bug, tables/columns
