### ISSUE TITLE
Bug in ImGui::GetViewportPlatformMonitor(ImGuiViewport* viewport_p)

### ISSUE THREAD

**Issue by ldsPatrick** [ocornut/imgui#3967] opened 2021-03-24 23:45 UTC
**Version/Branch of Dear ImGui:**

Version: 1.83
Branch: docking

Code crashes with out-of-bound access of the dynamic array or monitors:

    if (monitor_idx >= 0 || monitor_idx < g.PlatformIO.Monitors.Size)
        return &g.PlatformIO.Monitors[monitor_idx];

The condition should be '&&' not '||'.

**Comment by Thraden** [comment] 2021-03-25 10:29
Fixing this bug doesn't address the core issue, which is that monitor_idx is out of bounds of that array.

The way it happened for me is that I was working with ImGui on the master branch and then switched to docking. This resulted in the monitor_idx being out of bounds. The only thing that helped was deleting the imgui.ini file manually.

Could it be possible to implement versioning of imgui settings files in the library?

**Comment by ocornut** [comment] 2021-03-25 16:14
Thanks, thats a big oops indeed!
Caused by 4b9bc4902084a4a7171d6d4339717c9ecb121ccf, fixed now. Thank you.

> Could it be possible to implement versioning of imgui settings files in the library?

You are discussing a [XY Problem](https://xyproblem.info/) here.
I don't think the problem is specific to a branch transition, and there are valid paths in the viewport systems were monitor index isn't yet known (see the code _before_ 4b9bc4902084a4a7171d6d4339717c9ecb121ccf).

**Closed by ocornut** 2021-03-25 16:14 UTC
Labels: multi-viewports
