### ISSUE TITLE
Create custom font without using the BuildAtlas code path

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#1948] opened 2018-07-15 22:24 UTC
Hello,

i have font datas, like a texture atlas, and the rect of each glyph, and font infos like xadvance

i there a easy way to create an empty ImFont, and after add glyph infos for each char's ?

i have search in the source code on imgui, but its difficult to understand how it work, i know that ImConfig contain the general infos of the font, but it contain also a ttf buffer, and if i not pass this buffer, there is a assert ..

in my case i not have the ttf infos, but i have all the final infos of each glyphs. 

Maybe we can have a ImFontAtlas::AddEmptyFont(const ImFontConfig* font_cfg)
And affter that specify texture atlas to use, and add the glyphs to the font

I dont know how i can achieve this, but maybe you have some ideas i can try ?

i have tried, this for the custom font : 

```cpp

ImFont *font = m_TestFontAtlas.AddFont(&m_TestFontConfig);
if (font)
{
	font->FontSize = 30.0f;
	font->ConfigData = &m_TestFontConfig;
	font->ConfigDataCount = 1;
	m_TestFontAtlas.TexID = (ImTextureID)GenerationThread::Params->textureFont;
		
	font->ContainerAtlas = &m_TestFontAtlas;
		
	for (auto it = GenerationThread::Params->Glyphs.begin(); it != GenerationThread::Params->Glyphs.end(); ++it)
	{
		auto c = it->first;
		GlyphStruct *g = &(it->second);
		font->AddGlyph((ImWchar)c,
			g->rect.x, g->rect.y,
			g->rect.x + g->rect.z, g->rect.y + g->rect.w,
			g->rc.x, g->rc.y,
			g->rc.z, g->rc.w,
			g->advx);
	}

	font->BuildLookupTable();
}
```

after that i push the font, but in my InputTextMultiline, i see weird things :unamused:

when i type chars, they are displayed in wrong order..

![2018-07-16_01-31-31](https://user-images.githubusercontent.com/1434736/42739466-0f9336da-8898-11e8-890e-d71e3d63c4d0.gif)

Thanks

**Comment by ocornut** [comment] 2018-07-16 09:30
You can use `ShowStyleEditor()` to browse and debug the fonts and individual glyphs, hopefully it can help to understand what's wrong with the code.

**Comment by ocornut** [comment] 2018-07-16 09:32
I think your X0/Y0/X1/Y1 position are wrong, they are the offset for each character.

So maybe for a start change
```
		font->AddGlyph((ImWchar)c,
			g->rect.x, g->rect.y,
			g->rect.x + g->rect.z, g->rect.y + g->rect.w,
			g->rc.x, g->rc.y,
			g->rc.z, g->rc.w,
			g->advx);
```
to
```
		font->AddGlyph((ImWchar)c,
			0, 0,
			g->rect.z, g->rect.w,
			g->rc.x, g->rc.y,
			g->rc.z, g->rc.w,
			g->advx);
```
But your `GlyphStruct` may have another offset to take account of.

**Comment by aiekick** [comment] 2018-07-16 21:53
thanks. yep i not really understood weel what corners was :) i though it was pos + size, but no its a rect :)

so i done that finally : 

```cpp

m_TestFontAtlas.TexID = (ImTextureID)FontGenerator::Instance()->
        m_Font_RenderPack->GetTextureId(m_CurrentAttachmentId);
		
m_TestFont->ContainerAtlas = &m_TestFontAtlas;
		
int pdx = GenerationThread::Params->glyphPadding.x;

int lh = (GenerationThread::Params->lineHeight) * GenerationThread::Params->scale;
int bh = (GenerationThread::Params->baseHeight) * GenerationThread::Params->scale;

m_TestFont->Ascent = bh;
m_TestFont->Descent = bh - lh;

for (auto it = GenerationThread::Params->Glyphs.begin(); it != GenerationThread::Params->Glyphs.end(); ++it)
{
	auto c = it->first;
	GlyphStruct *glyph = &(it->second);

	int sx = glyph->size.x * GenerationThread::Params->scale;
	int sy = glyph->size.y * GenerationThread::Params->scale;

	int hbx = glyph->horiBearing.x * GenerationThread::Params->scale;
	int hby = glyph->horiBearing.y * GenerationThread::Params->scale;

	int advx = (glyph->advx) * GenerationThread::Params->scale + pdx;

	m_TestFont->AddGlyph((ImWchar)c,
		hbx, bh - hby,
		hbx + sx, bh - hby + sy,
		glyph->rc.x, glyph->rc.y,
		glyph->rc.z, glyph->rc.w,
		advx);
}
```

and i obtain that ! :satisfied:

![2018-07-16_23-50-47](https://user-images.githubusercontent.com/1434736/42785524-20c55a6c-8953-11e8-9b98-3b1ce57235f9.gif)

**Comment by meshula** [comment] 2018-07-16 22:21
That tool looks great :)

**Comment by aiekick** [comment] 2018-07-16 22:36
i will be released soon under MIT license but closed source :) you can follow me on twitter for have news :)

**Comment by ocornut** [comment] 2018-07-17 07:44
Good to hear the problem is solved! I will add a comment to AddGlyph() to clarify the parameters.
Closing this.

**Closed by ocornut** 2018-07-17 07:44 UTC
Labels: font/text

**Comment by aiekick** [comment] 2018-07-17 17:58
but when i wathc the font in the style editor i not have a good font map ..

![sdfontdesigner_msvc_release_2018-07-17_19-56-10](https://user-images.githubusercontent.com/1434736/42836559-ad40d8ec-89fb-11e8-8087-75e1cf7a0681.png)

do you know where search the problem ?

**Comment by aiekick** [comment] 2018-07-17 18:52
ok in understand. 

In more if i decide to use my custom font bitmap, all frames are disapearing, i dont know why all items except font are impacted : it is what you say about the lines ?

![2018-07-17_20-48-45](https://user-images.githubusercontent.com/1434736/42839197-395ad664-8a03-11e8-82ca-0fa90269e6be.gif)

**Comment by Hoek67** [comment] 2021-03-30 05:25
This sort of thing is also on my todo list as have a lot of custom fonts that have already been rasterized and packed onto a single texture. Will have a good look at it in the next day or 2 and hopefully add some constructive feedback.
