### ISSUE TITLE
Rendering artifacts with OpenGL backend

### ISSUE THREAD

**Issue by FunhuninjaStudio** [ocornut/imgui#5246] opened 2022-04-26 20:13 UTC
# IMGUI DOCKING AND DOCKSPACES BUG

## Problem
ImGui Docking and Dockspaces are not working properly. (with glfw, opengl3)

Whenever I turn on Dockspaces everything starts to get buggy. If I try to dock something it will get distorted and the only
way of fixing it is to close the application. I tried the DX11 example and it seems like there aren't any problem there.
Thank you!
### Screenshots
![image](https://user-images.githubusercontent.com/51212450/165382589-db77ae56-4a83-4eba-8d50-b30c406e2664.png)

**Comment by ocornut** [comment] 2022-04-26 20:30
Are you 100% it is due to dockspace and not multi-viewports ? Try to disable multi-viewports in the configuration panel.

**Comment by FunhuninjaStudio** [comment] 2022-04-27 06:54
When I disabled multi-viewports there weren't any problems. 
Is there a way to fix this without disabling multi-viewports? (I'm using the example)

Thank you

**Comment by ocornut** [comment] 2022-04-27 06:59
This is a duplicate of #4832
we should unfortunately revert that change done in the backend I suppose.

**Closed by ocornut** 2022-04-27 06:59 UTC
Labels: backend/binding, opengl, multi-viewports
