### ISSUE TITLE
ImGui::InputText() buf_size off by one?

### ISSUE THREAD

**Issue by Roflraging** [ocornut/imgui#132] opened 2015-02-13 05:46 UTC
I was trying to set up some text input boxes on very specifically sized character buffers and noticed that the buffers don't seem to be accepting as many bytes as I would expect:

![screenshot-imgui opengl2 example-6](https://cloud.githubusercontent.com/assets/3121968/6182834/2b57b874-b311-11e4-800e-ca413e46798a.png)

Am I just misunderstanding what the buffer size means with ImGui::InputText()?

```
        static char oneByte[1] = {};
        static char twoBytes[2] = {};
        static char threeBytes[3] = {};
        static char fourBytes[4] = {};
        static char tenBytes[10] = {};
        static char elevenBytes[11] = {};

        ImGui::Begin("InputText buffer size");

        ImGui::InputText("one byte", oneByte, sizeof(oneByte));
        ImGui::InputText("two bytes", twoBytes, sizeof(twoBytes));
        ImGui::InputText("three bytes", threeBytes, sizeof(threeBytes));
        ImGui::InputText("four bytes", fourBytes, sizeof(fourBytes));
        ImGui::InputText("ten bytes", tenBytes, sizeof(tenBytes));
        ImGui::InputText("eleven bytes", elevenBytes, sizeof(elevenBytes));

        ImGui::End();
```

**Comment by ocornut** [comment] 2015-02-13 09:36
I think the issue is in imgui.cpp STB_TEXTEDIT_INSERTCHARS()

if ((size_t)new_text_len + text_len + 1 >= obj->BufSize)

The >= should be >

I'll test further when my internet connection comes back.

**Comment by ocornut** [comment] 2015-02-13 11:34
Fixed now.

**Closed by ocornut** 2015-02-13 11:34 UTC

**Comment by Roflraging** [comment] 2015-02-13 18:05
Thanks Omar!
