### ISSUE TITLE
Widgets returning true only when they change value?

### ISSUE THREAD

**Issue by ongamex** [ocornut/imgui#956] opened 2016-12-29 11:03 UTC
I'm trying to implement a simple Undo/Redo for my level editor.
I use ImGui::DragFloat (and others..) to manipulate the values that I need to have history.
These values are updated when ImGui::DragFloat (and others) returns true.  

The problem that I have is that ImGui::DragFloat returns true even when 'sliding' the widget, I want to get notified somehow when to user stopped interacting with the ImGui::DragFloat (for example edited with the keyboard and hit enter, or the user released the mouse) in order to create an undoable state only then.

is there a way to achieve this?

**Comment by ocornut** [comment] 2016-12-29 15:20
See https://github.com/ocornut/imgui/issues/820
Those helpers haven't been added to the main branch yet so we can keep this new issue open.

**Comment by ongamex** [comment] 2016-12-29 18:02
Thanks for the quick replay, 

For the hack, it's a pity that it does not work with PushID and thus with DragFloat2/3/4.

**Comment by ocornut** [comment] 2016-12-29 21:03
It's not to do with PushId(), there was a problem with IsItemActive() within group which was fixed so it may just work now.

**Comment by ongamex** [comment] 2016-12-30 00:02
Yeah, the way I solved my problem is using the "hack" from #820 and basically duplicating the code for DragFloatN and tweaking it a little bit.

Here is the code just in case someone else needs it:
https://gist.github.com/ongamex/155c8b64186a4f5f41353dbfccbb018e

**Comment by ocornut** [comment] 2017-01-02 10:33
So the problem is that the proposed solution for `IsItemActiveLastFrame` doesn't work for groups because the way `EndGroup()` makes `IsItemActive()` works is a little dodgy in the first place.
So we can aim at providing an official IsItemActiveLastFrame (even as an internal) function that works for groups (I don't know how to implement it yet but will find a solution) and expose `IsItemJustReleased()` publicly.

**Comment by eliasdaler** [comment] 2017-05-22 21:09
Is there any progress in this? I think that it's a pretty important feature to have, seeing how many GUIs use this behavior as "PropertyChanged" event.

**Comment by ocornut** [comment] 2017-05-22 21:17
It's not as easy as it sounds because of the architecture of InputText, whicb needs to be cleaned up. No progress on it yet.

**Comment by eliasdaler** [comment] 2017-05-22 21:26
Okay, maybe anything I could help with? Or maybe changes are going to be pretty radical?

**Comment by ocornut** [comment] 2018-06-12 22:19
@ongamex @eliasdaler 
We now have a better solution for this issue that handle groups and multi-elements widget.
See there:
https://github.com/ocornut/imgui/issues/1875#issuecomment-396752570
(Closing this topic, please report/discuss in #1875 onward! Thanks!)

**Closed by ocornut** 2018-06-12 22:19 UTC
