### ISSUE TITLE
Very serious problem high CPU usage！

### ISSUE THREAD

**Issue by sxzxs** [ocornut/imgui#6308] opened 2023-04-06 15:40 UTC
**Version/Branch of Dear ImGui:**

Version: 1.89
Branch: viewport/docking

**win32 dx11 win10**

Back-ends: win32 dx11
Compiler: vs2022
Operating System: win10

**My Issue/Question:**

When its win32 dx11 binding process, minimize the interface, the utilization rate of CPU occupancy rate rise immediately to 50

**Screenshots/Video**
![minisize](https://user-images.githubusercontent.com/26515268/230429231-ae868294-3deb-4257-abbc-dfe3d130d076.png)
![No nimisize](https://user-images.githubusercontent.com/26515268/230429105-f948c514-8652-4c97-9f17-445693f14235.png)

**Comment by ocornut** [comment] 2023-04-06 16:13
We don't have an Idle process in place for minimization in our examples, and likely the app is running at maximum possible framerate since the `Present()` call doesn't wait for vsync.

Your application code can decide to pause when Minimized.

**Comment by ocornut** [comment] 2023-04-06 16:15
Closing as duplicate of #2496 
Aside from a more generic Idle scheme I suppose we could rework some of our example apps to simply stop when minimized.

**Closed by ocornut** 2023-04-06 16:15 UTC
Labels: backends

**Comment by sxzxs** [comment] 2023-04-06 16:16
On the issue, I have found this problem, I'm sorry before without browsing
1、https://github.com/ocornut/imgui/pull/3907
2、
```
	if (ImGui::GetIO().Framerate > 61.f) 
        {
		std::this_thread::sleep_for(std::chrono::milliseconds(200)); // drop to 5 FPS when invisible
	}

```

**Comment by ocornut** [comment] 2023-04-06 16:17
The solution in #3907 is more correct than checking for `Framerate > 61.f`

**Comment by ocornut** [comment] 2024-05-23 13:21
I have pushed https://github.com/ocornut/imgui/commit/ec1d2be96f30f9dbe52fc9d5d6b8c4c5eb5021f9 which seemingly solves it for both cases of minimization and screen locking. Implemented this for the DX9, DX10, DX11 and DX12 examples. Both DX9 and DX12 weren't burning as much CPU when looping with no visible swap chain, as Present() would still honor vsync, but it's still best to not loop when locked.

Note this issue for multi-viewports https://github.com/ocornut/imgui/issues/7615#issuecomment-2126973514

**Comment by damian-kos** [comment] 2024-10-21 21:29
I've noticed that when I statically link my builds against OpenGL 2 and OpenGL 3, the CPU usage in Task Manager can reach around 20%. In contrast, dynamically linking results in significantly lower CPU usage, typically between 1% and 3%.

Removing ImGui's code brings it back to normal values.

What could be causing this difference in CPU usage between static and dynamic linking?

**Comment by ocornut** [comment] 2024-10-22 07:11
What does statically linking against OpenGL 2 and OpenGL 3 means?

**Comment by damian-kos** [comment] 2024-10-22 08:17
Sorry my lack of experience showing up. So what I probably should've said is when I link against static libraries of SDL or GLFW. When I setup a new project I am using demos from the examples with SDL and GLFW installed with vcpkg without static command and they work what I assume fine.

Problem I mentioned is when I setup my project in VS with vcpkg using its manifest file with with 'Use Static Libraries' to Yes. The the issue occurs. 

Doesn't happen on win32 - dx versions only on sdl/glfw - opengl
