### ISSUE TITLE
Synchronized table resize border doesn't register mouse input when height are differents

### ISSUE THREAD

**Issue by SenseiHaketon** [ocornut/imgui#3955] opened 2021-03-21 14:28 UTC
**Version/Branch of Dear ImGui:**

Version: 1.83 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: Win10

**My Issue:**

When creating two or more Tables with the same ID (so the column width is synced) and TreeNodes as content,
the line where you resize the columns doesn't register mouse input correctly when TreeNodes are expanded only in one of the tables.

Is this intended? If so, how can I sync the column width without sharing the ID?

**Screenshots/Video**

![Screenshot 2021-03-21 152447](https://user-images.githubusercontent.com/20400957/111908498-cb273980-8a59-11eb-9db4-470f8b003e3e.jpg)

**Sample Code**
`

        ImGui::Begin("Test1");
        for (int j = 0; j < 2; j++)
        {
            ImGui::Separator();
            static ImGuiTableFlags flags = ImGuiTableFlags_Resizable | ImGuiTableFlags_NoSavedSettings | ImGuiTableFlags_RowBg;
            float minRowHeight = 30.0f;
            if (ImGui::BeginTable("table_test", 2, flags))
            {
                ImGui::TableSetupColumn("Name", ImGuiTableColumnFlags_NoHide | ImGuiTableColumnFlags_WidthStretch, 0.5f);
                ImGui::TableSetupColumn("Value", ImGuiTableColumnFlags_NoHide | ImGuiTableColumnFlags_WidthStretch, 0.5f);
                for (int i = 0; i < 5; i++)
                {
                    ImGui::TableNextRow(0, minRowHeight);
                    ImGui::TableSetColumnIndex(0);
                    std::string propName = "Hello " + std::to_string(i);

                    if (ImGui::TreeNodeEx(propName.c_str(), ImGuiTreeNodeFlags_SpanFullWidth, propName.c_str()))
                    {
                        for (int h = 0; h < 5; h++)
                        {
                            ImGui::TableNextRow(0, minRowHeight);
                            ImGui::TableSetColumnIndex(0);
                            ImGui::Text("\t\tChild");
                            ImGui::TableSetColumnIndex(1);
                            ImGui::Text("ChildValue");
                        }

                        ImGui::TreePop();
                    }
                }
                ImGui::EndTable();
            }
        }

        ImGui::End();`

**Comment by ocornut** [comment] 2021-03-22 14:36
As requested by the issue template, an actual minimal repro would be helpful here. 
I'm not entirely sure the problem is precisely the one you stated and only a repro can express the issue accurately.

**Comment by SenseiHaketon** [comment] 2021-03-23 20:42
Right, I'm sorry. I'll add one later.

**Comment by SenseiHaketon** [comment] 2021-03-23 23:13
@ocornut I've added sample code for now

**Comment by ocornut** [comment] 2021-03-24 13:46
Thanks a lot! I could confirm there is a bug with synchronized tables. This was puzzling at first, and then I realized it had nothing to do with TreeNode or actual contents, but is caused by the fact the tables have different height. We are store a "last table height" and this gets overwritten by each tables using the same ID of a synchronized set. 

Coincidentally this was mentioned a few days ago there:
https://github.com/ocornut/imgui/issues/3565#issuecomment-801069294

Will investigate a fix for it!

**Comment by ocornut** [comment] 2022-03-01 17:47
Managed to fix this issue today (fix is 0f14933). Closing, thanks for reporting!

**Closed by ocornut** 2022-03-01 17:47 UTC
Labels: bug, tables/columns

**Comment by SenseiHaketon** [comment] 2022-03-01 17:59
Thanks a lot! You're a legend :)
