### ISSUE TITLE
SWITCH PAGE ? WHY?

### ISSUE THREAD

**Issue by mDenis16** [ocornut/imgui#1221] opened 2017-07-09 11:17 UTC
if (ImGui::Begin("         TEST             ", &Vars.Menu.Opened, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoScrollbar))
		{
			const char* tabs[] = {
				"Home",
				"Inventory",
				"Bank",
				"Teleport",
				"Misc",
			};
			int tabs_size = sizeof(tabs) / sizeof(tabs[0]);

			for (int i = 0; i < tabs_size; i++)
			{
				ImVec2 windowSize = ImGui::GetWindowSize();
				int width = windowSize.x / tabs_size - 9;

				int distance;
				if (i == page)
					distance = 0;
				else
					distance = i > page ? i - page : page - i;

				ImGui::GetStyle().Colors[ImGuiCol_Button] = ImVec4(0.10f, 0.09f, 0.12f, 1.00f);

				if (ImGui::Button(tabs[i], ImVec2(width, 0)))
					page = i;

				ImGui::GetStyle().Colors[ImGuiCol_Button] = ImVec4(0.10f, 0.09f, 0.12f, 1.00f);

				if (i < tabs_size - 1)
					ImGui::SameLine();
			}

			ImGui::Separator();
///HERE IS THE PROBLEM
                  switch (page)    //.identifier "page" is undefined
			{
			case 0:
				RageBot();
				break;
			case 1:
				test1();
				break;
			case 2:
				test2();
				break;
			case 3:
				test3();
				break;
			case 4:
				test4();
				break;
			}

			ImGui::End();
		}

**Comment by ocornut** [comment] 2017-07-09 11:25
Duplicate of #1210. Please talk there and try using fully formed sentences. Thank you!

**Closed by ocornut** 2017-07-09 11:25 UTC
