### ISSUE TITLE
ColorEdit/Picker: bug on drag and drop and text input due to HSV-wrapping code

### ISSUE THREAD

**Issue by BloodSharp** [ocornut/imgui#2050] opened 2018-08-29 02:37 UTC
**Version/Branch of Dear ImGui:**

Tested on 1.53 WIP (branch 2017 drag&drop latest closed) and 1.62 (in release download section)

Back-ends: 1.53 WIP (my own custom winapi+opengl 3) / 1.62 (SDL2+GL3 standard no modifications)
OS: Linux Mint Tara x64 / Windows 7 Ultimate SP1
Compiler: GCC / MingW (from codeblocks installer)

**My Issue/Question:** There is a bug in drag and drop if someone uses only black and white color buttons, if the color button is black the RGB will be divided by 2 each time used, in white color cases I have no idea how the color is changing...
Any help to make a temporally fix will be also appreciated...

**Standalone, minimal, complete and verifiable example:**

```
static ImColor testingcolor=ImColor(255,128,0,255);
ImGui::SetNextWindowSize(ImVec2(250,250),ImGuiCond_Once);
ImGui::SetNextWindowPosCenter(ImGuiCond_Once);
if(ImGui::Begin("Testing Colors"))
{
   ImGui::BeginGroup();
   ImGui::ColorButton("Orange",ImColor(255,128,0,255),0,ImVec2(20,0));
   ImGui::ColorButton("Red",ImColor(255,0,0,255),0,ImVec2(20,0));
   ImGui::ColorButton("Green",ImColor(0,255,0,255),0,ImVec2(20,0));
   ImGui::ColorButton("Blue",ImColor(0,0,255,255),0,ImVec2(20,0));
   ImGui::ColorButton("Black",ImColor(0,0,0,255),0,ImVec2(20,0));
   ImGui::ColorButton("White",ImColor(255,255,255,255),0,ImVec2(20,0));
   ImGui::EndGroup();
   ImGui::SameLine();
   ImGui::PushItemWidth(200);
   ImGui::ColorPicker4("##COLOR_PICKER_TEST",(float*)&testingcolor,
            ImGuiColorEditFlags_RGB|ImGuiColorEditFlags_AlphaBar|ImGuiColorEditFlags_NoSidePreview);
   ImGui::PopItemWidth();
   ImGui::End();
}
```

**Screenshots/Video**

![imguicolorbuttonandpicker](https://user-images.githubusercontent.com/19619356/44761672-6530da80-ab1a-11e8-932a-11bb4efb9dcc.gif)

B#

**Comment by ocornut** [comment] 2018-08-29 10:11
Nice find! This has been in since the initial implementation in #346.
The problem lies in the code which does:

`// Try to cancel hue wrap (after ColorEdit), if any`

This code is useful in other situations. With:
![huv_wrap_code_enabled](https://user-images.githubusercontent.com/8225057/44781283-4109e380-ab84-11e8-977c-ece5b32fde37.gif)

without:
![huv_wrap_code_disabled](https://user-images.githubusercontent.com/8225057/44781290-45360100-ab84-11e8-809d-553f09b96a06.gif)

Another way to reproduce a similar bug is to have a RGB(0,0,255) value and just input 0 into the B box:

![input_0_into_b](https://user-images.githubusercontent.com/8225057/44781261-34858b00-ab84-11e8-85b8-9365b6e62a9a.gif)

So my guess is that we could avoid running the hue wrap fix up when inputting/dropping an absolute value, but keep it when dragging. I don't actually properly grok that HSV logic so I may be wrong.

**Comment by ocornut** [comment] 2018-08-29 11:31
I have now pushed a fix for this. I am not entirely satisfied but it'll probably be enough for now.

**Closed by ocornut** 2018-08-29 11:31 UTC
Labels: bug, drag drop
