### ISSUE TITLE
A strange problem about Chinese character display.

### ISSUE THREAD

**Issue by BDZNH** [ocornut/imgui#2070] opened 2018-09-09 07:52 UTC
Hello, I got a problem when I use Chinese in my application with imgui.

when I use "ImFont* font = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\msyh.ttc", 18.0f, NULL, io.Fonts->GetGlyphRanges`ChineseSimplifiedCommon());`"
the problem look like this
![problem](https://user-images.githubusercontent.com/17548735/45262319-46e6ab00-b447-11e8-9c12-54178d4cb03c.JPG)

the chinese character "浏" is changed to "?".

and when I use "ImFont* font = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\msyh.ttc", 18.0f, NULL, io.Fonts->GetGlyphRanges`ChineseFull());`"
It work well. It should look like this
![default](https://user-images.githubusercontent.com/17548735/45262304-26b6ec00-b447-11e8-994e-41699e7edf0f.JPG)

### But it will use over 200MB memory.

and the character "浏" is a Simplified Chinese character.

-----

os: windows 10 1803(17134.228)
ide: visual studio 15.8.3
imgui version: 1.65

-----

sorry for my poor English.

**Comment by ocornut** [comment] 2018-09-09 18:56
You should use the GlyphRangeBuilder to combine existing range + the extra glyphs you need.

Also reduce oversampling when loading large ranges. This is well documented in the fonts/ readme file.

**Comment by ocornut** [comment] 2018-09-09 18:58
I'm closing this now. It is written when creating an issue than Font Loading questions should be asked on the Discourse forum:
https://discourse.dearimgui.org/

**Closed by ocornut** 2018-09-09 18:58 UTC
Labels: font/text

**Comment by sgf** [comment] 2018-09-09 19:45
@BDZNH try freetype ? even thats still has some problem

**Comment by sgf** [comment] 2018-09-11 16:09
im have tried freetype,just same,because the problem is same, ye the function AddFontFromFileTTF

**Comment by BDZNH** [comment] 2018-09-23 00:54
@ice1000  我试一下
@ocornut  Thanks a lot, I'll try.
