### ISSUE TITLE
Feature request: Smooth rendering

### ISSUE THREAD

**Issue by raegnar** [ocornut/imgui#152] opened 2015-03-05 17:53 UTC
Is it possible to get optional support for smooth rendering of widgets like that in the [memononen](https://github.com/memononen/imgui) fork?

**Comment by ocornut** [comment] 2015-03-05 18:24
Yes will do eventually, but probably not a top priority.
Duplicate of #133

**Comment by ocornut** [comment] 2015-03-06 21:41
Closed as duplicate. Will do !

**Closed by ocornut** 2015-03-06 21:41 UTC
Labels: duplicate, enhancement

**Comment by ocornut** [comment] 2015-03-06 23:42
I have merged and moved Mikko changes into a new branch until they are sorted out
https://github.com/ocornut/imgui/tree/2015-03-antialiased-primitives

Please follow #133 for future updates.
