### ISSUE TITLE
BeginMenu with columns

### ISSUE THREAD

**Issue by q-depot** [ocornut/imgui#1149] opened 2017-05-19 12:31 UTC
Hi,

The columns don't seem to be working inside a menu, I reckon there is an issue with the resize so the content is clipped, If I use the border when I drag the handle it jumps.

```
if( ui::BeginMenu( "Endpoints" ) )
{
    if (ImGui::BeginMenu("New Endpoint"))
    {
        ImGui::Text( "Create Endpoint" );
        ImGui::Button("create");
        ImGui::EndMenu();
    }
	ImGui::Columns(4, "endpoints-view", false);
	ImGui::Separator();

	ImGui::Text( "Protocol" );	ImGui::NextColumn();
	ImGui::Text( "Name" );		ImGui::NextColumn();
	ImGui::Text( "Ip" );		ImGui::NextColumn();
	ImGui::Text( "Port" );		ImGui::NextColumn();

	ImGui::Separator();

	for( auto &ep : NodeEndpoint::getAll() )
	{
		ImGui::Text( ep->getProtocol().c_str() );								ImGui::NextColumn();
		ImGui::Text( ep->getName().c_str() );									ImGui::NextColumn();
		ImGui::Text( ep->getIp().c_str() );										ImGui::NextColumn();
		ImGui::Text( ep->isOsc() ? to_string(ep->getPort()).c_str() : " " );	ImGui::NextColumn();
	}

	ImGui::Columns(1);

    ui::EndMenu();
}
```

**Comment by ocornut** [comment] 2017-05-19 15:14
Thanks. I won't have to time to look at it right away, Columns are notoriously in need for a rewrite for many different reasons.

Not, I'm not sure exactly _which bug_ you are referring too, with your repro
```
        ImGui::Begin("Bug #1149");
        if( ImGui::BeginMenu( "Endpoints" ) )
        {
            if (ImGui::BeginMenu("New Endpoint"))
            {
                ImGui::Text( "Create Endpoint" );
                ImGui::Button("create");
                ImGui::EndMenu();
            }
            ImGui::Columns(4, "endpoints-view", false);
            ImGui::Separator();

            ImGui::Text( "Protocol" );	ImGui::NextColumn();
            ImGui::Text( "Name" );		ImGui::NextColumn();
            ImGui::Text( "Ip" );		ImGui::NextColumn();
            ImGui::Text( "Port" );		ImGui::NextColumn();

            ImGui::Separator();

            for (int n = 0; n < 10; n++)
            {
                ImGui::Text( "blah" ); ImGui::NextColumn();
                ImGui::Text( "this is a name" ); ImGui::NextColumn();
                ImGui::Text( "192.168.255.255" ); ImGui::NextColumn();
                ImGui::Text( "1234" ); ImGui::NextColumn();
            }

            ImGui::Columns(1);
            ImGui::EndMenu();
        }
        ImGui::End();
```

I get:
![image](https://cloud.githubusercontent.com/assets/8225057/26254114/c2aef6d0-3cb5-11e7-8b6b-45e4efe4fce5.png)

Which is visibly clipped, so arguably a bug from user's point of view, but not news as Columns do not have any sizing policy at the moment, so the whole columns set is spreading within available space.

As a ugly workaround to explicitly enlarge the menu you use, e.g.
```
        if( ImGui::BeginMenu( "Endpoints" ) )
        {
            float x = ImGui::GetCursorPosX();
            ImGui::SetCursorPosX(400.0f);
            ImGui::SetCursorPosX(x);
```

As pointed out, adding the columns separator gives odd resizing behavior.

At the moment I would suggest using SameLine() with known X positions to simulate cheap columns (but that would limit your field size). Sorry it's not great :(

**Comment by ocornut** [comment] 2020-12-08 16:26
Closing this as
- essentially duplicate of #1363 (same issue)
- new tables api generally has more features/facilities.

Equivalent test with Tables. 
Note that it requires `ImGuiTableFlags_ColumnsWidthFixed` policy because the `Stretch` policy uses available space.

```cpp
ImGui::Begin("Bug #1149");
if (ImGui::BeginMenu("Endpoints"))
{
    if (ImGui::BeginMenu("New Endpoint"))
    {
        ImGui::Text("Create Endpoint");
        ImGui::Button("create");
        ImGui::EndMenu();
    }

    if (ImGui::BeginTable("endpoints-view", 4, ImGuiTableFlags_ColumnsWidthFixed | ImGuiTableFlags_Borders))
    {
        ImGui::TableNextColumn(); ImGui::TableHeader("Protocol");
        ImGui::TableNextColumn(); ImGui::TableHeader("Name");
        ImGui::TableNextColumn(); ImGui::TableHeader("Ip");
        ImGui::TableNextColumn(); ImGui::TableHeader("Port");
        for (int n = 0; n < 10; n++)
        {
            ImGui::TableNextColumn(); ImGui::Text("blah");
            ImGui::TableNextColumn(); ImGui::Text("this is a name");
            ImGui::TableNextColumn(); ImGui::Text("192.168.255.255");
            ImGui::TableNextColumn(); ImGui::Text("1234");
        }
        ImGui::EndTable();
    }
    ImGui::EndMenu();
}
ImGui::End();
```

![image](https://user-images.githubusercontent.com/8225057/101510622-73693480-397a-11eb-845d-5a2b865df94f.png)

**Closed by ocornut** 2020-12-08 16:27 UTC
Labels: layout, tables/columns
