### ISSUE TITLE
Can't build example on Linux invalid conversion from ‘void (*)()’ to ‘void*’

### ISSUE THREAD

**Issue by anthonybakermpls** [ocornut/imgui#411] opened 2015-11-21 19:18 UTC
Trying to build the SDL opengl 3 example gives the following error:

$c++ `sdl2-config --cflags` -I ../.. -I ../libs/gl3w main.cpp imgui_impl_sdl_gl3.cpp ../../imgui*.cpp ../libs/gl3w/GL/gl3w.c `sdl2-config --libs` -lGL -o sdl2example
../libs/gl3w/GL/gl3w.c: In function ‘void* get_proc(const char*)’:
../libs/gl3w/GL/gl3w.c:85:25: error: invalid conversion from ‘void (*)()’ to ‘void*’ [-fpermissive]
  res = glXGetProcAddress((const GLubyte *) proc);

when i do -fpermissive:

$c++ -fpermissive `sdl2-config --cflags` -I ../.. -I ../libs/gl3w main.cpp imgui_impl_sdl_gl3.cpp ../../imgui*.cpp ../libs/gl3w/GL/gl3w.c `sdl2-config --libs` -lGL -o sdl2example           
../libs/gl3w/GL/gl3w.c: In function ‘void* get_proc(const char*)’:
../libs/gl3w/GL/gl3w.c:85:25: warning: invalid conversion from ‘void (*)()’ to ‘void*’ [-fpermissive]
  res = glXGetProcAddress((const GLubyte *) proc);
                         ^
/usr/bin/ld: /tmp/ccT2hT7y.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Note the sdl_opengl_example/ works fine.

**Comment by anthonybakermpls** [comment] 2015-11-22 15:45
Found the fix:
http://askubuntu.com/questions/334884/while-compiling-truecrypt-i-get-undefined-reference-to-symbol-dlcloseglibc

need -ldl in your build command in the readme for this.

c++ -fpermissive `sdl2-config --cflags` -I ../.. -I ../libs/gl3w main.cpp imgui_impl_sdl_gl3.cpp ../../imgui*.cpp ../libs/gl3w/GL/gl3w.c `sdl2-config --libs` -lGL -ldl -o sdl2example

**Comment by anthonybakermpls** [comment] 2015-11-22 15:48
Sorry I don't use github that much.. I guess I should leave this open with a suggested fix? I don't really even know how to do pull requests.

solution is to add  -ldl  to build command in your readme for this.

**Comment by anthonybakermpls** [comment] 2015-11-22 15:49
So does this mean imgui doesn't support opengl 3 natively or what is going on with these function mappings that cause this problem in the first place?

**Comment by ocornut** [comment] 2015-11-22 15:59
This code has nothing to do with imgui, gl3w is a wrapper to call OpenGL3 functions because modern OpenGL was designed to be tedious to use.

**Comment by ocornut** [comment] 2015-11-22 16:01
How does the makefile for the opengl3 example perform for you?
It also use gl3w.c and I haven't heard of issue with it (but I don't use Linux myself).

**Comment by ocornut** [comment] 2015-11-22 16:05
It looks like the problem is that gl3w.c is C not C++ and that code use function pointer casting feature that is obsoleted in C++ and that file is compiled in C++ with the command-line.

**Comment by ocornut** [comment] 2015-11-22 16:13
Could you remove the permissive flag and try adding a cast to void* on line 85 see if it fixes it?

```
	res = glXGetProcAddress((const GLubyte *) proc);
```
change to
```
	res = (void*)glXGetProcAddress((const GLubyte *) proc);
```
Thanks!

**Comment by anthonybakermpls** [comment] 2015-11-22 17:01
If I put that explicit cast in there, remove -fpermissive and the -ldl switches, it doesn't error or warn on the assignment but it breaks on the dlclose symbol.

c++ `sdl2-config --cflags` -I ../.. -I ../libs/gl3w main.cpp imgui_impl_sdl_gl3.cpp ../../imgui*.cpp ../libs/gl3w/GL/gl3w.c `sdl2-config --libs` -lGL -o sdl2example                         
/usr/bin/ld: /tmp/ccuwMg9O.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by ocornut** [comment] 2015-11-22 17:06
Yeah, -ldl is still required by gl3w on Linux so I added that to the README and will add the cast now. Thanks!

**Comment by anthonybakermpls** [comment] 2015-11-22 17:06
oh, and it looks like -fpermissive is required too with the -ldl. The makefile with the opengl3 example works perfectly I was comparing that before to try and figure out why that worked and this one didn't but I couldn't see anything.

**Comment by anthonybakermpls** [comment] 2015-11-22 17:07
This looks like a really cool library. Thanks for sharing it.

**Comment by ocornut** [comment] 2015-11-22 17:08
Sorry - can you clarify, even with the explicit cast -fpermissive is required? You are still getting the same error/warning with the cast? (I'd rather fix gl3w here than suggest that a flag is required)

**Comment by anthonybakermpls** [comment] 2015-11-22 17:15
Okay, with explicit cast in gl3w.c, -fpermissive is not needed but -ldl is required.

**Comment by ocornut** [comment] 2015-11-22 17:18
Thanks, fixed now. By looking at gl3w it looks like they have actually fixed the code in the recent versions and I'm not up to date there because I just grabbed a pregenerated gl3w.c from somewhere. 

I'd rather not update it right now because every minor changes related to building examples it causing new issues of this kind.

**Closed by ocornut** 2015-11-22 17:18 UTC
