### ISSUE TITLE
Broken line AA

### ISSUE THREAD

**Issue by MrDimarik** [ocornut/imgui#2989] opened 2020-01-17 20:35 UTC
**Version/Branch of Dear ImGui:**
Version: v1.75 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui_impl_dx11.cpp + imgui_impl_win32.cpp
Compiler: Visual Studio 2019 (v142) (SDK: Last 10.0.18362.0)
Operating System: Windows 10 1909 (18363.592)

**My Issue/Question:**
Drawing a triangle looks choppy!
Is there any way to fix this?

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/59513719/72636805-ee93b780-3970-11ea-98d9-402b77b419d6.png)

**Code Sample**
auto DrawList = ImGui::GetOverlayDrawList();
DrawList->AddTriangle({ 0,1080 }, { 960, 0 }, { 1000, 1000 }, -1, 2);

**Comment by ocornut** [comment] 2020-01-20 08:35
Hello,

There's a bug where the thickness of polyline strokes is not consistent accross segments.
See #2183 and proposed solution #2964. 

Workarounds
- Merge #2964 
- For occasional use, with small thickness and full opacity you may temporarily get around by using 3 distinct lines (really not ideal of course)

```cpp
ImDrawList* draw_list = ImGui::GetOverlayDrawList();
draw_list->AddTriangle(ImVec2( 0,1080), ImVec2(960, 0), ImVec2(1000, 1000), IM_COL32(255,255,255,255), 3);
```

Closing as duplicate of issues marked above, we should tackle them fairly shortly as the PR linked above is quite functional.

**Closed by ocornut** 2020-01-20 08:35 UTC
Labels: drawing
