### ISSUE TITLE
[SDL_OPENGL3] : possible regression

### ISSUE THREAD

**Issue by RobertoMalatesta** [ocornut/imgui#2919] opened 2019-12-05 19:11 UTC
**Version/Branch of Dear ImGui:**

Version: 1.75
Branch: master

**Back-end/Renderer/Compiler/OS**

Operating System: Ubuntu Server 18.04

**My Issue/Question:**
Out of the box `example_sdl_opengl3` does not compile anymore.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/11835025/70265528-e6096800-179a-11ea-8993-177037e03e9f.png)

**Comments**
If we already have SDL2, is glew still necessary ??

--R

**Comment by ebachard** [comment] 2019-12-06 06:57
Hello,

Something changed recently, indeed,but the issue is not that big : you can choose an OpenGL loader between gl3w (internal Dear ImGui), glew, and some other, by passing a define at build time. On my side, gl3w is sufficient, and works well. 

Maybe you prefer patch language ?   ;-) 
````
diff --git a/examples/example_sdl_opengl3/Makefile b/examples/example_sdl_opengl3/Makefile
index 9e84df92..0792d16a 100644
--- a/examples/example_sdl_opengl3/Makefile
+++ b/examples/example_sdl_opengl3/Makefile
@@ -22,7 +22,7 @@ OBJS = $(addsuffix .o, $(basename $(notdir $(SOURCES))))
 UNAME_S := $(shell uname -s)
 
 CXXFLAGS = -I../ -I../../
-CXXFLAGS += -g -Wall -Wformat
+CXXFLAGS += -g -Wall -Wformat  -DIMGUI_IMPL_OPENGL_LOADER_GL3W
 LIBS =
 
 ##---------------------------------------------------------------------

````
 
HTH


-- 
qɔᴉɹə

Auteur d'OOoLight et OOo4Kids
L'association EducOOo : http://www.educoo.org (dérivé d'OpenOffice)

https://framagit.org/ericb/miniDart (logiciel Handball)

**Comment by ocornut** [comment] 2019-12-06 09:44
Looks like a regression added by #2798 in case the system paths has access to Glew we have a mismatch between the Makefile linking intent and the auto-detected includes.
Makes #2798 a little less attractive :(
Fixed now!

**Closed by ocornut** 2019-12-06 09:44 UTC
Labels: backend/binding

**Comment by RobertoMalatesta** [comment] 2019-12-06 14:42
Hi @ebachard .


> Maybe you prefer patch language ? ;-)

?? No need of it.

I tend to avoid unneeded dependencies that foster complexity.

An internal custom loader will suffice, be leaner, more portable and under the project control.

Example:

[https://github.com/ApoorvaJ/Papaya/blob/3808e39b0f45d4ca4972621c847586e4060c042a/src/libs/gl_lite.h](https://github.com/ApoorvaJ/Papaya/blob/3808e39b0f45d4ca4972621c847586e4060c042a/src/libs/gl_lite.h)
 

--R
