### ISSUE TITLE
Imgui unresponsive when using multiple viewports (Win32 + Vulkan)

### ISSUE THREAD

**Issue by michaelxmroz** [ocornut/imgui#7377] opened 2024-03-08 09:34 UTC
### Version/Branch of Dear ImGui:

Version 1.90.4, Branch: docking

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_vulkan.cpp

### Compiler, OS:

Windows 11 + MSVC22

### Full config/build information:

```
Dear ImGui 1.90.5 WIP (19044)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1938
define: _MSVC_LANG=201703
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_vulkan
io.ConfigFlags: 0x00000000
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 960.00,864.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

Hi all,

I am trying to get multi viewports to work with the win32+Vulkan combo. This works fine as long as all the UI windows are in the main window, but as soon as I move one of the windows out, the entire UI, both in the main and the new window become unresponsive, i.e. do not react to move, resize, hover, click etc. This also applies to the window controls themselves, so I cannot move or resize the main window, even though that is managed by my own application, as soon as imgui creates a second window.

I'm assuming this is somehow related to window events not being handled properly as the windows mouse pointer sometimes gets stuck in a spinner or resize arrows when this happens. My main application is still running without issues while this happens, and is rendering properly at 60Hz.

On further investigation, the problem only starts occurring when I actually interact (hover/click) on the new window. So I can interact with the main window UI, and open a new window fine, but as soon as I move my mouse over to that other window both windows seem to stop receiving window events such as WM_MOUSEMOVE, WM_MOUSELEAVE, WM_LBUTTONDOWN etc.

I am new to imgui so this problem has me stumped. I would appreciate some help.

The code below is are just some snippets showing my imgui setup.

### Minimal, Complete and Verifiable Example code:

```
//Main window WindowProc
    LRESULT CALLBACK WindowProc(HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
    {
        if (ImGui_ImplWin32_WndProcHandler(hwnd, uMsg, wParam, lParam))
            return true;

        switch (uMsg)
        {
        case WM_CLOSE:
            PostQuitMessage(0);
            return 0;
        }
        return DefWindowProc(hwnd, uMsg, wParam, lParam);
    }

static int ImGui_CreateVkSurface(ImGuiViewport* viewport, ImU64 vk_instance, const void* vk_allocator, ImU64* out_vk_surface)
{
    VkSurfaceKHR surface;
    HWND windowHandle = static_cast<HWND>(viewport->PlatformHandleRaw);
    VkWin32SurfaceCreateInfoKHR surfaceInfo{ VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR };
    HMODULE instanceID = GetModuleHandle(nullptr);
    surfaceInfo.hwnd = windowHandle ;
    surfaceInfo.hinstance = instanceID;

	if (vkCreateWin32SurfaceKHR((VkInstance)vk_instance, &surfaceInfo, nullptr, &surface) != VK_SUCCESS) {
		throw std::runtime_error("failed to create window surface!");
	};
    *out_vk_surface = (ImU64)surface;
    return 0;
}

void Init(RendererVulkan& renderer)
{
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();
    io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;

    
    ImGui::GetPlatformIO().Platform_CreateVkSurface = ImGui_CreateVkSurface;
    
    HWND* windowHandle = static_cast<HWND*>(renderer.GetWindowHandle());
    ImGui_ImplWin32_Init(*windowHandle);

    ImGui_ImplVulkan_InitInfo init_info = {};
    init_info.Instance = renderer.m_instance;
    init_info.PhysicalDevice = renderer.m_physicalDevice;
    init_info.Device = renderer.m_logicalDevice;
    init_info.QueueFamily = renderer.m_graphicsQueueFamilyIndex;
    init_info.Queue = renderer.m_graphicsQueue;
    init_info.PipelineCache = VK_NULL_HANDLE;
    init_info.DescriptorPool = renderer.m_descriptorPool;
    init_info.RenderPass = renderer.m_renderPass;
    init_info.Subpass = 0;
    init_info.MinImageCount = 2;
    init_info.ImageCount = 2;
    init_info.MSAASamples = VK_SAMPLE_COUNT_1_BIT;
    init_info.Allocator = nullptr;
    init_info.CheckVkResultFn = check_vk_result;

    if (!ImGui_ImplVulkan_Init(&init_info))
    {
        LOG_ERROR("Initializing imgui Vulkan back end failed");
    }
}

void Prepare()
{
    ImGui_ImplVulkan_NewFrame();
    ImGui_ImplWin32_NewFrame();
    ImGui::NewFrame();
    bool show = true;
    ImGui::ShowDemoWindow(&show);
}

void Draw(RendererVulkan& renderer)
{
    ImGui::Render();

    ImGui::UpdatePlatformWindows();
    ImGui::RenderPlatformWindowsDefault();

    ImGui_ImplVulkan_RenderDrawData(ImGui::GetDrawData(), renderer.m_commandBuffers[renderer.m_commandBufferIndex]);
}

void Destroy()
{
    ImGui_ImplVulkan_Shutdown();
    ImGui_ImplWin32_Shutdown();
    ImGui::DestroyContext();
}
```

**Comment by ocornut** [comment] 2024-03-08 09:47
Could you first confirm if it happens with the stock unmodified examples (a win32 one and a vulkan one, separately I guess).

This is very likely an issue with your code but given the fact we currently don't have a win32+vulkan example it is not trivial to do a compare. One possible good way to move forward would be if you worked on an actual PR for a win32+vulkan (by combining existing examples, closely following their style) and see if it works. If it works you'll know the issue is in one of your logic change. If it doesn't work we'll both have shared interest to get it fixed and merged as a reference.

**Comment by michaelxmroz** [comment] 2024-03-08 12:03
Yeah, this was definitely an error on my side. My main window was created in a separate UI thread, while imgui was running (and therefore also creating new windows) on the main thread. winapi no likey. Creating the main window on the main thread and processing window events as part of the main loop fixed the issue.

Thank you for taking the time to reply!

**Closed** 2024-03-08 12:44 UTC
Labels: backends, vulkan
