### ISSUE TITLE
Feature Request: Pluggable text rendering

### ISSUE THREAD

**Issue by CallumDev** [ocornut/imgui#3406] opened 2020-08-15 12:10 UTC
Proper text rendering is hard, and current solutions for imgui surrounding CJK text involve rasterizing a lot of glyphs, impacting memory usage and application startup time.

Would it be possible to allow one to override implementations of CalcTextSizeA etc. through function pointers in the ImGuiContext, saving the need to maintain an invasive patchset?

**Comment by ocornut** [comment] 2020-08-15 18:21
Hello,
I'll close this as it seems like duplicate of #3365 which was posted recently. 
Feel free to elaboate in #3365 if you have idea. I personally believe this is not going to work, is going to be more complicated than swapping a few functions pointers, and fancier text rendering engine would need caching to work.

I also agree that the lack of dynamic font atlas is a much desirable feature and we will eventually work on that. Actually as part of the work on shadows we already started working on back-end support for texture update/resizing which will be needed for dynamic atlas.

**Closed by ocornut** 2020-08-15 18:21 UTC
Labels: font/text
