### ISSUE TITLE
ALT GR characters not working under Linux

### ISSUE THREAD

**Issue by RobertoMalatesta** [ocornut/imgui#334] opened 2015-09-15 17:07 UTC
ImGui Version: latest and (some) previous versions.
OS: Kubuntu 2014.04 LTS

Just a quick note to this wonderful tool:

Everything works fine but text input controls do not allow input of "[" "{" and other chars that on int'l keyboards  need ALT GR modifier.

Pressing ALT GR + something produces no char.

My bests,

--R

**Comment by ocornut** [comment] 2015-09-16 09:41
Should be fixed, got broken August 20. Let me know.

Been trying to figure out how to eventually transition to an input model that will allow processing action shortcuts such as "Ctrl+S" or menu selection shortcuts such as holding Alt and pressing letters, so that was part of the tweaks there but probably a mistake.

**Closed by ocornut** 2015-09-16 09:41 UTC

**Comment by RobertoMalatesta** [comment] 2015-09-16 17:18
Tested. OK.
Shortcuts could be a boon for keyboard mouseless navigation, CTRL-Mouse Wheel Zooming and the like.
I'm not too deep in the code now. but you already have implemented keysdown keymods and the like.
Isn't it enough to plug a state on these?


Ciao --R

**Comment by ocornut** [comment] 2015-09-16 17:22
The problem is that not all frameworks on user's side are sending translated characters when modifiers key are held in the first place. GLFW added the option but it's in 3.1 not even in 3.0

**Comment by RobertoMalatesta** [comment] 2015-09-16 17:37
I saw that a couple ago while tinkering on glfw on emscripten.Now I remember.

BTW: compiling for emscripten is a few inches away:

if I remember correctly July ImGUI only complained about glPop/glPushAttrib for opengl2 and SDL2 demos.
opengl3 was more convoluted since got pesky on gl3w and other files.
I did a port of TurboBadger for a quick evaluation in a few hours (modified the loop etc-- http://exedraos.com/everyware/Demo01.html) so I was confident to be able to do it with ImGUI as well but it bonked on my head.
Having an example onto it could be good for mass adoption.

**Comment by ocornut** [comment] 2015-09-16 17:45
There's already a few Emscripten demos that people made
http://www.redblobgames.com/x/1538-imgui-emscripten/em-imgui.html

I'm not really hoping for mass adoption. I would if I had the time or money to keep supporting and working on it, but right now new users basically means more requests/questions and I'm already seriously overwhelmed with my mental todo list constructed from requests. So while I'm hoping to sustain this amount of support and grow the library slowly I can't afford to grow it at a faster pace. Keeping low profile is more sustainable, I prefer to have less and more technically able users :)

**Comment by RobertoMalatesta** [comment] 2015-09-16 18:28
I fully understand you on all the points.
Keep on the good work.

**Comment by ocornut** [comment] 2015-09-16 20:20
Thanks :)
Another issue I'm wary about is that the more user, the harder it is to make breaking change to the API or to the integration layer. I'm still making some of those changes in a controlled way when they are needed! As ImGui improve it will get more stable.

**Comment by RobertoMalatesta** [comment] 2015-09-17 13:16
If it works don't touch it.
20+ years of IT and still that is one of the core principles. That and the KISS principle ImGUI so nicely testifies for :-D

The day I'll have the time I'll pick my emscripten port, fix it and send it to you.
It seems nobody worked on an Android port as well.

One note: ImGUI seems a natural fit for OpenFrameworks, since the ofxUI is not mantained anymore:
http://www.syedrezaali.com/#/ofxui/ (pity, it was very stylish)
There's already a plugin for OF:
https://github.com/brucelane/ofxImGui
so I suppose you should fasten the belt before hitting a crowd of lots of more users.
(What about going VC or -sheesh- crowdsourcing? is Patron enough?)

**Comment by brucelane** [comment] 2015-09-17 13:59
sorry, https://github.com/brucelane/ofxImGui is really not working yet, I intended to do it, but I am busy on other projects right now. I hope to get back to it when I can
And yes Reza Ali's ofxui was great, I used the Cinder port of it called ciUI in the past, I specially like the rotary sliders!

**Comment by ocornut** [comment] 2015-09-17 14:02
There's a working one here:
https://github.com/jvcleave/ofxImGui/

**Comment by ocornut** [comment] 2015-09-17 14:13
> (What about going VC or -sheesh- crowdsourcing? is Patron enough?)

Patreon is nice pocket money and I am very thankful but isn't enough (it's equivalent of half a day of freelancing per month). So I'm basically doing ImGui on my free time when I should be working on my other projects :). I was hoping companies using ImGui would chip in but it's not been happening much. People just don't pay for software. 

You can do rotary sliders in ImGui in a few lines of code. 

There's an empscripten demo in a pull request submitted yesterday.
ImGui was designed to be trivially portable, we don't really need a port to five millions libraries, each of those example is potential extra maintenance as well. We need to keep working on improving the main library :)

**Comment by brucelane** [comment] 2015-09-17 14:35
thank you Omar, great! I deleted my repo and forked
https://github.com/jvcleave/ofxImGui/ so the link is not broken...

**Comment by RobertoMalatesta** [comment] 2015-09-17 16:07
@brucelane: you and @jvcleave are doing a good job of keeping the ball running.
At this time I'm constantly testing and evaluating OpenFrameworks and ImGUI (among a lot of other C/C++ prjs)  but at the moment I don't find a spot where to use these technologies.
It's a pity to see so many GUIs like ofxUI, ofxUI (+tables and widgets additions sparse on the of forum), imGUI, TurboBadger doing the brownian walk and not summing up the efforts.
Maybe when one will emerge as the main one (and I bet on Omar's) other work will be directed toward it improvement.

@ocornut :+1: 
>> I was hoping companies using ImGui would chip in but it's not been happening much. 
>> People just don't pay for software.

Sad, but true. To a certain extent.

Three-neuron IT managers generally cannot open a source code in an editor, let alone understand the sheer potentiality of C/C++ code like yours.

Rotary sliders are indeed simple to do in ImGUI (open a context draw 2 arcs with fill and capture mouse clicks) but not by company permies that would find difficult to create a custom hello world component.

The all look at the VISUAL, so you have to show some wibbly wobbly teletubbly colorful interface with large animated simple icons (that's where joyful rotary sliders come handy, and a pony maybe :-D).

Something that could attract a retarded six-months old baby empowered with the memory of a red fish.
 
They will never pick up a tool that needs knowledge to use it.

Maybe if you offer them some king of visual editor, with all the components already set-up and a wizard that can produce 98% of their code....

**Comment by ocornut** [comment] 2015-09-17 19:41
Now you are rambling. :)
Bottom line is that if I can only spend a few hours a week on imgui I need to be careful about how I invest my time. And I don't want to open the valves too fast before ImGui is a better software because I won't have the bandwidth to handle support for it.
