### ISSUE TITLE
How to use menubar in popupModal?

### ISSUE THREAD

**Issue by cipher1985** [ocornut/imgui#2308] opened 2019-01-24 08:21 UTC
Version/Branch of Dear ImGui:
v1.67
Back-end file/Renderer/OS:
glfw + opengl2 + imgui

My Issue/Question:
How to use menubar in popupModal?

when I use the menubar in PopupModal ,clicking any itemmenu will close the model .
the code like this:

>if (ImGui::BeginPopupModal("testMenu", NULL, ImGuiWindowFlags_MenuBar | 
 ImGuiWindowFlags_AlwaysAutoResize))
{
	if (ImGui::BeginMenuBar())
	{
		if (ImGui::BeginMenu(u8"test1"))
		{
			ImGui::MenuItem("test1_1");
			ImGui::MenuItem("test1_2");
			ImGui::EndMenu();
		}
		ImGui::MenuItem("test2");
		if (ImGui::MenuItem("test3"))
		{
			ImGui::CloseCurrentPopup();
		}
		ImGui::EndMenuBar();
	}
	ImGui::Button("test");
	ImGui::EndPopup();
}

If I want to click the test3 to close the model, the result is that clicking any menu button will close the model.
So how can I use the menubar at popupModal?

**Comment by ocornut** [comment] 2019-01-25 11:07
Hello,

I confirmed the issue, it looks like a bug to me.

**Comment by ocornut** [comment] 2019-01-27 22:54
@cipher1985, this should be fixed now!

**Closed by ocornut** 2019-01-27 22:54 UTC
Labels: bug, menus, popups
