### ISSUE TITLE
Drag and Drop Target Box does not remain within the Window

### ISSUE THREAD

**Issue by Link1J** [ocornut/imgui#3272] opened 2020-05-29 15:10 UTC
**Version/Branch of Dear ImGui:**

Version: 1.76 WIP
Branch: Master and Docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp, imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp, imgui_impl_win32.cpp + imgui_impl_directx11.cpp, Custom
Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**

The yellow boxes for drag and drop targets, do not stay within the window they are from. It does not appear to be affected by any chance to the renderer or backend.

**Screenshots/Video**

![Yellow box breaks window bounds 2](https://user-images.githubusercontent.com/22891267/83275194-d6446c80-a19c-11ea-9f22-faf79b0482ae.PNG)

**Standalone, minimal, complete and verifiable example:** 
The Demo window works to show this.
Make the Demo window have a width of 93, then use the first drag and drop example with the color edits. That is what was done to get the screen shot.

**Comment by markitus18** [comment] 2020-05-31 19:21
I'm pretty sure this is intended behaviour. The system allows the user to drag one item from one window and drop it into another.
In which situation would you not want this behaviour?

**Comment by Link1J** [comment] 2020-05-31 19:29
> I'm pretty sure this is intended behavior. 

Last I checked the window elements stay in window. The **yellow box** does not. Therefor unintended behavior. Note that the **yellow box** draws on the scrollbar, and the background.

**Comment by markitus18** [comment] 2020-05-31 20:04
> Last I checked the window elements stay in window. The **yellow box** does not. Therefor unintended behavior. Note that the **yellow box** draws on the scrollbar, and the background.

Ah, yes, of course... I thought you were referring to the tooltip window. Too many hours of debugging today :) Removing my comment to avoid confusion.

**Comment by rokups** [comment] 2020-06-01 10:24
Turns out that this behavior is enabled on purpose. This is how it looks without explicitly allowing yellow rectangle to go out of bounds:
![image](https://user-images.githubusercontent.com/19151258/83400044-e5c8ed00-a40a-11ea-8130-1adb4f0150e3.png)
I have no idea what correct behavior is in this case. We have to wait for a verdict from @ocornut.

**Comment by ocornut** [comment] 2021-06-30 14:14
Pushed a fix with 4ddb6b46c314045d75b565fc29170e7cb2327eca
This intentional (see initial commit 4b94738c7e64a7a912a72b373063b42a407ec1bd) but I frankly can't remember nor understand why I thought it was a good idea back then...
Same issue as #4281

**Closed by ocornut** 2021-06-30 14:14 UTC
Labels: drag drop

**Comment by ocornut** [comment] 2023-10-05 12:16
I have reworked this with 085ed7b 

Before June 2021
![image](https://github.com/ocornut/imgui/assets/8225057/833e6e15-b0eb-4ce8-a5f6-9deb6245fb04)

June 2021
![image](https://github.com/ocornut/imgui/assets/8225057/ba740552-4a0f-4f85-91ad-5fea9b696735)

October 2023
![image](https://github.com/ocornut/imgui/assets/8225057/6bb5e5ce-68fc-443e-b674-476aa63425f9)
