### ISSUE TITLE
Larger table Clipper Expectation

### ISSUE THREAD

**Issue by vikram-lodhi** [ocornut/imgui#6131] opened 2023-01-31 09:58 UTC
**Version/Branch of Dear ImGui:**
```
Dear ImGui 1.89.2 (18920)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1934
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C06
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,4.00
style.FrameRounding: 3.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

Version: 1.89.2
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: MSVC 143 {Visual Studio 2022} {Dear ImGui installed with vcpkg}
Operating System: Windows 10

**My Issue/Question:**

I am testing ImguiListClipper.

in First screen shot row from 0 to 38 is visible so clipper has executed up to 40. that's fine
but when table row visible from 419 to 438, 
**why clipper is getting executed from 0 to 450 **, there should be a way only clipper execute from lets say 410 to 450
in this way application performance can be improved.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/123872971/215726907-bf1feac3-986d-4fda-92e8-cbb8ef4bca88.png)
![image](https://user-images.githubusercontent.com/123872971/215727194-069774b2-cf5b-41f2-84c4-c7a75d6a6e05.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue

void test_tableClipping() {
    constexpr ImGuiTableFlags flags= ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable | ImGuiTableFlags_ScrollX | ImGuiTableFlags_ScrollY | ImGuiTableFlags_Borders;
    if (ImGui::Begin("Test Table Clipping")) {
        if (ImGui::BeginTable("Test Table", 10, flags)) {
            for (int i = 0; i < 10; ++i) {
                ImGui::TableSetupColumn(std::to_string(i).data());
            }
            ImGui::TableHeadersRow();

            ImGuiListClipper clipper;
            clipper.Begin(1000);
            int start = -9999;
            int end = 0;
            while (clipper.Step()) {
                start = start == -9999 ? clipper.DisplayStart : start;
                end = clipper.DisplayEnd;
                for (int row = clipper.DisplayStart; row < clipper.DisplayEnd; row++) {
                    ImGui::TableNextRow();
                    for (int column = 0; column < 10; column++) {
                        if(ImGui::TableSetColumnIndex(column)) }
                            ImGui::Text("Hello %d,%d", column, row);
                       }
                    }
                }
            }
            printf("%s %d %d\n", __FUNCTION__, start, end);

            ImGui::EndTable();
        }
    }

    ImGui::End();
}
```

**Comment by ocornut** [comment] 2023-01-31 10:27
Your printf() logging code seems buggy I don't understand why you would have this line`start = start == -9999 ? clipper.DisplayStart : start;` and not simply display the original values, which could be the cause of a misunderstanding.

You can use `Demo->Tools->Debug Log->Clipper` to visualize Clipper states.

**Comment by vikram-lodhi** [comment] 2023-01-31 10:53
start = start == -9999 ? clipper.DisplayStart : start;
this line only store the first initializer value or first execution of clipper
its same as
if(start == -9999){start = clipper.DisplayStart;}

Till then lets me understand the code of `Demo->Tools->Debug Log->Clipper`

**Comment by ocornut** [comment] 2023-01-31 11:03
> this line only store the first initializer value or first execution of clipper

Only for the start value.  You are manipulating/changing values that you display for debug only and making assumption based on manipulated values. I think your assumption "why clipper is getting executed from 0 to 450 " is incorrect because your debug display is incorrect.

Clipper will likely request the first item (0..1) to be able to calculate height, then the visible range e.g. (e.g. 418..437), and may include other ranges (e.g. if keyboard focus is somewhere else).

**Comment by ocornut** [comment] 2023-01-31 11:33
Closing this as clearly this is caused by your misleading printf() code, you can verify the behavior in the Debug Log.

**Closed by ocornut** 2023-01-31 11:33 UTC
Labels: clipper

**Comment by vikram-lodhi** [comment] 2023-01-31 11:39
Ok, for other to understand this. 

Clipper is asking for first row: [0-1] to calculate the width
on Next execution of step
it will give viewIndex number [x -> y]{100 -> 150}

Thanks
