### ISSUE TITLE
Tables: Automatic column width becomes zero when the number of columns changes

### ISSUE THREAD

**Issue by ArekSredzki** [ocornut/imgui#4046] opened 2021-04-16 06:32 UTC
**Version/Branch of Dear ImGui:**

Version: 1.82 WIP 732cd837a9ed8ecb2ce4035e7d40a1c9a04ae240
Branch: docking

**Back-end/Renderer/Compiler/OS**

Not relevant

**My Issue/Question:**
One of the tables in my application has a variable number of columns.
Since the contents of each column can take up a relatively large amount of space, I need to have horizontal scrolling enabled with `ImGuiTableFlags_ScrollX`.

The width of each column is correctly computed on most frames.
However, the width of every column becomes 0 (+ padding) whenever the number of tables changes.
This results in an undesirable flicker that is very noticeable if the application is rendering at a lower frame rate.

I expected ImGui to at least initialize the column widths using the column label.
However, I think it would be desirable for ImGui to preserve the previously column width data when the column count changes, at least for the minimum common number of columns.

It's worth noting that the `TableSetupColumn` does not appear to provide a way to set a reasonable minimum width.
I attempted to use the following, but it ended up being the permanent width instead of just an initial default:
```c++
    const float init_width = ImGui::CalcTextSize(header_label.c_str()).x;
    ImGui::TableSetupColumn(header_label.c_str(), column_flags, init_width);
``` 

**GIFs**
![imgui_column_sizing_issue-2021-04-15_23 08 06](https://user-images.githubusercontent.com/879918/114979490-ce86c880-9e3f-11eb-98c3-a9c6bc0d4fe0.gif)
![imgui_column_sizing_issue-2021-04-15_23 19 53](https://user-images.githubusercontent.com/879918/114980367-35f14800-9e41-11eb-9e57-c90f83d9a533.gif)

**Standalone, minimal, complete and verifiable example:**
```c++
if (!ImGui::Begin("Hack"))
{
  ImGui::End();
  return;
}

// Add a new column every 0.5s, up to a max of 10 columns before rolling over back to 1.
constexpr double seconds_per_new_column = 0.5;
constexpr int max_num_columns = 10;
const int column_count = static_cast<int>(ImGui::GetTime() / seconds_per_new_column) % max_num_columns + 1;

if (ImGui::BeginTable("Variable Column Count Table",
                      column_count,
                      ImGuiTableFlags_Borders | ImGuiTableFlags_ScrollX))
{
  char label[32];
  for (int column = 0; column < column_count; column++)
  {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wold-style-cast"
    ImFormatString(label, IM_ARRAYSIZE(label), "Column %d", column);
#pragma GCC diagnostic pop
    ImGui::TableSetupColumn(label);
  }
  ImGui::TableHeadersRow();

  constexpr int row_count = 10;
  for (int row = 0; row < row_count; row++)
  {
    ImGui::TableNextRow();
    for (int column = 0; column < column_count; column++)
    {
      ImGui::TableNextColumn();
      // Just some random contents that varies significantly from cell to cell.
      ImGui::Text("%d ^ %d = %d", column, row, static_cast<int>(pow(column, row)));
    }
  }
  ImGui::EndTable();
}

ImGui::End();
```

**Comment by ocornut** [comment] 2021-04-16 06:36
Thank you Arek for the careful bug report and repro. I did have that working afaik but condition may have changed, some flags may affect it or maybe there was a regression. I will investigate.

Note that hiding/showing column may be a suitable workaround here, but I agree it would be better to fix that scenario.

**Comment by ArekSredzki** [comment] 2021-04-16 06:43
Thanks for the speedy response as always @ocornut :) 
As a stop-gap, I'm considering showing/hiding columns programmatically as you suggest. However, since that has its own complications, it'd be nice to fix it directly.

**Comment by ArekSredzki** [comment] 2021-04-16 06:50
FYI, The same issue occurs with `ImGuiTableFlags_SizingStretchProp` or `ImGuiTableFlags_SizingFixedFit` instead of `ImGuiTableFlags_ScrollX`

**Comment by ocornut** [comment] 2021-04-16 16:32
Pushed fix 770f9daab3a81524147bd3252f14322ae2f52bec
Not very well exercised but the width restoration now has tests for this particular path.

I didn't attempt to preserve column order on column count change as it may be a more trickier (could be investigated later).

```cpp
if (ImGui::Begin("Test #4046"))
{
    // Add a new column every 0.5s, up to a max of 10 columns before rolling over back to 1.
    double seconds_per_new_column = 0.5f;
    int max_num_columns = 10;
    const int column_count = static_cast<int>(ImGui::GetTime() / seconds_per_new_column) % max_num_columns + 1;

    if (ImGui::BeginTable("Variable Column Count Table", column_count,  ImGuiTableFlags_Borders | ImGuiTableFlags_ScrollX))
    {
        char label[32];
        for (int column = 0; column < column_count; column++)
        {
            sprintf(label, "Column %d", column);
            ImGui::TableSetupColumn(label);
        }
        ImGui::TableHeadersRow();

        int row_count = 10;
        for (int row = 0; row < row_count; row++)
        {
            ImGui::TableNextRow();
            for (int column = 0; column < column_count; column++)
            {
                ImGui::TableNextColumn();
                // Just some random contents that varies significantly from cell to cell.
                ImGui::Text("%d ^ %d = %d", column, row, (int)powf((float)column, (float)row));
            }
        }
        ImGui::EndTable();
    }
    ImGui::End();
}
```

**Closed by ocornut** 2021-04-16 16:32 UTC
Labels: tables/columns

**Comment by ArekSredzki** [comment] 2021-04-16 16:53
@ocornut Thank you so much for the prompt fix! Would you mind merging it into the docking branch? Our build setup pulls ImGui from GitHub directly so having a merged commit hash would be very helpful :)

**Comment by ocornut** [comment] 2021-04-16 17:07
Sorry I did a docking update yesterday, if you need a temporary commit hash you can fork + cherry-pick + push.

**Comment by ArekSredzki** [comment] 2021-04-16 17:39
No worries, I wasn't sure how frequently you usually update the branch.

The fix works nicely, though it would be nice for the column width to be initialized with at least the column name.
That would make it less jarring when a new column is added.
Would that be difficult to incorporate?

**Comment by ocornut** [comment] 2021-04-16 17:46
Not as simple because what you refer to as “Colum name” is simply content which has been output in each column of the header row, and that is designed to be flexible (you can add leading checkboxes or not even submit the header row, still have columns names).

**Comment by ArekSredzki** [comment] 2021-04-16 17:54
I understand that doing it generically is difficult, but it would be nice to at least use an approximate version of the correct size rather than zero.

My thinking is that the min-width could be computed from the text size of the column label provided to `TableSetupColumn`.

However, being able to explicitly provide a _minimum_ column width would be valuable. Perhaps I missed it but I didn't see a method of doing so in the current API.

**Comment by ArekSredzki** [comment] 2021-04-20 06:04
@ocornut Would it be reasonable for me to open a new ticket requesting the enhancements described in my previous comment or is there an existing method for achieving this? :)

**Comment by ocornut** [comment] 2021-04-21 12:06
> but it would be nice to at least use an approximate version of the correct size rather than zero.

Outside of your specific use (appending new columns while table a showing): 
- You'd still get moving column in the case of a table appearing after host window is appearing. 
- Because settings are saved this only happens once.
Your use case is a little more specific because we do ditch those settings when resizing column count. If you simply hidden/shown column you wouldn't have this problem as much. 

> My thinking is that the min-width could be computed from the text size of the column label provided to TableSetupColumn.

In the case of a stretched down table this wouldn't be an adequate use.
That also wouldn't account for e.g. Sort markers.
