### ISSUE TITLE
Debug window in multi-viewport environment

### ISSUE THREAD

**Issue by rcane** [ocornut/imgui#4236] opened 2021-06-17 11:15 UTC
**Version/Branch of Dear ImGui:**

Version: 1.84 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: custom OpenGL-based backend
Operating System: Windows 10

**My Issue/Question:**

The "Debug##Default" window ImGui creates internally in `NewFrame()` can (unexpectedly) create its own viewport. This happened to me because the debug window saves (also unknown to me) its position in the settings file. And after activating the multi-viewport feature the saved position from before now lied slightly outside the main viewport so ImGui created an extra one for the debug window. The problem with this is that this created viewport is never registered with the backend (i.e. no platform callback is invoked for it). So my backend did not know about this viewport at all. This became an actual problem when I created a tooltip window which also was not inside the main viewport. When ImGui creates the viewport for that window it makes the (invisible) viewport of the debug window its parent. And when eventually `Platform_CreateWindow` is called for the new viewport my code tries to get to the platform parent window by checking `PlatformUserData` of the parent viewport. But since the viewport of the debug window was never passed to my backend `PlatformUserData` is `nullptr`.

I can certainly work around this problem but I think ImGui could make it much easier by simply not allowing the debug window to be moved outside the main viewport.
As I understand it this window is meant for the case when I make a mistake and forget to put my ImGui widgets into Begin/End pairs. So its purpose is simply to show me my mistake without crashing immediately. If that is the case why is the state of that window saved in the config at all? Since I normally don't want to see this window I certainly don't care about where it was placed on screen last time.

So I see two options to fix this in ImGui:

1. Make sure the debug window is always placed on the main viewport so that no additional viewport is ever created for it.
2. If 1 is not possible or wanted, at least invoke the appropriate platform callback when the viewport is created so a backend knows about it.

I guess it is clear which one I would prefer. 😉

**Comment by ocornut** [comment] 2021-06-17 13:24
Hello,

Your description of the problem is correct, however
- I think it is correct and desirable that backend doesn't see a platform window created for when the implicit Debug window is hidden.
- I am not sure we want to arbitrarily restrict usage of the implicit Debug window.

I think the problem we want to solve is:
> Then I created a tooltip window which also was not inside the main viewport. When ImGui creates the viewport for that window it makes the (invisible) viewport of the debug window its parent. 

That parenting perhaps should not happen.

Is your tooltip not triggered on e.g. hovering an item from an existing window? 
Could you provide code/pseudocode for it.

**Comment by ocornut** [comment] 2021-06-17 14:24
I have a pushed a fix for this:
cce307a2b
In line with a similar fix done for #2409, so right now there are consistent.

Ideally should be written a little differently but I think this should solve most issues.

**Closed by ocornut** 2021-06-17 14:24 UTC
Labels: multi-viewports

**Comment by rcane** [comment] 2021-06-17 14:27
I was just typing this to explain that I am using the tooltip to show information about objects from the underlying 3D scene. So it has no direct window parent. But you apparently fixed it too fast. 👍
