### ISSUE TITLE
ImGui::Button how to make it not changing ActiveID.

### ISSUE THREAD

**Issue by DaRallis** [ocornut/imgui#5096] opened 2022-03-11 23:35 UTC
----

**Version/Branch of Dear ImGui:**

Latest version.

**Back-end/Renderer/Compiler/OS**

Using DirectX9

Operating System: Win10

**My Issue/Question:**

Hi, how do I make a button that doesn't change the current active ID. Basically I've got a TextInput and I wanna click on a button without losing the focus for the TextInput. I tried a lot of things but none worked properly.

When I add an button the ActiveID is changed to the ButtonID instead of staying at the TextInputID and the TextInput focus is lost.

Thank you for any ideas.

**Screenshots/Video**
NaN

**Comment by ocornut** [comment] 2022-03-14 01:37
Duplicate of #1418 (also see #1554)

It's not possible but you can restore focus on the InputText() after pressing the button.
I think it would be good to rework the internal/undocumented _NoHoldingActiveID button behavior flag to actually not clear existing active id and then maybe this would work.

Please move this discussing to #1418.

**Closed** 2022-03-14 17:45 UTC
