### ISSUE TITLE
Dockbuilder Segmentation Fault

### ISSUE THREAD

**Issue by Isam-Ilyas29** [ocornut/imgui#3203] opened 2020-05-06 10:08 UTC
**Information:**

Version: 1.76 WIP
Branch: docking

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp 
Compiler: gcc
Operating System: linux, manjaro

**My Issue/Question:**

I seem to get a segmentation fault when executing this code multiple times during runtime: 
```cpp
if (ImGui::MenuItem("Default Layout")) { 
	ImGui::DockBuilderRemoveNode(mDockspaceID);
	ImGui::DockBuilderAddNode(mDockspaceID, ImGuiDockNodeFlags_None);
	ImGui::DockBuilderSetNodeSize(mDockspaceID, ImGui::GetMainViewport()->Size);

	ImGuiID dock_main = mDockspaceID;
	ImGuiID dock_right = ImGui::DockBuilderSplitNode(dock_main, ImGuiDir_Right, 0.3f, nullptr, &dock_main);
	ImGuiID dock_down = ImGui::DockBuilderSplitNode(dock_main, ImGuiDir_Down, 0.3f, nullptr, &dock_main);

	ImGui::DockBuilderDockWindow("Profiler##profiler1", dock_main);
	ImGui::DockBuilderDockWindow("Scene##scene1", dock_main);
	ImGui::DockBuilderDockWindow("Editor##editor1", dock_right);
	ImGui::DockBuilderDockWindow("Console##console1", dock_down);
	ImGui::DockBuilderDockWindow("Log##logger1", dock_down);
	ImGui::DockBuilderFinish(mDockspaceID);
}
```

![The callstack](https://user-images.githubusercontent.com/55923804/81120767-460c6200-8f25-11ea-92da-95783cb360b7.png)

**Full function:**
The full function can be found here and to clarify, I call this function before creating any of the windows in the current frame.
https://hastebin.com/wayiroriwo.cpp

**Comment by ocornut** [comment] 2020-05-06 10:31
Hello,

It is generally illegal to be using DockBuilderXXX function if they are affecting a window that you are in. I will try to add more assert/checks to detect those cases. Also see

**Comment by Isam-Ilyas29** [comment] 2020-05-06 10:41
So there generally isn't a way to add it to a menubar and its intended use is by itself?

**Comment by ocornut** [comment] 2020-05-06 10:50
You can put the UI to access that anywhere, but it's probably better if you run that DockBuilder code code at the beginning or end of the frame.

However note that I haven't looked at your specific issue in details yet, maybe there's another issue we can also fix on our end.

**Comment by ocornut** [comment] 2020-05-07 14:49
I'll close this topic to move the discussion to #3111

**Closed by ocornut** 2020-05-07 14:49 UTC
Labels: docking

**Comment by ocornut** [comment] 2021-07-07 14:26
> The full function can be found here and to clarify, I call this function before creating any of the windows in the current frame.
https://hastebin.com/wayiroriwo.cpp

Hello @Isam-Ilyas29,
That link seems to have elapsed, any chance you still have a trace of the full code as it was when you posted this?

**Comment by ocornut** [comment] 2021-07-07 14:48
Might be fixed with cd4cc9ff0d, but moving to #4295 which is a duplicate of this now.

**Comment by ocornut** [comment] 2021-07-07 16:23
Fully fixed with eb6f4b1a6a ! Yay!

**Comment by Isam-Ilyas29** [comment] 2021-07-10 12:22
Do you still require the code, I could have a go for looking for it?

**Comment by ocornut** [comment] 2021-07-10 15:48
Should be good, i eventually understood the bug! Thank you
