### ISSUE TITLE
Calling MemFree after an explicit destruction of the last context

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#992] opened 2017-01-22 21:08 UTC
Hello,

i have a InputText Field, if i copy paste some data from the clipboard. when i call the app, after the ImGui::Shutdown(); the app crash here in imgui.cpp
![screenhunter_110 jan 22 22 03](https://cloud.githubusercontent.com/assets/1434736/22185950/c1591f18-e0ee-11e6-992c-856a72aebd86.jpg)

i use your imgui_impl_sdl of example directory.

if i write something, there is no problem, but when i do ctrl+v, it crash (only when i close the app).
I dont know why this code is called after the ImGui:Shutdown(), and the callgraph of vs2015 on win7 give that
![screenhunter_111 jan 22 22 06](https://cloud.githubusercontent.com/assets/1434736/22185970/0ee30f46-e0ef-11e6-93bd-2a4261b2d7aa.jpg)

**Comment by ocornut** [comment] 2017-01-22 21:13
Can you confirm that you are getting the bug when running the _unmodified_ sample from the `sdl_opengl2_example` folder?

There's no code afaik that explicitly set GImGui to NULL.

**Comment by aiekick** [comment] 2017-01-22 22:14
no it work, its weird, i have replace all the imgui and the interface with sdl2 from my app in the example and it work.
it may be a problem in my windows system..
i create a imgui context and i destroy it, maybe like you mention, it is due to that.

but im not sure why i created a context :), i find that in a sample on the net. what is the goal to create a imgui context ?

**Comment by aiekick** [comment] 2017-01-22 22:16
it was for a multi windows system. how can i destroy the current context properly ? it is necessary ?

**Comment by ocornut** [comment] 2017-01-23 07:12
Hmm.

Right now the easiest workaround is to never destroy the initial/default context.
You have memory (probably a static ImVector) allocated that's being free after the context, it is a restriction that's inconvenient and undesirable. I'm not often running into it myself as I don't really use multiple context.

It's an issue with the design of storing those `MemAllocFn` `MemFreeFn` handlers in the context. 
Perhaps they should just be global in the first place, as it is unlikely that people would need different allocator for different contexts (and even so, we could add a context pointer to the allocator function?).

I chose to put them in the context to avoid relying on `#define` which are less obvious to setup depending on your build system and/or how/if you compile dear imgui yourself.

I think I might just bite the bullet and move to global functions, aka GImGuiMalloc, GImGuiFree ?

Moving this discussion to #586

**Comment by aiekick** [comment] 2017-01-24 01:01
for the moment, i not used the many context. and the bug appear only with the use of ctrl+v, so for the moment, i can wait a fix :) thanks, for the explains

**Comment by sonoro1234** [comment] 2017-02-06 16:19
It is not happening for destroying default context, just destroying any context sets GImGui to NULL.

**Comment by paulsapps** [comment] 2017-02-06 18:02
How come unmodified sample hasn't got this issue then?

**Comment by sonoro1234** [comment] 2017-02-07 16:30
unmodified sample only uses default context

**Comment by zx64** [comment] 2017-11-10 23:47
I've been running into a sporadic crash on shutdown in a Windows codebase that uses a non-default context. The code lives inside a DLL, so context lifetime is tied to when the DLL loads and unloads, but static variables are only destructed at process exit which happens after the DLL is unloaded...

The callstack points at the destructor for this variable:

```
static const char* GetClipboardTextFn_DefaultImpl(void*)
{
    static ImVector<char> buf_local;
```

I've locally changed it so it always uses a `ImVector<char>` that's tied to the current context:
`ImVector<char>& buf_local = GImGui->PrivateClipboard;`

I haven't done substantial testing to confirm if that fixes my problem, but does that seem like a reasonable change to make?

**Comment by ocornut** [comment] 2017-11-11 09:23
@zx64 Well it would work but it is a little odd and misleading. That clipboard function should have nothing to do with an imgui context and you are using a buffer than happens to be lying in a context, so it ties the lifetime of the return value to the context. Practically speaking it is probably ok but it feels very misleading.

> The code lives inside a DLL, so context lifetime is tied to when the DLL loads and unloads, but static variables are only destructed at process exit which happens after the DLL is unloaded...

If I understand correctly the problem is that at the time of destruction ImVector<> cannot access a destructor since it is stored in the current GImGui instance pointer? 
Would my suggested changes in this message https://github.com/ocornut/imgui/issues/586#issuecomment-332249326 solve the problem?

If that's the case you might also be able to temporarily workaround by restoring the default context after destroying your context.

(I suppose I should bite the bullet at some point and setup a DLL system to understand those problem better - I'm happy using Edit & Continue or Recode which doesn't requires DLL nor kill instances).

**Comment by zx64** [comment] 2017-11-11 13:53
I think those changes would help - it'd avoid having `ImVector`'s internal storage being allocated by one context and freed by another.
The asymmetric lifetime of function statics makes this especially awkward, hence my initial thought to remove needing to have a static variable - and there happened to be a buffer used by the non-Win32 default implementation of the clipboard.

**Comment by ocornut** [comment] 2017-11-11 14:02
In spite of being a little odd, It wouldn’t hurt to implement your suggestion with an explicit comment to describe it. So I’m going to do that in the meanwhile as it is an easy change.

**Comment by ocornut** [comment] 2018-02-06 20:52
@aiekick the changes described in #1565 should fix everything described in this issue.
You can now override the allocators with `ImGui::SetAllocatorFunctions()`, and they aren't stored in the context at all.

There's no default static/global context in imgui.cpp, only a pointer and you need to call CreateContext() to allocate a context.

If you have `ImVector<>` etc. destructed during program destruction when you'd want your allocators to be available during destruction as well.

**Closed by ocornut** 2018-02-06 20:52 UTC
Labels: multi contexts
