### ISSUE TITLE
Chinese support in std: c ++ latest

### ISSUE THREAD

**Issue by Bywnb** [ocornut/imgui#3044] opened 2020-02-29 12:24 UTC
This issue uses Google Translate entirely. I used Google Translate to translate from Chinese to English, please forgive me if there is a mistake!

First, there is no problem using English in / std: c ++ 17. I encountered a problem when I used / std: c ++ latest

In std: c ++ 17, the following code can be converted from English display to Chinese display
English display:
`ImGui::MenuItem("My software", nullptr, &window.software);`
Chinese display:
`ImGui::MenuItem(u8"我的软件", nullptr, &window.software);`

When I try to release in / std: c ++ latest , vs gives an error
Error (Active) E0304 There is no overloaded function "ImGui :: MenuItem" instance matching the argument list

I am a beginner, ask for help, thank you

**Comment by heroboy** [comment] 2020-02-29 12:42
I think you ask the same question again. https://github.com/ocornut/imgui/issues/2708

**Comment by Bywnb** [comment] 2020-02-29 12:50
> I think you ask the same question again. #2708

Maybe yes, but how should i solve this

**Comment by kudaba** [comment] 2020-02-29 21:22
I just tried locally and I don't get any errors. In the short you you could probably just write:
``ImGui::MenuItem((const char*)u8"我的软件", nullptr, &window.software);``
To force the cast to the correct type. utf works at the bit level so signed or unsigned won't make any difference.

**Comment by ocornut** [comment] 2020-03-01 17:51
Closing as duplicate of #2708 

I am baffled that C++20 somehow dedicated to break this default conversion. I guess few users stored localized strings in their codebase. By doing so they are pushing earlier engineering effort from casual users which is not a good sign of how crippled and unflexible modern C++ is becoming.

See https://stackoverflow.com/questions/56833000/c20-with-u8-char8-t-and-stdstring and http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1423r2.html justly mentioned in the other issue.

**Closed by ocornut** 2020-03-01 17:51 UTC
Labels: font/text
