### ISSUE TITLE
Enable/Disable buttons etc.

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#901] opened 2016-11-10 10:18 UTC
Is there a way to enable/disable buttons (and other widgets) based on user interaction? For example, based on a user action a visible button changes state from disabled to enabled?

**Comment by ocornut** [comment] 2016-11-12 11:37
There's no way at the moment, it is something that needs to be done.
Duplicate of #211

**Closed by ocornut** 2016-11-12 11:37 UTC
