### ISSUE TITLE
A character is deleted when creating a newline in 'InputTextMultiline'.

### ISSUE THREAD

**Issue by netrunnernobody** [ocornut/imgui#1411] opened 2017-11-01 18:56 UTC
Found a minor bug earlier. If you press enter mid-line within an InputTextMultiline, you lose a character.

An example of this would be "Hello World!". If you were to press enter with your cursor between "Hello" and "World", the resulting string would be

> Hello
> orld!

Not a major bug, but might be worth looking into.

**Comment by ocornut** [comment] 2017-11-01 19:02
I just tried with many of the examples application and cannot reproduce the issue.
Which imgui_impl_XXX file are you using? Did you implement your own or modify them?

Maybe you are submitting both a `ImGuiKey_Enter` key-pressed and a `\n` character input and that causes problem? Just guessing.

**Comment by ocornut** [comment] 2018-01-17 14:25
@netrunnernobody Any news on that? In the absence of more details this report seems invalid to me, but I appreciate more info. If you have an issue with your binding code I'd be happy to help.

**Comment by ocornut** [comment] 2019-03-13 11:01
@netrunnernobody Closing as invalid, and not providing details/repro.

**Closed by ocornut** 2019-03-13 11:01 UTC
Labels: backend/binding, inputtext
