### ISSUE TITLE
Unusual slider behavior when grab clicked

### ISSUE THREAD

**Issue by demucin** [ocornut/imgui#4583] opened 2021-09-25 15:20 UTC
<strong>Version/Branch of Dear ImGui:</strong>
Version: v1.85
Branch: master

<strong>Back-end/Renderer/Compiler/OS:</strong>
Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp

<strong>My Issue/Question:</strong>
Related with vertical slider's unexpected behavior.
Scrolling process starts as soon as mouse down
over the grab without any dragging.

<strong>minimal code to reproduce:</strong>
down the mouse over grab and up (click the grab) value will be changed.
I hope I was able to express...Thanks.

<code>
        ImGui::Begin("vertical slider");
        static int int_value = 0;

        ImGui::PushStyleVar(ImGuiStyleVar_GrabMinSize, 40);
        ImGui::VSliderInt("##0, 1..512", ImVec2(48, 160), &int_value, 0, 512);
        ImGui::PopStyleVar();

        ImGui::End();
</code>

**Comment by ocornut** [comment] 2021-09-25 19:17
Duplicate of #1946 will move discussion there.

**Closed by ocornut** 2021-09-25 19:17 UTC
Labels: sliders/drags
