### ISSUE TITLE
Glitch in 1.67 with multiple BeginChild/EndChild to append

### ISSUE THREAD

**Issue by codz01** [ocornut/imgui#2282] opened 2019-01-15 13:51 UTC
in the d3d9 example i've found this :
![gif](https://user-images.githubusercontent.com/10813427/51184512-c17f7580-18d4-11e9-988d-d9c20dc36873.gif)

**Comment by ocornut** [comment] 2019-01-15 14:12
Good catch, this was caused by 6890e08bc5c9d00cae3af913e47c9daf017e0164 and fixed in b8c6e31c2de36d80ed16af54b80ae8e489964f84. I added pushed and updated tag and updated the release note.

**Closed by ocornut** 2019-01-15 14:12 UTC
Labels: bug
