### ISSUE TITLE
Table with ImGuiTableFlags_ScrollY does not reserve horizontal space for vertical scrollbar

### ISSUE THREAD

**Issue by bratpilz** [ocornut/imgui#7651] opened 2024-06-03 08:48 UTC
### Version/Branch of Dear ImGui:

Version 1.90.8 WIP, Branch: master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Linux + GCC 12

### Full config/build information:

```
Dear ImGui 1.90.8 WIP (19073)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201103
define: __linux__
define: __GNUC__=12
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**

When using ImGuiTableFlags_ScrollY in a table, no horizontal space gets reserved for the vertical scroll bar, causing the end of the table content to be cut off.

I think the issue lies in line 1494 of imgui_tables.cpp:
```c++
        const float decoration_size = table->TempData->AngledHeadersExtraWidth + ((table->Flags & ImGuiTableFlags_ScrollX) ? inner_window->ScrollbarSizes.x : 0.0f);
```
If I change ImGuiTableFlags_ScrollX to ImGuiTableFlags_ScrollY here, the issue goes away, and this change makes sense to me since only a vertical scrollbar would need additional horizontal space.

### Screenshots/Video:

Before change:
![imgui-table-scrollbar-fit-issue](https://github.com/ocornut/imgui/assets/2135591/8b414247-29c3-407c-876a-450f7827c207)

After change:
![imgui-table-scrollbar-fit-fixed](https://github.com/ocornut/imgui/assets/2135591/2c4e5939-f239-4ec9-8d27-c66edf30ed2a)

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
	ImGui::Begin("Table Issue", 0, ImGuiWindowFlags_AlwaysAutoResize);
	// ImGui::TextUnformatted("<Extra widgets>");
	unsigned flags = ImGuiTableFlags_SizingFixedFit | ImGuiTableFlags_ScrollY;
	if (ImGui::BeginTable("Table", 1, flags, ImVec2(0.0f, 100.0f)))
	  {
	    for (int i = 0; i < 100; ++i)
	      {
		ImGui::TableNextColumn();
		ImGui::Text("Row %02d - Loooooong text", i);
	      }
	    ImGui::EndTable();
	  }
	ImGui::End();
```

**Comment by ocornut** [comment] 2024-06-03 17:08
Thanks for reporting this.
I have pushed a fix : a31aa68

For clarity, it specifically relates to how the table reports its ideal contents size to the auto-resizing parent container.

The problem is a little big more complex than meet the eyes and it's not impossible we would need to get back to this.
One issue is that the reports bubbling up into parents may create one frame glitches, we could technically pre-compute expected visibility of scrollbar ahead to reduce issues in this case.

Amended "table_reported_size" test:
https://github.com/ocornut/imgui_test_engine/commit/0231200f731953c533f59100e8898e768cc3b3f7

**Closed by ocornut** 2024-06-03 17:08 UTC
Labels: tables/columns, scrolling
