### ISSUE TITLE
How to make windows that snap to locations and then stay sort off fixed?

### ISSUE THREAD

**Issue by Tim4135** [ocornut/imgui#1591] opened 2018-02-03 17:04 UTC
Hi,

I am creating a OpenGL (game) engine kind off thing and i am using IMGUI for the GUI part.
I found it very easy to use so far, but i have a problem:
I would like to have windows that can snap to the sides of the OpenGL window and can be switched between like in this picture here:
![](https://user-images.githubusercontent.com/153526/29975939-9c3db48e-8f38-11e7-80f1-2a777e7a43c8.png)
In the picture he has 3 tabs named scene view, import asset and game view where he can switch between.
I would like to know how i could do that.
And I also have another question:
If I want, how could I make these 3 tabs movable, so I could move the game view window/tab to the side for example, or completely have it as a floating window?(but still in the same OpenGL window off course)

Could someone help me with this?

Thanks

**Comment by nem0** [comment] 2018-02-03 22:06
See #351

**Comment by Tim4135** [comment] 2018-02-03 22:29
Thanks will look into it, but i am looking more for a way to get tabs in my editor.
Anyone know how to do that?
Is it included in IMGUI or is it something third party/something I have to create myself?

**Comment by nem0** [comment] 2018-02-03 22:35
I still assume you want docking, which is in the picture you posted. And that can be found in #351.

In case you really want just tabs, which is something different, see #261 or #1083

**Comment by Tim4135** [comment] 2018-02-03 22:54
Hi, yes, i would like both.
I BTW. found this:
https://github.com/ocornut/imgui/issues/261#issuecomment-338699653
Does someone know the progress on that?
And @nem0 , am I right that your are the creator of the engine in the picture?
How did you achieve what you have?

**Comment by nem0** [comment] 2018-02-03 23:03
Yes I'm the author of that. You can find everything in #351

**Comment by nem0** [comment] 2018-02-03 23:04
There's also more advanced version https://github.com/thennequin/ImWindow

**Comment by ocornut** [comment] 2018-02-03 23:20
Tim, while your questions are legit they are also very general questions to complex problems and it looks like you haven’t researched it very much. As Mikulas pointed out that thread has references and you may also check for the various docking/tabs links in the Wiki.

The short answer is that I am working on an official solution but it’s not ready, and among third party solutions the one Mikulas wrote and which has been forked/tweaked by other people is a viable and functional option too. 

The tabs in #261 were released as a short-term branch based on early Docking researchs, but it’s not much more than Tabs. It’s useful but not as useful as a full docking solution.

Closing this as duplicate of #351, feel free to ask questions here or therr tho.

**Closed by ocornut** 2018-02-03 23:20 UTC
