### ISSUE TITLE
Using buttons as tabs wont work!

### ISSUE THREAD

**Issue by darkingman123** [ocornut/imgui#1233] opened 2017-07-16 04:47 UTC
Hi, i tried multiple times to get this to work with different methods.... current code looks like this
`int m_CurrentPane;

					if (ImGui::Button(XorStr("RAGE"), ImVec2(100.f, 40.f))) m_CurrentPane = 1;
					ImGui::SameLine();
					if (ImGui::Button(XorStr("LEGIT"), ImVec2(100.f, 40.f))) m_CurrentPane = 2;
					ImGui::SameLine();
					if (ImGui::Button(XorStr("VISUALS"), ImVec2(100.f, 40.f))) m_CurrentPane = 3;
					ImGui::SameLine();
					if (ImGui::Button(XorStr("ANTIAIMS"), ImVec2(100.f, 40.f))) m_CurrentPane = 4;
					ImGui::SameLine();
					if (ImGui::Button(XorStr("MISC"), ImVec2(100.f, 40.f))) m_CurrentPane = 5;

					ImGui::Separator();

					if (m_CurrentPane == 1)
					{
						ImGui::Checkbox(XorStr("Auto Shoot"), &OptionsManager.bAutoShoot);
						ImGui::Checkbox(XorStr("Auto Pistol"), &OptionsManager.bAutoPistol);
						ImGui::Checkbox(XorStr("Auto Scope"), &OptionsManager.bAutoScope);
						ImGui::Checkbox(XorStr("Silent aim"), &OptionsManager.bSilentAim);
						ImGui::SliderInt(XorStr("HitChance"), &OptionsManager.iHitchance, 0, 100);
						ImGui::SliderInt(XorStr("HitChance Max Seeds"), &OptionsManager.iHitChanceSeed, 0, 256);

						ImGui::Checkbox(XorStr("Resolve angle"), &OptionsManager.bCorrect);
						static const char *szResolveType[] = { XorStr("Simple"), XorStr("Delta calc"), XorStr("Delta calc 2"), XorStr("Anti-Anti-Resolver") };
						ImGui::Combo(XorStr("Resolver type"), &OptionsManager.iResolverType, szResolveType, ARRAYSIZE(szResolveType));

						static const char *szMultiHitboxes[] = {
							XorStr("Head"), XorStr("Neck"), XorStr("Upper Chest"), XorStr("Chest"), XorStr("Thorax"),
							XorStr("Body"), XorStr("Left Forearm"), XorStr("Right Forearm"), XorStr("Hands"), XorStr("Left Thigh"),
							XorStr("Right Thigh"), XorStr("Left Calf"), XorStr("Right Calf"), XorStr("Left Foot"), XorStr("Right Foot")
						};

						ImGui::Text("Multipoint hitboxes scan :");
						ImGui::BeginChild("#multipoint", ImVec2(0, 200), true, ImGuiWindowFlags_AlwaysVerticalScrollbar);
						for (int i = 0; i < ARRAYSIZE(szMultiHitboxes); ++i) {
							ImGui::Selectable(szMultiHitboxes[i], &OptionsManager.aMultiHitboxes[i]);
						}
						ImGui::EndChild();

						ImGui::Checkbox(XorStr("Awall Prioritize Visible Parts"), &OptionsManager.bPrioritizeVis);
						ImGui::Checkbox(XorStr("Prioritize Selected Hitbox"), &OptionsManager.bPrioritize);
						ImGui::SliderInt(XorStr("Select Hitbox"), &OptionsManager.iHitbox, 0, 20);
						ImGui::SliderFloat(XorStr("Min Damage"), &OptionsManager.flMinDmg, 0, 100);
						ImGui::Checkbox(XorStr("Auto Body-Aim"), &OptionsManager.bAutoBaim);
						ImGui::SliderInt(XorStr("Body-Aim After Shots"), &OptionsManager.iAutoBaimAferShot, 0, 10);
						ImGui::SliderInt(XorStr("Select Hitbox Auto Body-Aim"), &OptionsManager.iHitboxAutoBaim, 0, 20);
						ImGui::Checkbox(XorStr("Disable Interp/Lag Compensate"), &OptionsManager.bInterpLagComp);
					}
					else if (m_CurrentPane == 2)
					{
						ImGui::Text("Soon to come");
					}

					else if (m_CurrentPane == 3)
					{
						ImGui::Checkbox(XorStr("Glow"), &OptionsManager.bGlow);
						ImGui::Checkbox(XorStr("Health"), &OptionsManager.bHealthBar);
						ImGui::Checkbox(XorStr("Armor"), &OptionsManager.bArmorBar);
						ImGui::Checkbox(XorStr("Player Name"), &OptionsManager.bPlayerName);
						ImGui::Checkbox(XorStr("Player Index"), &OptionsManager.bPlayerIndex);
						ImGui::Checkbox(XorStr("Bone ESP"), &OptionsManager.bBoneESP);
						ImGui::Checkbox(XorStr("Weapon ESP"), &OptionsManager.bWeaponESP);
						ImGui::Checkbox(XorStr("No Scope"), &OptionsManager.bNoScope);
					}
					else if (m_CurrentPane == 4)
					{
						ImGui::Checkbox(XorStr("No Flash"), &OptionsManager.bNoFlash);
						ImGui::Checkbox(XorStr("No Visual Recoil"), &OptionsManager.bNoVisRecoil);
						ImGui::SliderInt(XorStr("Fov"), &OptionsManager.iFov, 0, 90);
						ImGui::Checkbox(XorStr("Water Mark"), &OptionsManager.bWaterMark);
						ImGui::Checkbox(XorStr("Indicators"), &OptionsManager.bIndicators);
					}
					else if (m_CurrentPane == 5)
					{
						ImGui::Checkbox(XorStr("Fakelag"), &OptionsManager.bFakeLag);
						ImGui::SliderInt(XorStr("Choke Packets"), &OptionsManager.iFakeLagAmount, 0, 50);

						ImGui::Checkbox(XorStr("AA Enable"), &OptionsManager.bAA);
						static const char *szAAPitch[] = { XorStr("Down"), XorStr("Up"), XorStr("Mid") };
						ImGui::Combo(XorStr("Pitch AA"), &OptionsManager.iAAPitch, szAAPitch, ARRAYSIZE(szAAPitch));

						static const char *szRealAAYaw[] = { XorStr("Simple 90 Jitter"), XorStr("Static side") };
						ImGui::Combo(XorStr("Real Yaw AA"), &OptionsManager.iAARealYaw, szRealAAYaw, ARRAYSIZE(szRealAAYaw));

						static const char *szFakeAAYaw[] = { XorStr("Kidua A-Resolver"), XorStr("Sqch A-Resolver"), XorStr("Backward"), XorStr("TEST") };
						ImGui::Combo(XorStr("Fake Yaw AA"), &OptionsManager.iAAFakeYaw, szFakeAAYaw, ARRAYSIZE(szFakeAAYaw));
					}`

It either doesnt respond to the button press or does not draw

**Comment by ocornut** [comment] 2017-07-16 05:02
Try looks correct assuming m_CurrentPane is persistant and not reset every frame.
**Please provide a full repro we can paste into one of the examples/ application, so that we have all the context, and which would also force you to simplify and narrow down the problem**.
Right now nobody can run/compile your code!
If I'm not mistaken, this isn't your first time here coming with vague reports and not following on requests for details, so I'll close this until you can come with a clear repro. Thanks.

**Closed by ocornut** 2017-07-16 05:02 UTC

**Comment by darkingman123** [comment] 2017-07-16 05:09
This is my first time here and i have no clue what you mean by clear repro.

**Comment by darkingman123** [comment] 2017-07-16 05:17
Oh well, m_CurrentPane is only an int i created to store values. Im sure this is wrong. How do i correctly define m_CurrentPane?

**Comment by ocornut** [comment] 2017-07-16 05:23
OK sorry for the confusion then (we received _many_ requests in the past with very similar code and related to tabs, and most of the time they aren't imgui problems but rather misunderstanding of C++ from the user).

> Oh well, m_CurrentPane is only an int i created to store values. Im sure this is wrong. How do i correctly define m_CurrentPane?

Your question suggest non-familiarity with C++, which is fine but this place really isn't the place to ask then. It's really harming imgui that people are using this forum not asking questions not related to imgui. Please use general programming forums, they will also force you to narrow down and clarify your problem.

> This is my first time here and i have no clue what you mean by clear repro.

A clear reproduction would be: the smallest and simplest possible standalone piece of code people can use to reproduce your issue on their computer. Typically we don't request a full standalone application but a piece of code we can paste in one of the examples/ application that are ready-to-use. Creating one would force you to 1) narrow it down all the useful information and ideally 2) have you remove the unnecessary confusing information. Very often in the process of doing that you will understand and solve the issue by yourself before it's even ready to be posted.

Right now if I look at the code you posted, it seems correct. Which I why I'm saying that we are missing pieces of the puzzle to help you. How is m_currentPane stored, it is being initialized? etc. Providing a standalone repro would answer all those questions and someone on a general programming/C++ community would help you/

It also doesn't help that you come with an ill-defined problem that looks exactly the same as 5 persons before you, and don't end your message with a "Thank you".

**Comment by ocornut** [comment] 2017-07-16 05:32
> Oh well, m_CurrentPane is only an int i created to store values. Im sure this is wrong. How do i correctly define m_CurrentPane?

Another way to put it is: words are ambiguous. one may be confused, talking about different things, or omitting information.

The only non ambiguous thing is the actual code you use. Out of courtesy for others, but also because it is the easiest way for you to solve your problem, you want to simplify it and trim the fat to only share what really relates to the issue at hand.
