### ISSUE TITLE
move `struct ImGui_ImplOpenGL3_Data` definition from `imgui_impl_opengl3.cpp` to one of it's headers

### ISSUE THREAD

**Issue by betsch85** [ocornut/imgui#6269] opened 2023-03-23 12:38 UTC
**Version/Branch of Dear ImGui:**

Version: 1.89.4
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp

**My Issue/Question:**

For debugging reasons I'm giving the ImGui GL object/shaders labels using `glObjectLabel`, for that I need to get the handles from ImGui, which are in `imgui_impl_opengl3.cpp` (`struct ImGui_ImplOpenGL3_Data`), currently I've copied that definition into one of my header files, but if the layout of the members (at least those coming before the one I'm using) will change in the future I wouldn't notice, so it'd be nice to move that definition to one of the `imgui_impl_opengl3*`-headers

I'm only using this in debug builds so it's not that important but if it isn't too inconvenient for you it'd be nice

**Comment by ocornut** [comment] 2023-03-23 15:18
It'd be too dangerous to move those internal structs to the header file as it would increase the like-hood of people using that data. However I'd be open to add the `glObjectLabel()` calling code to the backend if it was carefully designed to work with every loader, GL headers and GL runtime version.

**Comment by ocornut** [comment] 2023-03-23 15:36
I'll close this as wont-fix. 

If you want to submit a PR with calls to `glObjectLabel`: add a dummy call anywhere in the imgui_impl_opengl3.cpp, then run https://github.com/dearimgui/gl3w_stripped to update our custom loader. Using our custom loader technically you may be able to use `if (glObjectLabel != NULL) glObjectLabel(....);` the problem is that I'm not 100% sure a test like this will work with other loaders, so perhaps the whole thing needs to be wrapped in a function that only exists if `IMGL3W_IMPL` is defined.

Personally I would suggest you maintain a small fork on your side and rebase when updating.

**Closed by ocornut** 2023-03-23 15:36 UTC
Labels: backends, opengl
