### ISSUE TITLE
Is there any ways to color some string in one string variable?

### ISSUE THREAD

**Issue by tempacc123** [ocornut/imgui#1325] opened 2017-09-16 07:07 UTC
I want to color string "perspective" in one big string variable. can i achive this with imgui?

		if (mode.find("Perspective") !=std::string::npos)
			ImGui::TextColored(ImVec4(1.0f, 0.0f, 0.0f, 1.0f), mode.c_str());

current imgui function makes whole of them colored :(

**Comment by ocornut** [comment] 2017-09-16 13:16
Closed as duplicate of https://github.com/ocornut/imgui/issues/902
There's no trivial or standard way to do it without custom code, but it's possible.

**Closed by ocornut** 2017-09-16 13:16 UTC
