### ISSUE TITLE
Horizontal scrolling is backwards in imgui_impl_win32 and imgui_impl_sdl

### ISSUE THREAD

**Issue by PathogenDavid** [ocornut/imgui#4019] opened 2021-04-07 20:15 UTC
**Version/Branch of Dear ImGui:**

Version: [current `master`](https://github.com/ocornut/imgui/commit/d6a5cc7934b4f4f9d5effffc4f1acee151247f51), [current `docking`](https://github.com/ocornut/imgui/commit/65cd14502c2a018b736636de14326be2a86f04da)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Back-ends: imgui_impl_sdl.cpp + imgui_impl_dx11.cpp
Compiler: MSVC 19.28.29913 x64 (Visual Studio 2019 16.9.3)
Operating System: Windows 10 x64 20H2 (19042.867)

**My Issue/Question:**

The horizontal scrolling direction in Dear ImGui with the Win32/SDL backends is backwards when compared to other Windows applications. It is correct with the imgui_impl_glfw backend. This issue is observable in the official examples. (I specifically tested `example_glfw_opengl3`, `example_sdl_directx11`, and `example_win32_directx12`.)

For the sake of clarity, I am going to describe scrolling in terms of what the scrollbar's grabber does in response to you moving the mouse wheel.

1. Launch something with horizontal scrolling that isn't powered by Dear ImGui. (IE: Visual Studio, a web browser.)
  a. Open content which is too wide for the screen or resize the window so a horizontal scrollbar appears.
  b. Press right on the scroll wheel. **The grabber moves to the right.**
  c. Press left on the scroll wheel. **The grabber moves to the left.**
2. Launch `example_win32_directx12`
  a. In the demo window, expand `Layout & Scrolling` and then `Scrolling
  b. Uncheck `Track`
  c. In one of the horizontal scrolling examples...
  d. Press right on the scroll wheel. **The grabber moves to the left.**
  e. Press left on the scroll wheel. **The grabber moves to the right.**
3. Repeat step 2 with `example_sdl_directx11`, same result.
4. Repeat step 2 with `example_glfw_opengl3`:
  a. When pressing right on the scroll wheel, **The grabber moves to the right.**
  b. When pressing left on the scroll wheel, **The grabber moves to the left.**

As you can see, `example_win32_directx12`/`example_sdl_directx11` are backwards from what would be expected when compared to other Windows apps as well as `example_glfw_opengl3`.

**Screenshots/Video**

This issue is difficult to convey in screenshots/video. I believe it should be apparent from following the steps above.

**Standalone, minimal, complete and verifiable example:**

This issue reproduces in the Dear ImGui examples without changes.

----------------

**Root cause**

This issue essentially happens because Dear ImGui treats `MouseWheelH` in the positive as being a scroll to the left. (Which mirrors positive `MouseWheel` being a scroll up.)

However, both [`WM_MOUSEHWHEEL`](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-mousehwheel) and [`SDL_MouseWheelEvent.y`](http://wiki.libsdl.org/SDL_MouseWheelEvent) are defined as positive being a scroll to the right. ([`GLFWscrollfun`](https://www.glfw.org/docs/3.0/group__input.html#ga4687e2199c60a18a8dd1da532e6d75c9) does not say, but it's apparently the opposite. Probably to make it consistent with `yoffset` which is positive up for all three.)

**Proposed fix**

The easiest fix would be to document the expectation for both `ImGuiIO::MouseWheel` and `ImGuiIO::MouseWheelH`, and flip them in the affected backends.

Additionally, the horizontal scrolling in `ImGui::UpdateMouseWheel` could also be flipped to match the convention of SDL/Windows. If this is done, I think it needs to be done by flipping [the `MouseWheelH` read](https://github.com/ocornut/imgui/blob/d6a5cc7934b4f4f9d5effffc4f1acee151247f51/imgui.cpp#L3748) rather than flipping [the call to `SetScrollX`](https://github.com/ocornut/imgui/blob/d6a5cc7934b4f4f9d5effffc4f1acee151247f51/imgui.cpp#L3774) as the latter would affect shift scrollings. (In my opinion, the current shift scrolling is intuitive. There's not a lot of precedent for this interaction on Windows, but Photoshop and Dear ImGui both move the grabber left if I use control/shift+scroll up.)

The downside of modifying `ImGui::UpdateMouseWheel` is that it could potentially break custom backends. Although since the direction of `MouseWheelH` wasn't defined before, it's possible this bug is present in many custom backends as well. (I actually originally discovered this issue in my own custom backend since I expected positive right.)

**Comment by ocornut** [comment] 2021-04-07 20:25
Thank you David!
Will investigate this later. For now linking to #3394 and #1463
Note that #3394 didn't investigate SDL and didn't connect that `MouseWheelH` value to Scrolling.

**Comment by PathogenDavid** [comment] 2021-04-07 20:46
Ah, I bet #3394 was the same issue but they blamed the wrong thing. The [`ALLEGRO_EVENT_MOUSE_AXES` documentation](https://www.allegro.cc/manual/5/ALLEGRO_EVENT#allegro_event_mouse_axes) doesn't explicitly say, but based on the description of `mouse.z` I'd assume `mouse.w` is positive right like SDL and Windows. Odd that they said SDL was correct for them though, that makes me wonder if SDL has a bug on Linux that cancels this out there.

Also this reminded me I meant to check on my laptop too for the sake of sanity. I can confirm its trackpad acts the same as my desktop's mouse. (GLFW matches other apps, Win32 and SDL are backwards.)

**Comment by rokups** [comment] 2021-06-01 12:42
Can confirm that inverting x axis on SDL/Win32 works as expected. This also works properly on MacOS when holding SHIFT (92b7b1f caused some problems regarding that). While testing this i noticed that for some reason wheel acceleration was disabled. Allowing SDL to accelerate wheel does not seem to have any unwanted effects and makes wheel behave consistently in imgui and native applications, so i included that change in commit linked above as well.

**Comment by ocornut** [comment] 2021-06-01 16:58
@rokups I believe "wheel acceleration" should be left to a separate discussion and PR, it's probably not a simple topic to handle as the amount are not well defined across platforms/backends. It'd be useful to report how those mouse wheel values are generated by SDL for every platform.

It's difficult to test a way to natively send MOUSEWHEELH events here, and Mac mouse drivers on drivers have options to invert the axis making things more confusing. Additionally I'm unsure all OS scroll the same way depending on mouse.

> Odd that they said SDL was correct for them though, that makes me wonder if SDL has a bug on Linux that cancels this out there.

That should be enough of a hint to suggest we might be overlooking something. I think we need a wider range of tests done across platforms (+ bonus checking if third-party drivers involved have invert options). That person basically says SDL and GLFW works the same for them, and now we are inverting SDL but not GLFW. We are missing something.

SHIFT+vertical wheel also needs testing separately from horizontal wheel.

**Comment by rokups** [comment] 2021-09-01 12:45
```
OS is configured so scrollbar moves to the direction of wheel (which means on MacOS natural scrolling is disabled).

Linux (SDL2)
Modifiers do not change wheel direction.
Amplitude can reach -10/+10 or more on rapid flicks.
Up           = +1 +0
Down         = -1 +0
Left         = +0 +1   // Incorrect, fix pending https://github.com/libsdl-org/SDL/pull/4700
Right        = +0 -1   //


Linux (GLFW)
Modifiers do not change wheel direction.
Amplitude can reach -10/+10 or more on rapid flicks.
Up           =    +1    +0
Down         =    -1    +0
Left         =    +0    +1
Right        =    +0    -1

Windows (SDL2)
Modifiers do not change wheel direction.
Amplitude can reach -2/+2, but flicks produce continuous event stream, simulating a wheel that is spinning when released.
Up           =    -1    +0
Down         =    -1    +0
Left         =    +0    -1
Right        =    +0    +1

Windows (GLFW)
Modifiers do not change wheel direction.
Amplitude can reach -1/+1, API may report -1 < value < 1 due to values divided by `WHEEL_DELTA`.
Up           =    +1    +0
Down         =    -1    +0
Left         =    +0    +1
Right        =    +0    -1

Windows (Win32)
Modifiers do not change wheel direction.
Amplitude can reach -1/+1, API may report -1 < value < 1 due to values divided by `WHEEL_DELTA`.
Up           =    +1    +0
Down         =    -1    +0
Left         =    +0    -1
Right        =    +0    +1

MacOS (SDL2)
Amplitude can reach -12/+12 or more on rapid flicks. Values are always whole numbers.
Up           =    +1    +0
Down         =    -1    +0
Up   + Shift =    +0    -1  // Only available with a mouse, not working on a touchpad
Down + Shift =    +0    +1  //
Left         =    +0    -1
Right        =    +0    +1

MacOS (GLFW, mouse)
Amplitude can reach -6/+6 or more on rapid flicks.
Values can be fractional, single wheel tick is 0.1.
Up           =    +1    +0
Down         =    -1    +0
Up   + Shift =    +0    +1  // Only available with a mouse, not working on a touchpad
Down + Shift =    +0    -1  //
Left         =    +0    +1
Right        =    +0    -1
```

We are dealing with three distrinct bugs.
1. Inverted scrolling in Win32 backend.
2. Inverted scrolling in SDL backend.
3. SDL2 reports inverted horizontal scroll on X11/Linux.

As a result we get:
* Horizontal scroll is inverted on windows with win32 and sdl backends.
* Horizontal scroll is inverted on MacOS with sdl backend.
* Horizontal scroll works as expected on X11/Linux with sdl backend due to double inversion.

I submitted a PR to SDL to fix inverted events in X11 backend: https://github.com/libsdl-org/SDL/pull/4700.
While [proposed fix](https://github.com/ocornut/imgui/compare/master...rokups:rk/fix-inverted-wheel-x) is correct, it could include a workaround for SDL on Linux, taking into account inverted events on SDL versions before my proposed fix is merged. So now we wait for SDL people to take care of that PR.

**Comment by ocornut** [comment] 2023-01-31 20:19
Extra data (will add more as I test on my PC laptop with a touchpad)

Someone recently wondered why the SDL backend clamping mouse wheel inputs to -1/+1 (thread #6081) I didn't have a good answer yet as this clamping was added many years ago.

Interestingly, I tested the SDL2+Emscripten example and confirmed odd findings, namely that the scale of wheel values reported on Emscripten vary depending on the browser.
From the values I am getting, I don't think the / 20.0f is any correct :(
(You can visualize the values in Demo->Tools->Debug Log->IO)

Misc
- That's for SDL backend with the wheel clamping removed.
- The GLFW backend doesn't clamp the wheel value.
- Couldn't test horizontal on all computers yet.
- The web/Emscripten runs are for the same build (hosted by the same Windows machine).
- Couldn't get to run on OSX+Firefox (website shows black) so tested only Safari and Chrome there.

I also noticed SDL 2.0.18 added "preciseX/preciseY" fields so I am also testing those, but they are not available in Emscripten latest.
```
typedef struct SDL_MouseWheelEvent
{
    Sint32 x;           /**< The amount scrolled horizontally, positive to the right and negative to the left */
    Sint32 y;           /**< The amount scrolled vertically, positive away from the user and negative toward the user */
    Uint32 direction;   /**< Set to one of the SDL_MOUSEWHEEL_* defines. When FLIPPED the values in X and Y will be opposite. Multiply by -1 to change them back */
    float preciseX;     /**< The amount scrolled horizontally, positive to the right and negative to the left, with float precision (added in 2.0.18) */
    float preciseY;     /**< The amount scrolled vertically, positive away from the user and negative toward the user, with float precision (added in 2.0.18) */
```

**From Windows 11 (Desktop 1)**
```
- Mouse - Native(GLFW/SDL/Win32): UP: +1   / DOWN: -1   (occasionally a little more +2,+3 etc.) (SDL's precise fields are same)
- Mouse - Firefox:                UP: +108 / DOWN: -108 (fixed steps)
- Mouse - Chrome:                 UP: +350 / DOWN: -350 (fixed steps)
- Mouse - Edge:                   UP: +175 / DOWN: -175 (fixed steps)
- Can't test horizontal wheel here yet.

**From OSX: Vertical Wheel/Swipe**
- 3rd party Mouse - Native SDL:     UP: -1.0 to -~30   /    DOWN: +1.0 to +~30   (depends on wheeling velocity) (precise fields are same)
- 3rd party Mouse - Native SDL:  Sh+UP:  1.0 to +~30   / Sh+DOWN: -1.0 to +~30   (with SHIFT. all values becomes rounded) (precise fields are same)
- 3rd party Mouse - Native GLFW:    UP: -0.1 to -~30   /    DOWN: +0.1 to +~30   (depends on wheeling velocity).
- 3rd party Mouse - Native GLFW: Sh+UP: -1   to -~30   / Sh+DOWN: +1 to +~30     (with SHIFT. all values becomes rounded)
- 3rd party Mouse - Safari SDL:     UP: -4   to -~600  /    DOWN: +4   to +~600  (depends on wheeling velocity).
- 3rd party Mouse - Safari SDL:  Sh+UP: +40  to +~600  / Sh+DOWN: -4   to -~600  (depends on wheeling velocity).
- 3rd party Mouse - Chrome SDL:     UP: -8   to -~1200 /    DOWN: +8   to +~1200 (depends on wheeling velocity).
- 3rd party Mouse - Chrome SDL:  Sh+UP: +80  to +~1200 / Sh+DOWN: -80  to -~1200 (depends on wheeling velocity).
- Laptop Touchpad - Native SDL:     UP: -1.0 to -~30   /    DOWN: +1.0 to +~30   (little/no smoothed inertia) (precise fields are more precise but lack of smoothing is strange)
- Laptop Touchpad - Native GLFW:    UP: -0.1 to -~20   /    DOWN: +0.1 to +~20   (with smoothed inertia).
- Laptop Touchpad - Safari SDL:     UP: -1   to -~30   /    DOWN: +1   to +~30   (with smoothed inertia).
- Laptop Touchpad - Chrome SDL:     UP: -2   to -~300  /    DOWN: +2   to +~300  (with smoothed inertia).

**From OSX: Horizontal Wheel/Swipe**
- Laptop Touchpad - Native SDL:   LEFT: +1.0 to +~30  / RIGHT: -1.0 to -~30  (little/no smoothed inertia).
- Laptop Touchpad - Native GLFW:  LEFT: -0.1 to +~20  / RIGHT: +1.0 to +~30  (with smoothed inertia).
- Laptop Touchpad - Safari SDL:   LEFT: +1.0 to +30   / RIGHT: -1.0 to -~30  (with smoothed inertia).
- Laptop Touchpad - Chrome SDL:   LEFT: +2.0 to +300  / RIGHT: -2.0 to -~300 (with smoothed inertia).
```

**Comment by topolarity** [comment] 2023-01-31 21:27
Are these data the raw value per event, or are they accumulated over a period of time?

I've seen that slow scrolls become heavily batched/under-sampled on some systems, so it's probably necessary to accumulate for an apples-to-apples comparison.

**Comment by ocornut** [comment] 2023-01-31 21:32
> Are these data the raw value per event, 

Per event.
(There is an accumulation done in our scrolling code for sub-pixel values.)

Notes:

- We should decide what sign should be a LEFT wheel/swipe and RIGHT wheel/swipe BEFORE deciding on a scroll direction. 
- Then we make backends and platform consistent.
- We should confirm if SHIFT+UP always means same sign as LEFT (table above suggests so).

About GLFW:

- GLFW+Emscripten (\*) somehow report wheel values opposite of SDL+Emscripten for Y axis.
- GLFW Horizontal Sign is indeed inconsistent between Native and Emscripten. 
(*\) built from a Windows machine, haven't tested building FROM OSX but I think would make no difference. But I'll double-check.

Note opening thread message:
> The horizontal scrolling direction in Dear ImGui with the Win32/SDL backends is backwards when compared to other Windows applications. It is correct with the imgui_impl_glfw backend. This issue is observable in the official examples. (I specifically tested example_glfw_opengl3, example_sdl_directx11, and example_win32_directx12.)

A per the scary table above, further notes:

- I think wheel up and swipe up should be standardized as positive values (and down as negative values) based on typical Windows machine behavior.
- Which means all backends should flip Y on OSX (undo natural scrolling setting), and core imgui does opposite flip in scrolling code (based on runtime boolean set based on natural scrolling setting) ? So when using a wheel to scroll on OSX, values are flipped twice, but this ensure the values in MouseWheel are consistent across platforms and backends.
- We expose a runtime value specifying the sign of scroll up and the sign of scroll down, which widgets (e.g. one performing Scrolling) can use. 

Question:
- Can someone using Unity or Unreal with access to both PC or Mac can confirm if there are widgets where you can edit e.g. an int or float with mouse wheel, and if the direction of change is swapped based on natural scrolling setting, aka if non-scrolling types of inputs relying on mouse wheel are also affected by the flip ?
- How about Zooming behavior?

**Comment by ocornut** [comment] 2023-01-31 21:41
FYI there's no action needed; other than the two questions above (for people who can run Unity or Unreal on two platforms).

I've gathered good data and will add more soon and then attempt some fixes for the horizontal direction issues.

**Comment by topolarity** [comment] 2023-01-31 21:41
> Per event.
> (There is an accumulation done in our scrolling code for sub-pixel values.)

Is it possible then that the event rates are different, in addition to the event scaling?

I'll dive in soon and try to reproduce some of your findings

**Comment by ocornut** [comment] 2023-02-01 20:45
I have pushed 3617a96 fixing most issues discussed here.

Remaining issues IHMO:
- The magnitude of wheel inputs under Emscripten (with SDL or GLFW backends) is still a problem which I have merely used a dumb scale factor for. We should continue this specific discussion in #6096.
- When running on Emscripten under OSX, Shift+WheelY with a mouse will be cancelled by our own handling of Shift+WheelY, this is because `io.ConfigMacOSXBehaviors` is not set. We should either disable Shift+WheelY support turning into WheelX on Emscripten, or find a way to detect an OSX client under OSX.

Attached my data converted to an Excel sheet. Please ignore above table as this sheet is more complete and more accurate.
**You can see the 4 fixes that have been done and why.**

[Wheeling Notes 2023-02-01.xlsx](https://github.com/ocornut/imgui/files/10561441/Wheeling.Notes.2023-02-01.xlsx)

Thank you !

**Closed by ocornut** 2023-02-01 20:45 UTC
Labels: backends, scrolling, inputs

**Comment by ocornut** [comment] 2023-02-01 23:17
Duh i also accidentally pushed a WIP example for GLFW+Emscripten which i didn’t intend to include in that commit (reason: somehow git stashes don’t stash new files unless staged). So expect that to be removed or massaged later, perhaps folded into existing examples.

**Comment by PathogenDavid** [comment] 2023-02-09 10:31
> git stashes don’t stash new files unless staged

You can use `--include-untracked`/`-u` with `git stash save`/`push` to include them. (I also hate the default behavior.)
