### ISSUE TITLE
Crash while resizing docked windows when one of the windows is not visible.

### ISSUE THREAD

**Issue by Myszkoj** [ocornut/imgui#3328] opened 2020-06-30 12:54 UTC
Hi! I keep getting this assertion:
![crash_006](https://user-images.githubusercontent.com/9519504/86126813-394c5a80-badf-11ea-8bde-14af190674fc.jpg)

I made this example to show when this happes:
![docking problem](https://user-images.githubusercontent.com/9519504/86126720-19b53200-badf-11ea-95b6-49e15fca5561.gif)

At first i thought i messed up something in the code, but i managed to reproduce this crash in your Demo -> Examples -> Documents:
![crash_007](https://user-images.githubusercontent.com/9519504/86127896-e70c3900-bae0-11ea-9ff8-8cc43086bde5.jpg)
![crash_008](https://user-images.githubusercontent.com/9519504/86127421-1ff7de00-bae0-11ea-87ae-0d1dbbbb058f.jpg)

In this example I have docked 3 windows, one after another (Eggplant, Lettuce, Carrot), then I closed the Lettuce window and moved splitter towards the Eggplant, after this I reopened the Lettuce window and the same crash appeared again.
 
I downloaded imgui-docking.zip on 24th of June 2020.

**Comment by ocornut** [comment] 2020-06-30 14:53
Thanks for the report, confirmed.
I have I have a fix/branch somewhere where I was working on it, will investigate.

**Comment by ocornut** [comment] 2020-06-30 16:58
Pushed a fix I had in another branch. 
Since there's not enough space for both windows in that small node it'll look weird but it's easy to recover it by resizing.

I'm working on toolbar usage patterns which requires nodes pushing back for the size they need, and it may lead further related changes.

**Closed by ocornut** 2020-06-30 16:58 UTC
Labels: bug, docking
