### ISSUE TITLE
Visualize real-time images from depth cameras in imgui interface?

### ISSUE THREAD

**Issue by Vibek** [ocornut/imgui#1462] opened 2017-11-27 14:49 UTC
Hello,
I am newbie and just started using imgui. I am wondering, if it is possible to show the real-time streaming images from the depth camera in imgui. I already design interface, which shows all the graphs, plots and so on. But wondering is it possible to show real-time images also. 
I am tried to avoid several windows, thus working on imgui to design an interface which can show all the tasks in one window.
Thanks.:)

**Comment by ocornut** [comment] 2017-11-27 14:51
Closing as duplicate of your question in #813 (now answered). Please read documentation and check examples.

**Closed by ocornut** 2017-11-27 14:51 UTC
