### ISSUE TITLE
Docking branch: last focused tab doesn't persist

### ISSUE THREAD

**Issue by richardeakin** [ocornut/imgui#2507] opened 2019-04-20 22:40 UTC
**Version/Branch of Dear ImGui:**

Version: 20f0cb02816832644a5e05b0909e3fad71355e3d
Branch: docking

**Back-end/Renderer/Compiler/OS**

example_glfw_opengl3, Win 10 / Visual Studio 2019

**My Issue/Question:**

Should the last tab I selected in a tab group persist once I have closed the app and reopened? I believe from [this post](https://github.com/ocornut/imgui/issues/2109#issuecomment-425974856) that it is meant to.

Steps I took:
1) run example_glfw_opengl3
2) drag the "Hello, World!" window into the "ImGui Demo" window so they are tabbed and "Hello, World!" is visible / selected.
3) select "ImGui Demo" tab so it is visible.
4) Close the app with the X button
5) Re-run

I then see the "Hello, World!" tab, whereas I expected to see the "ImGui Demo" tab.

Thanks for such an awesome UI tool! Use it every day, you're a champ.

**Comment by ocornut** [comment] 2019-04-21 22:01
Hello,

You are correct that the linked post incorrectly stated that this was restored, it is currently not (edited the post). This is however quite desirable. See lower posts of #2304 for an explanation. The general feature isn't tied to Docking in particular and isn't trivial to handle without bugs, but it might be simpler to just implement the docking subset of it.

**Comment by richardeakin** [comment] 2019-04-24 16:36
Ah I see, thanks for the update, indeed seems like a duplicate of #2304.

Is there a way I can force what tab appears at startup? Either by editing the .ini file or in C++. I was hoping to be able to hand off a project to other non-developers with the windows they'd like to use already visible.

**Comment by ocornut** [comment] 2019-04-24 17:18
As a temporary workaround, you can call FocusWindow() after submitting your windows once.

**Comment by ocornut** [comment] 2020-03-09 13:05
Closing as duplicate of #2304 (still unsolved).

**Closed by ocornut** 2020-03-09 13:05 UTC
Labels: docking, focus, settings
