### ISSUE TITLE
Append text to InputTextMultiline

### ISSUE THREAD

**Issue by AndroTwrpid** [ocornut/imgui#4627] opened 2021-10-04 11:37 UTC
Hello, is possible to append data to InputTextMultiline?
I'm new to imgui

**Comment by rokups** [comment] 2021-10-04 13:51
Append text to a buffer InputTextMultiline() uses. New text will show up if widget is inactive.

Also please follow issue template. It is there for a reason, and that reason is not to be ignored.

**Comment by ocornut** [comment] 2021-10-04 16:32
Closing as duplicate of #3878, #2881
This is an open problem.

**Closed by ocornut** 2021-10-04 16:32 UTC
Labels: inputtext
