### ISSUE TITLE
Docking operation resets the background color of attached sub windows

### ISSUE THREAD

**Issue by EssenWorkbench** [ocornut/imgui#4101] opened 2021-05-05 09:45 UTC
**Version/Branch of Dear ImGui:**

Version: v1.83 WIP
Branch: v1.83 WIP_(docking)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx12.cpp
Compiler: Visual Studio 2017
Operating System: Windows 10

**My Issue/Question:**

Docking operation change the background color of sub window

**Screenshots/Video**

[ before docking ]
![image](https://user-images.githubusercontent.com/3712295/117122721-043a1580-ad4b-11eb-8a3d-d9fd51fd222b.png)

[while docking ]
![image](https://user-images.githubusercontent.com/3712295/117122901-39466800-ad4b-11eb-8e71-9088bae6cae2.png)

[after docking ]
![image](https://user-images.githubusercontent.com/3712295/117122972-4c593800-ad4b-11eb-89a3-effc7ced11f4.png)

// snippet code to create the sub window & set the background color
        const ImU32 color =
            root_node_id_ != -1 ? evaluate(graph_, root_node_id_) : IM_COL32(255, 20, 147, 255);
        ImGui::PushStyleColor(ImGuiCol_WindowBg, color);
        ImGui::Begin("output color");
        ImGui::End();
        ImGui::PopStyleColor();

**Comment by ocornut** [comment] 2021-05-05 10:29
Hello,

Closing as duplicate of #2700
See in particular my recent post: https://github.com/ocornut/imgui/issues/2700#issuecomment-762851523

I've got an "almost working" version of it but it's not easy to fix the edge cases and they would lead to flickering (no background at all for 1-2 frames) in some cases.

Further comments are best posted in #2700. Thank you!

**Closed by ocornut** 2021-05-05 10:29 UTC
Labels: docking, style
