### ISSUE TITLE
Compiling files from tabs's branch v1.655

### ISSUE THREAD

**Issue by Bonicx** [ocornut/imgui#2091] opened 2018-09-18 09:43 UTC
Hi I have a problem with the tab branch's file compiling in visual studio 2017.
Is there anyway to resolve these errors?
![111](https://user-images.githubusercontent.com/32429706/45678965-25ce3a80-bb6a-11e8-993f-f99da049f0a4.png)

**Version/Branch of Dear ImGui:**

v1.65

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_opengl3.cpp
OS: Windows 10
Compiler: VS2017

**Comment by ocornut** [comment] 2018-09-18 15:03
This is not really related to the Tabs branch neither to the imgui_impl_opengl3.cpp
If you are trying to compile the example_glfw_opengl3/ example (I am guessing, but you are not specifying which example you are compiling) it is linking with a precompiled copy of GLFW which might not work with newer VS2017. 

You can google this error, or replace GLFW with our own versions or binary. 

Will have to rework the example to provide a copy of GLFW binaries that works with 2017 or some other workaround, I haven't looked into it yet.

See #2010.

Please note that the `Tabs` branch will be discontinued soon as we will be transitioning to the Docking branch.

**Comment by ocornut** [comment] 2018-09-20 08:42
Also see #2043.

**Comment by ocornut** [comment] 2018-11-05 16:32
This should be fixed now. The problem is that linking VS2010 binaries into recent VS applications needs `legacy_stdio_definitions.lib`, and we provide an old GLFW3.lib binary to ease compiling those examples out of the box. We are using a pragma to link with this in the main.cpp of the GLFW examples.

**Closed by ocornut** 2018-11-05 16:32 UTC
Labels: backend/binding, build tools
