### ISSUE TITLE
SDL2 w/ SDL_Renderer and multiple windows?

### ISSUE THREAD

**Issue by dacobi** [ocornut/imgui#6975] opened 2023-11-02 09:57 UTC
I'm working on a program where I'd like to add the ability to have multiple windows.
Each window will be created by SDL2 and has to have a SDL_Renderer and an ImGui MainMenu and windows.
Would I have to manually create a new ImGui context for each window or is it something that can be done with the docking branch?

**Comment by ocornut** [comment] 2023-11-02 10:22
Hello Dacobi, 
This should normally be posted in Issues.

Our the SDL_Renderer backend currently doesn't support multi-viewports.
See this thread #5835
The main underlying reason is SDL_Renderer API doesn't allow for texture sharing in multiple context.
It should be a relatively easy thing to add to SDL, someone open an issue:
https://github.com/libsdl-org/SDL/issues/6742
But I am afraid it hasn't been very visible. May be a good idea to post to the SDL issue.

**Comment by dacobi** [comment] 2023-11-02 10:35
Thanks for your reply

I'm not sure I understand entirely.
I see that multi viewports aren't supported with SDL_Renderer backend, but my program doesn't need to share SDL textures between windows/SDL_Renderers. Would I still be able to hack it by manually creating a new ImGui context for each window?

**Comment by ocornut** [comment] 2023-11-02 10:59
> Would I still be able to hack it by manually creating a new ImGui context for each window?

Yes that would work. Create multiple imgui context and set the current context accordingly. Backends data should be stored inside each active context.

**Comment by ocornut** [comment] 2024-01-09 15:16
Closing as duplicate of #5835

**Closed by ocornut** 2024-01-09 15:16 UTC
Labels: backends, multi-contexts
