### ISSUE TITLE
Style borders

### ISSUE THREAD

**Issue by Shadowblitz16** [ocornut/imgui#1535] opened 2018-01-04 21:18 UTC
hello I have another question. this one about skinning imgui by drawing lines across the widgets

is it possible to turn something like this...
![unskinned](https://user-images.githubusercontent.com/2453707/34584464-b0e6e85e-f150-11e7-9fad-f9f4a4881075.png)

into something like this..
![skinned](https://user-images.githubusercontent.com/2453707/34584471-b9dfedf2-f150-11e7-8aa4-3cc32d20caf9.png)

by drawing lines over the widgets?

if not this could be an alternative to allowing people to use images for skinning since it only requires something like..

ImGui::PushStyleRect(int x1, int y1, int x2, int y2, bool outline, int color, int hovercolor, int activecolor)
imGui::PopStyleRect()

**Comment by ocornut** [comment] 2018-01-05 00:02
Have you looked at FrameBorderSize, ImGuiCol_Border, ImGuiCol_BorderShadow ?

Right now that’s all there is available.

**Comment by Shadowblitz16** [comment] 2018-01-05 01:39
no I haven't but I will take a look thankyou

**Comment by Shadowblitz16** [comment] 2018-01-05 04:53
ok so i seems borders are what I want but is there a way to use these on the titlebar, menubar, and window?

**Comment by ocornut** [comment] 2018-01-05 08:55
Have you looked at the style structure and the demo code and style editor?

**Comment by ocornut** [comment] 2018-01-05 09:56
I agree in principle but this won't be added until the style system is refactored, and I have no ETA for it.
Some notes on similar topics here:
https://github.com/ocornut/imgui/issues/447

Dear ImGui is for tools and not designed to be styled very much.

**Comment by ocornut** [comment] 2018-01-05 09:57
I'll close it as duplicate of the ideas discussed in #447, will do eventually.

**Closed by ocornut** 2018-01-05 09:57 UTC
Labels: style
