### ISSUE TITLE
Example linker error with precompiled glfw3.lib and VS2015

### ISSUE THREAD

**Issue by siddharthcmdz** [ocornut/imgui#2043] opened 2018-08-25 22:06 UTC
Hi,

I use windows 10, visual studio 2015. I get a linker error when i build the examples. The failures are in example_glfw_opengl2/3:

> 1>glfw3.lib(context.obj) : warning LNK4217: locally defined symbol sscanf imported in function parseVersionString
> 1>MSVCRTD.lib(vsnprintf.obj) : warning LNK4049: locally defined symbol _vsnprintf imported
> 1>glfw3.lib(init.obj) : error LNK2019: unresolved external symbol __imp_vsnprintf referenced in function _glfwInputError
> 1>MSVCRTD.lib(vsnprintf.obj) : error LNK2001: unresolved external symbol __imp_vsnprintf
> 1>C:\imgui\examples\example_glfw_opengl3\Debug\example_glfw_opengl3.exe : fatal error LNK1120: 1 unresolved externals
> 

This happens when the platform toolset is Visual Studio 2015(v140). However, there is no build errors when i change the toolset to Visual Studio 2012 (v110).

[Edit] Just forgot to mention, the visual studio configuration used is Debug x64.

Any suggestions here?

**Comment by tienery** [comment] 2018-08-26 14:46
I have this problem earlier myself. Try adding "legacy_stdio_definitions.lib" to your library dependencies in the bat file.

**Comment by ocornut** [comment] 2018-11-05 16:32
This should be fixed now. As pointed by @tienery, the problem is that linking VS2010 binaries into recent VS applications needs `legacy_stdio_definitions.lib`, and we provide an old GLFW3.lib binary to ease compiling those examples out of the box. We are using a pragma to link with this in the main.cpp of the GLFW examples.

**Closed by ocornut** 2018-11-05 16:32 UTC
Labels: backend/binding, build tools

**Comment by ESP0xA** [comment] 2021-03-21 04:14
Verified. This is helpful, thnx a lot.
