### ISSUE TITLE
The Menu Bar Can't Display Correctly

### ISSUE THREAD

**Issue by gghyoo** [ocornut/imgui#1376] opened 2017-10-17 13:08 UTC
![image](https://user-images.githubusercontent.com/7220499/31666494-09aa74b6-b37f-11e7-976f-ee16370bd056.png)

In Windows 10 （New Release Version），The Menu Bar Can't Display Correctly. This Also Happened in the Demo Example. 

Using imgui_impl_glfw.cpp (OpenGL2)

**Comment by gghyoo** [comment] 2017-10-17 13:11
The display is correct in older win10 version, But someday After I Upgrade my os, the dispaly change to not correct.

**Comment by ocornut** [comment] 2017-10-17 13:16
Can you provide a screenshot/video of what happens with the unmodified demo example?

**Comment by ocornut** [comment] 2018-04-23 12:37
@gghyoo Any update on this? Which video card are you using? Does updating the video driver makes any difference? What's are your screen resolution and windows DPI setting?

**Comment by ocornut** [comment] 2018-04-23 12:44
Closing as duplicate of #1421, it appears to be a Intel driver issue? Also see https://github.com/glfw/glfw/issues/1069

**Closed by ocornut** 2018-04-23 12:44 UTC
Labels: backend/binding
