### ISSUE TITLE
Align icons glyphs or Align text

### ISSUE THREAD

**Issue by madeso** [ocornut/imgui#1869] opened 2018-06-08 07:42 UTC
**Version/Branch of Dear ImGui:**

About 1 week old master (948009a8)

**Back-end file/Renderer/OS:**

Slightly modified imgui_impl_sdl_gl3.h (changed imgui and opengl include paths)

**My Issue/Question:**

I want to align the texts/center the icons in this popup:

![image](https://user-images.githubusercontent.com/1352934/41143859-32ef2cfc-6afb-11e8-89cd-a9e2d22ca28c.png)

``` cpp
if(ImGui::BeginPopup("Example Bug"))
{
  // defined somewhere else
  // static bool enabled1 = true;
  // static bool enabled2 = true;
  const char* text1    = ICON_FK_ARROWS_H " New Horizontal divider";
  const char* text2    = ICON_FK_ARROWS_V " New Vertical divider";

  if(enabled1) ImGui::Selectable(text1);
  else ImGui::Text(text1);

  if(enabled2) ImGui::Selectable(text2);
  else ImGui::Text(text2);
  ImGui::EndPopup();
}
```

The current workaround is to add spaces before and after the icon, to align the text, so one possible, but hacky solution would be to add a min_glyph_width to the ImFontConfig struct when loading the font.

**Comment by ocornut** [comment] 2018-06-08 07:49
At the user level, you may split your text rendering in two steps:

```
ImGui::Text(icon)
ImGui::SameLine(position)
ImGui::Text(description)
```

That will also.

> one possible, but hacky solution would be to add a min_glyph_width to the ImFontConfig struct when loading the font.

I agree, been meaning to add an option like that for merging icon fonts as it is a common problem. Will probably add this feature soon. To not add additional absolute size into `ImFontConfig`, I wonder if this option should be specified as a ratio of the font height? Maybe a little weird..

**Comment by ocornut** [comment] 2018-06-08 10:50
I pushed a branch `font_min_max_advance` with the feature, if you'd like to test it.
There are both Min and Max settings, allowing to force a font to be monospaced.
When the AdvanceX value for a given glyph is adjusted, the code offset the glyphs by half that amount to recenter it. This is possibly subject to tweaks or additional options (feedback welcome).

```
ImGui::Text(ICON_FA_ARROWS_H " New Horizontal divider");
ImGui::Text(ICON_FA_ARROWS_V " New Vertical divider");
```

![image](https://user-images.githubusercontent.com/8225057/41154354-35a5aa38-6b1a-11e8-819a-4125ad198103.png)

```
void DebugLoadFontAwesome4()
{
    ImGuiIO& io = ImGui::GetIO();
    io.Fonts->AddFontDefault();

    ImFontConfig cfg;
    cfg.MergeMode = true;
    cfg.GlyphMinAdvanceX = 14.0f;
    static const ImWchar icon_ranges[] = { ICON_MIN_FA, ICON_MAX_FA, 0 };
    io.Fonts->AddFontFromFileTTF("../../../imgui-wip/fonts/fontawesome-webfont.ttf", 14.0f, &cfg, icon_ranges);
}
```

**Comment by madeso** [comment] 2018-06-08 11:53
I saw it, the diff looks awesome, added a calender reminder, will try it when I get back from work in about 5-6 hours.

Not sure about the SameLine() solution though, as that will create 2 seperate widgets, and hence decrease the active region of the selectable, right?

**Comment by ocornut** [comment] 2018-06-08 11:56
Selectable by default uses the entire available width for hit testing:
```
ImGui::Selectable("Hello");
ImGui::SameLine();
ImGui::Text("Blah");
```

![image](https://user-images.githubusercontent.com/8225057/41156782-99bf043e-6b23-11e8-8f92-731029716e00.png)

**Comment by codecat** [comment] 2018-06-08 16:00
This works great! :tada:

![](https://4o4.nl/20180608gpqJfeZs.png)

![](https://4o4.nl/20180608LVmUrn16.png)

**Comment by madeso** [comment] 2018-06-08 18:42
I couldn't get SameLine() solution lines to sync up, but the min_max_advance branch works perfectly.

**Comment by codecat** [comment] 2018-06-10 09:50
Will this be merged soon? Seems like a small enough feature to merge?

**Comment by dougbinks** [comment] 2018-06-10 10:47
I've just tried this branch and it works extremely well for us. We no longer need to add tabs or manually position content. Many thanks!

**Comment by ocornut** [comment] 2018-06-10 13:07
Merged. Thanks @madeso @codecat @dougbinks for the confirmation!

**Closed by ocornut** 2018-06-10 13:07 UTC
Labels: font/text

**Comment by vikram-lodhi** [comment] 2023-02-20 13:50
```
static const ImWchar icons_ranges[] = {ICON_MIN_FA, ICON_MAX_16_FA, 0};
void AddFonts() {
    ImGuiIO &io = ImGui::GetIO();
    io.Fonts->AddFontDefault();
    ImFontConfig icons_config;
    icons_config.MergeMode = true;
    icons_config.PixelSnapH = true;
    icons_config.GlyphMinAdvanceX = 16.0f;

    io.Fonts->AddFontFromFileTTF(FONT_ICON_FILE_NAME_FAS, 16.0f, &icons_config, icons_ranges);
}
```
Font File from `https://github.com/FortAwesome/Font-Awesome/blob/5.x/webfonts/fa-solid-900.ttf`

I am using latest push of `Docking` branch

![image](https://user-images.githubusercontent.com/123872971/220125129-5cce3400-02b9-4aae-91d3-d0a3acd85510.png)

[IconFontCppHeaders](https://github.com/juliettef/IconFontCppHeaders)
I am using given API to load Icon

```
if (ImGui::Button(ICON_FA_MINUS_SQUARE " Remove Parameter")) { }
ImGui::SameLine();
if (ImGui::Button(ICON_FA_SAVE " Save Config")) {}
```

How can i align icon?

**Comment by dougbinks** [comment] 2023-02-20 15:09
Hi @vikram-lodhi,

We have found that font awesome fonts need to have their sizes reduced by `2.0f/3.0f` in order to align correctly.

The default font (which it looks like you are using) has a fontsize of 13.0f. So something like this might work well for you:

```C
baseFontSize = 13.0f;
icons_config.GlyphMinAdvanceX = baseFontSize * 2.0f/3.0f;
io.Fonts->AddFontFromFileTTF(FONT_ICON_FILE_NAME_FAS,  baseFontSize * 2.0f/3.0f, &icons_config, icons_ranges);
```

I should update the readme at https://github.com/juliettef/IconFontCppHeaders to mention this.

**Comment by juliettef** [comment] 2023-02-20 16:20
FYI updated the [IconFontCppHeaders readme example code](https://github.com/juliettef/IconFontCppHeaders#example-code).

**Comment by ron3545** [comment] 2023-12-07 15:53
So I' currently using the latest version of the docking branch. 

I'm trying to add icon on a button, but the problem is that the icon and the text are not aligned together. Additionally, is it possible to have the same font size for both the icon and the text?
here is what I've got:
![image](https://github.com/ocornut/imgui/assets/86136180/cb743e8f-38a5-4ecc-92ff-50ebdc1f08ac)

```
ImGui::CreateContext();
ImGuiIO& io = ImGui::GetIO(); 
io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;     // Enable Keyboard Controls
io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;         // Enable Docking
io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;       // Enable Multi-Viewport / Platform Windows
io.IniFilename = NULL;
//io.DisplaySize = ImVec2(1280, 720) / io.DisplayFramebufferScale;
io.Fonts->AddFontDefault();

float iconFontSize = 18 * 4.0f / 3.0f; 
static const ImWchar icons_ranges_CI[] = { ICON_MIN_CI, ICON_MAX_CI, 0 };
static const ImWchar icons_ranges_MDI[] = { ICON_MIN_MDI, ICON_MAX_MDI, 0 };

ImFontConfig icons_config; 
icons_config.MergeMode = true; 
icons_config.GlyphMinAdvanceX = iconFontSize;

ICFont = io.Fonts->AddFontFromFileTTF( FONT_ICON_FILE_NAME_CI, iconFontSize, &icons_config, icons_ranges_CI );
IMDIFont = io.Fonts->AddFontFromFileTTF( FONT_ICON_FILE_NAME_MDI, iconFontSize, &icons_config, icons_ranges_MDI); 

const char* button_names[] = {ICON_CI_NEW_FILE " New File...", ICON_CI_ADD " Open File...",  "Open Folder...",  "Clone Git Repository..."};


// in imgui window somewhere
ImGui::PushFont(ICFont);
      if(ImGui::Button(button_names[i]))
      {
          
      }
ImGui::PopFont();
```

Font file from `https://github.com/microsoft/vscode-codicons/blob/main/dist/codicon.ttf`

**Comment by ocornut** [comment] 2023-12-07 15:56
You are loading your icons font with size 24 (18 * 4 / 3) whereas `AddFontDefault()` by default load a font of size 13.
You'll need to have the size to roughly match.

You don't need to use `PushFont()` if the fonts are merged together.

**Comment by ron3545** [comment] 2023-12-07 16:11
How can the discrepancy in font sizes, specifically loading the icons font with a size of 24 (calculated as 18 * 4 / 3), while the default font loaded by AddFontDefault() is of size 13, be addressed to ensure that the sizes roughly match? Additionally, I've attempted to remove AddFontDefault(), but encountered an error when trying to use MergeMode from ImFontConfig. How can this issue be resolved while maintaining compatibility with MergeMode?
![image](https://github.com/ocornut/imgui/assets/86136180/e7fb516a-49be-403c-9600-640769a8fd2b)

**Comment by ocornut** [comment] 2023-12-07 16:24
>  be addressed to ensure that the sizes roughly match

Load the icon font with a size of 13 or the default font with a size of 24...

> Additionally, I've attempted to remove AddFontDefault(), but encountered an error when trying to use MergeMode from ImFontConfig. How can this issue be resolved while maintaining compatibility with MergeMode?

You can pass a `ImFontConfig` value to AddFont:
```
ImFontConfig cfg;
cfg.SizePixels = 24.0f;
ImGui::AddFontDefault(&cfg);
```
