### ISSUE TITLE
[win32] Standard shortcuts stop working in input widgets

### ISSUE THREAD

**Issue by crackedmind** [ocornut/imgui#2976] opened 2020-01-11 09:52 UTC
**Version/Branch of Dear ImGui:**

Version: `1.75 WIP (17401)`
Branch: master and docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp and imgui_impl_glfw.cpp
Operating System: Windows 10 1909

**My Issue/Question:**
Standard ctrl based hotkeys for input widgets stop working after using some windows/keysuper system shortcuts like win+space (change input language) and win+v (clipboard history, appeared in Windows 10 1809). It stops working until window reactivation. 

Problem is here:
https://github.com/ocornut/imgui/blob/f03c00bc89c4ba9b45f4e216d943e1d890dfbac0/examples/imgui_impl_glfw.cpp#L124
https://github.com/ocornut/imgui/blob/f03c00bc89c4ba9b45f4e216d943e1d890dfbac0/examples/imgui_impl_sdl.cpp#L118

And when we pressed: win-space, then ctrl-z. we got is_shortcut_key == false, because io.KeySuper ==1 and io.KeyCtrl also equals to 1.

https://github.com/ocornut/imgui/blob/f03c00bc89c4ba9b45f4e216d943e1d890dfbac0/imgui_widgets.cpp#L3671

I don't know why KeySuper state not clears after KEYUP event. As workaround i use `#ifndef _WIN32` guard

In pure win32 backend io.KeySuper always sets to false.
https://github.com/ocornut/imgui/blob/f03c00bc89c4ba9b45f4e216d943e1d890dfbac0/examples/imgui_impl_win32.cpp#L223

**Standalone, minimal, complete and verifiable example:** 
Just open Demo window in default sdl/glfw examples and go to Multi-line text widget example.

**Comment by ocornut** [comment] 2020-01-11 16:59
Thank you for the report. This is the first time I use Win+V I didn't even know this feature existed.

So it looks like there are multiple issues at end:

(1) Investigate why SDL and GLFW don't correctly report when the `Super/GUI` key is released. I tested with GLFW and confirmed that KeySuper was stuck after releasing it after a Win+V.

In this screenshot the Win+V ui is open, and the Windows key has been released already and it's still reported as pressed: (note that text appearing in the OS UI on the top-right is just my clipboard history!).

![Image1](https://user-images.githubusercontent.com/8225057/72207582-d9afb380-349a-11ea-813e-7082e34d870e.png)

This is essentially similar to #2062 in essence.

(2) Investigate if we could expose the `Super` key in imgui_impl_win32.cpp, when I looked it wasn't obvious to me how to read that key.

----

My intuition is the following:
- The "Windows key" is not really properly usable for user applications under Win32, and because of this neither SDL nor GLFW have worked out nice workarounds to catch when it has been released. 
- Maybe we easily prove that both SDL and GLFW have a bug and possibly aim to report and fix it there.
- If that's the case, since this is a key that's difficult to even access/use under Windos, my suggested answer for both 1 and 2 is simply to not forward the key in the SDL and GLFW backup when running on Windows (so simply #ifdef that section out of both back-ends).

In fact that later option we should apply right now, since that's the immediate best fix we have, while we investigate SDL/GLFW further.

**Comment by rokups** [comment] 2020-01-13 13:44
Reason for this happening is that `WM_KEYUP` is not sent for `Super` keys upon release in _some_ cases. This explains why both GLFW and SDL have same issue - it is win32 problem. Both libraries would require a workaround for this quirk. This conclusion is based on testing win32_dx11 example.

A workaround:
```cpp
    io.KeysDown[VK_LWIN] &= (::GetKeyState(VK_LWIN) & 0x8000) != 0;
    io.KeysDown[VK_RWIN] &= (::GetKeyState(VK_RWIN) & 0x8000) != 0;
    io.KeySuper = io.KeysDown[VK_LWIN] || io.KeysDown[VK_RWIN];
```

This clears keys in stuck state manually. Bonus: it also implements `Super` modifier.

**Comment by rokups** [comment] 2020-01-16 13:20
This will be fixed in next GLFW release.

**Comment by ocornut** [comment] 2020-01-17 14:00
Closing this as a non-dear imgui issue, reported to GLFW and SDL and fixed in GLFW. Thanks Stanislav and Rokups.

**Closed by ocornut** 2020-01-17 14:00 UTC
Labels: backend/binding, inputs
