### ISSUE TITLE
Is it possible to add ViewportSideBar into an ImGui Window?

### ISSUE THREAD

**Issue by LightShade12** [ocornut/imgui#6592] opened 2023-07-10 08:45 UTC
Version/Branch of Dear ImGui:
Version: 1.89.7
Branch: docking

Back-end/Renderer/Compiler/OS:
Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Operating System: Windows 10

My Issue/Question:
How can I add a "ImGui::BeginViewportSideBar" into an imgui window? My current code:

```
	ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
	ImGui::Begin("Viewport");
	if (ImGui::BeginViewportSideBar("##ViewportStatusBar", NULL, ImGuiDir_Down, ImGui::GetFrameHeight(), m_windowflags)) {
		if (ImGui::BeginMenuBar()) {
			ImGui::Text("ViewportStatus");
			ImGui::EndMenuBar();
		}
	};
	m_viewportWidth = ImGui::GetContentRegionAvail().x;
	m_viewportHeight = ImGui::GetContentRegionAvail().y;

	auto image = m_Renderer.GetFinalImage();
	if (image)
		ImGui::Image((void*)image->GetGLTexID(), ImVec2(image->GetWidth(), image->GetHeight()), { 0,1 }, { 1,0 });
	ImGui::End();

	ImGui::PopStyleVar();
```
with flags:

`ImGuiWindowFlags m_windowflags = ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoNavFocus;`

results in: 
![image](https://github.com/ocornut/imgui/assets/102753608/2e16ef54-1ba4-41f5-9eee-5754468f27f4)

Is it possible to only limit the viewport status bar in the "viewport" window?

**Comment by ocornut** [comment] 2023-07-10 10:06
No. It's called `BeginViewportSidebar()` because it applies to a Viewport not a Window.
This is the same as #5038, #3518 so I will close this as duplicate.

Some of the work for #3692 was intended to make this easier to do, so this is planned, but you can currently use some of the workaround suggested in the other linked issues, e.g. use a manually sized `BeginChild()` window.

**Closed by ocornut** 2023-07-10 10:06 UTC

**Comment by LightShade12** [comment] 2023-07-12 04:16
Thank you it worked. Here's the snippet for the bottom bar for others:
```
ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
	ImGui::Begin("Viewport");

	m_viewportWidth = ImGui::GetContentRegionAvail().x;
	m_viewportHeight = ImGui::GetContentRegionAvail().y-22;

	auto image = m_Renderer.GetFinalImage();
	if (image)
		ImGui::Image((void*)image->GetGLTexID(), ImVec2(image->GetWidth(), image->GetHeight()), { 0,1 }, { 1,0 });
	//ImGui::SetCursorScreenPos({ ImGui::GetCursorScreenPos().x,ImGui::GetCursorScreenPos().y+ImGui::GetContentRegionAvail().y / 2});
	ImGui::BeginChild("statusbar", ImVec2(ImGui::GetContentRegionAvail().x, 19.0f));
	ImGui::Text("Samples:%d", m_Renderer.GetSampleCount()); ImGui::SameLine();
	ImGui::Text("/%d", m_Renderer.GetSettings().MaxSamplesLimit);
	ImGui::EndChild();
	ImGui::End();

	ImGui::PopStyleVar();
```
![image](https://github.com/ocornut/imgui/assets/102753608/eb581d9d-4156-4744-b5c2-8695746bb5a4)
