### ISSUE TITLE
A window which is no longer being submitted causes docked sibling to appear docked

### ISSUE THREAD

**Issue by PathogenDavid** [ocornut/imgui#4904] opened 2022-01-13 16:59 UTC
**Version/Branch of Dear ImGui:**

Version: 1.87 WIP 
Branch: docking acfc7798fdbab692b8fa855c7dd4ec43bc0bd828 (Latest as of today)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC 19.31.30919 (Visual Studio 2022 17.1.0p2)
Operating System: Windows 10 21H2

**My Issue/Question:**

If you dock two windows together and stop submitting one of them, the other will still appear docked even though from the user's perspective it isn't docked with anything.

**Screenshots/Video**

See below.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

This issue is reproducible in the official `example_glfw_opengl3` without modification.

1. Launch the demo. Check `Another Window` to show the other example window.

![image](https://user-images.githubusercontent.com/278957/149373170-a5726efc-ced1-4759-b059-570f50d202ac.png)

2. Dock `Another Window` into the demo window

![image](https://user-images.githubusercontent.com/278957/149373234-f64e6166-239a-4728-86be-9ac3f6a6c890.png)

3. Uncheck `Another Window` and observe the demo window still has a tab bar as if it were still docked:

![image](https://user-images.githubusercontent.com/278957/149373366-cdf4a5f3-1522-4d89-a17f-4d93d1f30d4b.png)

**Comment by ocornut** [comment] 2022-01-13 17:06
This is a known issue, one of the many current artifacts of the docking system (which I'd like to resolve but probably won't before Docking V3).
Other issues are listed there: https://github.com/ocornut/imgui/issues/2386#issuecomment-467610076

**Comment by PathogenDavid** [comment] 2022-01-13 17:18
Apologies, I looked for an issue but didn't find that one. (Although I think I probably would've overlooked that one even if I did.)

Feel free to close this if you don't need the separate tracking.

**Comment by ocornut** [comment] 2022-01-13 17:47
>  (Although I think I probably would've overlooked that one even if I did.)

Yes sorry was misleading didn't mean to suggest that the linked issue explicitly talked about that, but it list the OTHER ISSUES caused by those "single floating window with a tab-bar" thing.

Interestingly, some people explicitly want this tab bar at all time because it makes things more consistent, and there's a `io.ConfigDockingAlwaysTabBar` configuration flag for it. But the regressions caused by them tend to currently not be worth it.

I'm going to cop-out and close this because it's a rather glaring known issue of Docking and I don't want to see it in my face this now, and will definitively be addressed in the rewrite.

**Closed by ocornut** 2022-01-13 17:47 UTC
Labels: docking
