### ISSUE TITLE
Scroll jitter Glitch

### ISSUE THREAD

**Issue by enchanty** [ocornut/imgui#3708] opened 2021-01-10 21:43 UTC
![VID-20210111-WA0000](https://user-images.githubusercontent.com/71351988/104136191-b0737d00-53a5-11eb-88e6-dbe7c808ea0c.gif)

How I fix this scrolling jitter glitch?

**Comment by ocornut** [comment] 2021-01-10 21:55
We’d need a version number and precise repro to investigate. This looks like some code has varying height depending on clipping state, which shouldn’t happen at least not in the demo.

**Comment by ocornut** [comment] 2021-01-11 15:37
Going to close this as I cannot reproduce, it's missing information anyway and the GIF suggest using an old version.
If there is indeed a bug in the current version please post details here and I'll be happy to reopen and look into it but right now we're missing information to act on.

**Closed by ocornut** 2021-01-11 15:37 UTC
Labels: scrolling

**Comment by enchanty** [comment] 2021-01-12 13:09
My version number is 1.79 WIP and yes I have a resized checkbox and whenever I scroll this error happens

**Comment by ocornut** [comment] 2021-01-12 13:32
> yes I have a resized checkbox a

Can you clarify? I don't understand what you mean here.
Can you provide an explanation of to how to make it happens, or record a video of it happening from the start of the application?

**Comment by enchanty** [comment] 2021-01-12 14:30
If the normal checkbox size of the example is 5, mine is 10 (I made this resizing for experimentation but I got a scroll error like this)

**Comment by ocornut** [comment] 2021-01-12 14:41
I do not understand your explanation.

If you modified widgets code maybe you made a mistake in your mod.

If the bug happens without this please explain how to repro it. Right now you are being vague.

**Comment by enchanty** [comment] 2021-01-12 17:35
As you said there is no problem with the demo, I made a manipulation on the widget, because I set a size above the default size, when this item appears in the menu, the scroll reacts in this way.

**Comment by ocornut** [comment] 2021-01-12 17:56
Then,
Your question being "How I fix this scrolling jitter glitch?" if you want an answer you'll need to provide more details.

**Comment by enchanty** [comment] 2021-01-12 18:19
the detail you want from me Checkbox size?

**Comment by PathogenDavid** [comment] 2021-01-12 18:25
> the detail you want from me Checkbox size?

IE: How are you changing the checkbox size? A snippet of code would be useful.

**Comment by enchanty** [comment] 2021-01-12 19:16
I'm a designer and I'm trying to recode Samsung's design on ImGui, and since I'm just starting ImGui I'm looking for the source of this problem, the exact design and build is like this.
![Dear ImGui DirectX9 Example 2021-01-12 21-47-21](https://user-images.githubusercontent.com/71351988/104360101-99599a00-5521-11eb-878e-24931687e772.gif)

**Comment by PathogenDavid** [comment] 2021-01-12 21:25
That's all well and good, but without providing more information about what you did to cause the glitch nobody is going to be able to help you.

Your original video showed the glitch with the ImGui demo window, can you not share the **code changes** you made to cause the issue?

**Comment by enchanty** [comment] 2021-01-13 17:31
> That's all well and good, but without providing more information about what you did to cause the glitch nobody is going to be able to help you.
> 
> Your original video showed the glitch with the ImGui demo window, can you not share the **code changes** you made to cause the issue?

If you want to see my source code, I can reach it via Discord.

**Comment by thedmd** [comment] 2021-01-14 01:04
@enchanty By distilling the issue to small reproduceable piece of code you are helping to reduce friction and make it more likely people will look at fix the problem. It is very unlikely anything will happen until you provide a repro.

**Comment by enchanty** [comment] 2021-01-14 17:25
> @enchanty By distilling the issue to small reproduceable piece of code you are helping to reduce friction and make it more likely people will look at fix the problem. It is very unlikely anything will happen until you provide a repro.
> 
> Also please use issue template in the future, it is there to help save time and get as much relevant information as possible.

If you add me from discord, I can share my source code so we can find the solution faster

**Comment by enchanty** [comment] 2021-01-16 20:31
I think I found what caused the problem ImGui I used an InvisibleButton in the checkbox and I think the problem is caused by this.
![image](https://user-images.githubusercontent.com/71351988/104822360-ec4d8d00-5852-11eb-853e-0787f0e827ef.png)

**Comment by enchanty** [comment] 2021-01-16 20:44
I think I can solve this situation with ItemSize

**Comment by enchanty** [comment] 2021-01-16 20:56
But I have a togglebutton and the label must be active for the animation to be active.

**Comment by enchanty** [comment] 2021-01-16 22:35
Yeah I fixed 👍
