### ISSUE TITLE
However viewport on SDL backend (was: After upgrading to newest unstable docking the menus are not working correctly)

### ISSUE THREAD

**Issue by slajerek** [ocornut/imgui#4960] opened 2022-01-29 08:37 UTC
**Version/Branch of Dear ImGui:**

Version: commit 27004aca705e33e8a88f368372628c28f1ee4cd1
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Operating System: macOS Catalina

**My Issue/Question:**

After upgrading to commit 27004aca705e33e8a88f368372628c28f1ee4cd1 from docking branch the menus stopped working. I can not enter some menus anymore (they simply do not show submenus and do not show selection on mouse hover). After reverting to older version (from a ~1 month ago) and the same branch this works again.

**Comment by ocornut** [comment] 2022-01-29 08:39
Does it happens in the demo and example app?

Is it specifically menu as in BeginMenu() calls ? Please clarifyz

**Comment by slajerek** [comment] 2022-01-29 09:21
Yes, this **does happen** in ImGui demo.

Please check this video where I show the problem: https://www.youtube.com/watch?v=UxERr0uJAq4

As you can see there, the submenus do not open (in most cases, but seems to be intermittent sometimes).

I've checked my updates and last time I upgraded ImGui Docking was on commit 06d5f9297de441d229f717bf6284bb14e71970f9  and that was working (as it also did for last 2 years or so). Note, I only replaced the ImGui files and recompiled in the video. I may try to check which exact commit caused this showstopper, but it will take a while.

**Comment by ocornut** [comment] 2022-01-29 09:41
At first glance it seems reported to multi-viewport, perhaps backend not reporting the hovered viewport correctly.

First question: did you also update the SDL backend or are you using a copy of an old version of the SDL backend?
(If using an old version and the update backend fixes it, please back up the old backend or try to find the version because this is still something we'd aim to aim).

**Comment by ocornut** [comment] 2022-01-29 09:50
For records, this doesn't happen in the example app on latest Docking with SDL+OpenGL under Windows, with SDL 2.0.20.

So:
- perhaps it is related to an issue with old backend backward compatibility
- perhaps it is related to OSX
- perhaps it is related to SDL version (since the SDL has quite a few #ifdef there)

**Comment by ocornut** [comment] 2022-01-29 10:01
The relevant pieces of SDL in imgui_impl_sdl are:
Track hovered window:

```cpp
        case SDL_WINDOWEVENT:
        {
            // When capturing mouse, SDL will send a bunch of conflicting LEAVE/ENTER event on every mouse move, but the final ENTER tends to be right.
            // However we won't get a correct LEAVE event for a captured window.
            Uint8 window_event = event->window.event;
            if (window_event == SDL_WINDOWEVENT_ENTER)
                bd->MouseWindowID = event->window.windowID;
            if (window_event == SDL_WINDOWEVENT_LEAVE)
            {
                bd->MouseWindowID = 0;
                io.AddMousePosEvent(-FLT_MAX, -FLT_MAX);
            }
```

Then in `ImGui_ImplSDL2_UpdateMouseData()`:

```cpp
    ImGuiID mouse_viewport_id = 0;
    if (SDL_Window* sdl_mouse_window = SDL_GetWindowFromID(bd->MouseWindowID))
        if (ImGuiViewport* mouse_viewport = ImGui::FindViewportByPlatformHandle((void*)sdl_mouse_window))
            mouse_viewport_id = mouse_viewport->ID;
    io.AddMouseViewportEvent(mouse_viewport_id);
```

In that function you could print out the value of `bd->MouseWindowID` (SDL id) and `mouse_viewport_id` (imgui viewport id) and see what you get.

My impression is that perhaps under OSX with your setup and/or SDL version, you are not getting `SDL_WINDOWEVENT_ENTER/LEAVE` events correctly while a new window is taking focus?
In the window when the large menu appears it takes focus, a new viewport hosted by a new SDL window are created, and it looks like they would interfere with getting mouse events? In which case maybe SDL is inconsistent there.

**Almost certainly** if you comment those lines
```
        io.BackendFlags |= ImGuiBackendFlags_HasMouseHoveredViewport;// We can call io.AddMouseViewportEvent() with correct data (optional)
```
and comment:
```
    ImGuiID mouse_viewport_id = 0;
    if (SDL_Window* sdl_mouse_window = SDL_GetWindowFromID(bd->MouseWindowID))
        if (ImGuiViewport* mouse_viewport = ImGui::FindViewportByPlatformHandle((void*)sdl_mouse_window))
            mouse_viewport_id = mouse_viewport->ID;
    io.AddMouseViewportEvent(mouse_viewport_id);
```

It will revert to the old behavior of letting dear imgui uses its (flawed) heuristic to infer OS window z-ordering. Not ideal but we should investigate.

**Comment by slajerek** [comment] 2022-01-29 10:03
Thanks, I always also upgrade the SDL backend. 

I've just quickly checked randomly selected commit and confirm that under commit 9ce0f35ef36d4fe39052f8107d8017c8833ce771 works fine. I'll investigate this further and get back to you.

**Comment by ocornut** [comment] 2022-01-29 10:12
Probably caused by 1338eb31f73a7ee1a3dda8cfc6f1e46970e5288c

**Comment by slajerek** [comment] 2022-01-29 13:53
Yes, I confirm, the problem is caused by 1338eb31f73a7ee1a3dda8cfc6f1e46970e5288c
Also, indeed commenting out these suggested lines fixes the problem.

I tested the same codebase commit 27004aca705e33e8a88f368372628c28f1ee4cd1 and the problem:
-  **occurs** on macOS and Linux SDL 2.0.18
- **does not occur** MS Windows SDL 2.0.10. I need to recompile SDL 2.0.18 for MS Windows to confirm if that's a problem of the platform or the SDL2.

Please check video with debug logs as suggested: https://youtu.be/7XKMKqLJF_A

**Comment by ocornut** [comment] 2022-01-31 10:50
I've pushed a fix for this 08350e5

**But would be interested in confirming if it happens with latest SDL**

And most importantly: can you investigate and clarify which events are reported or not on Linux/OSX for those viewports: do you get `SDL_MOUSEMOTION` ? do you get `SDL_WINDOWEVENT_ENTER` / `SDL_WINDOWEVENT_LEAVE` ?

Thank you!

**Comment by rokups** [comment] 2022-02-02 11:07
I tested SDL 2.0.20 (latest) on Linux and MacOS.

On Linux everything works properly. Focused and unfocused windows of every kind (main viewport or viewport windows) get `SDL_MOUSEMOTION`, `SDL_WINDOWEVENT_ENTER`, `SDL_WINDOWEVENT_LEAVE` events.

However on MacOS events are terribly broken:
* Only focused window properly receives all mentioned events.
* Unfocused main viewport receives mentioned events _only_ when mouse moves _very slowly_ across left/bottom/right window border. These events are very likely to be skipped if mouse moves rapidly across the border, and are never sent if mouse moves through the top window edge (titlebar).
* Unfocused viewport windows do not receive any of these events at all, probably because there are no OS decorations that catch these events in case of main viewport.

`#ifdef _WIN32` in 08350e5 can be replaced by `#ifndef APPLE`.

**Comment by ocornut** [comment] 2022-02-03 10:52
Thank you @rokups for investigating. I have now merged the change to allow it on Linux.

**Closed by ocornut** 2022-02-03 10:52 UTC
Labels: bug, backend/binding, osx/ios, multi-viewports, linux
