### ISSUE TITLE
Space button works as Enter button for InputText when keyboard navigation is enabled

### ISSUE THREAD

**Issue by neondev9** [ocornut/imgui#4552] opened 2021-09-17 06:33 UTC
**Version/Branch of Dear ImGui:**

Version: 1.85 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx12.cpp
Operating System: Windows 10 20H2 19042.1165

**My Issue/Question:**
Space button works as Enter button for InputText widget, when keyboard navigation is enabled.
I didn't have this issue some time ago on master branch (~1.84 WIP). But I found it after switching to docking branch (commit https://github.com/ocornut/imgui/commit/5d95e7eef9cad6ca1f09dcfb9c8b520b6624eb98). Current latest commit has the same issue: https://github.com/ocornut/imgui/commit/c58fb464113435fdb7d122fde87cef4920b3d2c6
Issue can be reproduced using unmodified win32_dx12 example.
Note: I've checked release 1.84.2 there is no issue.

**Standalone, minimal, complete and verifiable example:**
1. Open example_win32_directx12.exe
2. Make sure you have enabled Configuration - configuration - io.ConfigFlags: NavEnableKeyboard
3. Go to Widgets - Text Input - Multi-line text input
4. Try to use Space button (ImGuiNavInput_Activate)
5. Single Space click works as Enter button (add newline).

**Comment by ocornut** [comment] 2021-09-17 12:35
Thanks, I can confirm the bug (regression due to commit bd6c9e99) will fix shortly.

**Comment by ocornut** [comment] 2021-09-17 14:31
Pushed fix 2cffcbdc6 thank you!

**Closed by ocornut** 2021-09-17 14:31 UTC
Labels: bug, nav, inputtext
