### ISSUE TITLE
Table column sort icon in wrong place

### ISSUE THREAD

**Issue by goossens** [ocornut/imgui#4918] opened 2022-01-19 14:42 UTC
**Version/Branch of Dear ImGui:**

Version: 1.86
Branch: Unmodified release

**Back-end/Renderer/Compiler/OS**

Back-ends: Custom GLFW with BGFX
Compiler: Xcode
Operating System: MacOS Big Sur 11.6.2

**My Issue/Question:**

Depending on the flags passed to create a table, the sort icon in the last column is rendered in the wrong place.

* The sortable table demo uses ImGuiTableFlags_Resizable , ImGuiTableFlags_BordersOuter, ImGuiTableFlags_BordersV and ImGuiTableFlags_NoBordersInBody. This renders correctly.
* By removing the border (i.e. remove the ImGuiTableFlags_BordersOuter, ImGuiTableFlags_BordersV and ImGuiTableFlags_NoBordersInBody flags), the sort icon in the last column shifts a few pixels to the right.
* By also removing the ImGuiTableFlags_Resizable flag, the sort icon in the last column shifts out of view.

**Screenshots/Video**

XXX _(you can drag files here)_

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

Change lines 5054-5057 in imgui_demo.cpp from:

```
        static ImGuiTableFlags flags =
            ImGuiTableFlags_Resizable | ImGuiTableFlags_Reorderable | ImGuiTableFlags_Hideable | ImGuiTableFlags_Sortable | ImGuiTableFlags_SortMulti
            | ImGuiTableFlags_RowBg | ImGuiTableFlags_BordersOuter | ImGuiTableFlags_BordersV | ImGuiTableFlags_NoBordersInBody
            | ImGuiTableFlags_ScrollY;
```

to:

```
        static ImGuiTableFlags flags =
           ImGuiTableFlags_Reorderable | ImGuiTableFlags_Hideable | ImGuiTableFlags_Sortable | ImGuiTableFlags_SortMulti
            | ImGuiTableFlags_RowBg
            | ImGuiTableFlags_ScrollY;
```

**Comment by ocornut** [comment] 2022-01-19 15:07
I can confirm the bug. In the end it is due to the `_PadOuterX`, `_NoPadOuterX`, `_NoPadInnerX` flags which happens to have different default based on the flags mentioned above.

By toying with flags in the "Advanced" demo + shift-clicking columns to see arrows in all columns we can visualize the issue better.

**Comment by ocornut** [comment] 2022-01-19 15:35
I won't have time to be fixing this 100% right away.
It's a little complicated due to how `TableGetCellBgRect()` works and the padding system. There are good reasons why it is setup this way, but I believe `TableGetCellBgRect()` probably should be reworked.

In `TableGetCellBgRect()` at first glance this appears to work:
```
    x1 = ImMax(x1, table->BgClipRect.Min.x);
    x2 = ImMin(x2, table->BgClipRect.Max.x);
    x1 = ImMax(x1, column->ClipRect.Min.x);
    x2 = ImMin(x2, column->MaxX);
```
Which can also remove some code in `TableEndRow()`
But I think this willneed further inspection.

**Comment by ocornut** [comment] 2022-01-19 17:10
Pushed a fix for this.


**Another issue: note for future myself**

There's another bug also related to how `TableGetCellBgRect()` function. In the drawing code in `TableEndRow()` when it applies horizontal clipping to avoid rendering highlight crossing frozen boundaries (`cell_bg_rect.Min.x = ImMax(cell_bg_rect.Min.x, column->ClipRect.Min.x)` and `cell_bg_rect.Max.x = ImMin(cell_bg_rect.Max.x, column->MaxX);` this accidentally undo the outer padding that `TableGetCellBgRect()` attempt to add. As a result in that situation with PadOuterX + NoPadInnerX, the BG highlight on a left-most and right-most cell will look incomplete:

![image](https://user-images.githubusercontent.com/8225057/150179656-d2c69f92-574c-48fd-bca2-e6462cf2cec5.png)

![image](https://user-images.githubusercontent.com/8225057/150179632-08dd2366-68f3-404f-85e9-7febbd52cc8b.png)

It's not probably that simple in reality, need to toy with Demo>Tables>Padding because I imagine there are varying expectation for where that boundaries should be depending on use and how it interact with merging of draw commands based on submitted contents, so I'll leave that for later.

**Closed by ocornut** 2022-01-19 17:10 UTC
Labels: bug, tables/columns
