### ISSUE TITLE
Multiline text with ReadOnly can render incorrectly when text changes

### ISSUE THREAD

**Issue by bgribble** [ocornut/imgui#8242] opened 2024-12-18 14:31 UTC
### Version/Branch of Dear ImGui:

Version 1.91.5, via imgui_bundle

### Back-ends:

SDL2

### Compiler, OS:

Linux + python and c++

### Details:

I discovered this issue while working with [ImGui Bundle](https://github.com/pthom/imgui_bundle) in python. The full report with reproduction code in Python and C++, and a screencast of the behavior, is in https://github.com/pthom/imgui_bundle/issues/295

My [application](https://github.com/bgribble/mfp) uses an `InputTextMultiline` with the `ReadOnly` flag to implement an interactive REPL in the application. I made it ReadOnly so I can handle input myself, to implement app-specific keybindings for history navigation and editing.  

I observed that under some circumstances the InputTextMultiline would display spaces or nonprinting characters (appearing as ???) rather than the text that was passed to the widget. Clicking in a different Imgui window in the app would cause the text to appear as expected.

I discussed with Pascal Thomet and he believes that this might be a bug in Imgui, since the following simple C++ code demonstrates it.

### Screenshots/Video:

https://private-user-images.githubusercontent.com/7694091/396430600-e32df899-1ff6-4ae4-86df-0022e19f4bc9.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Njg4NzAsIm5iZiI6MTczNDQ2ODU3MCwicGF0aCI6Ii83Njk0MDkxLzM5NjQzMDYwMC1lMzJkZjg5OS0xZmY2LTRhZTQtODZkZi0wMDIyZTE5ZjRiYzkubXA0P1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMjA0OTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDgwY2UyYWY5MzY4MTE3MTA3ZGJiMmZlYzhhY2ZiNDZjODI1NmNlMmY3OTVkZGQ2NmMyMzVhMjZhNTZhMDQxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xA_trmF6JO6AvfmqD8pQvmXsR9sssqOXGLtOr_4Zg9Y

### Minimal, Complete and Verifiable Example code:

```cpp
#include <imgui.h>
#include "misc/cpp/imgui_stdlib.h"
#include <hello_imgui/hello_imgui.h>

std::string static_text = R"(
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
occaecat cupidatat non proident, sunt in culpa qui officia deserunt
mollit anim id est laborum.
)";


char buffer[2048];

int frame_count = 0;

void gui()
{
    ImGui::Text("Should reveal text over time.");
    ImGui::Text("Click in the multiline text widget to see invisible and erroneous characters");
    ImGui::Text("Then click outside the widget to see the correct text restored");
    ImGui::Text("Code taken from demo_widgets.py");

    auto callback = [](ImGuiInputTextCallbackData* cb_data) -> int
    {
        int bufpos = frame_count / 2;
        cb_data->SelectionStart = bufpos;
        cb_data->SelectionEnd = bufpos;
        cb_data->CursorPos = bufpos;
        return 0;
    };

    memset(buffer, 0, sizeof(buffer));
    strncpy(buffer, static_text.c_str(), frame_count / 2);

    ImGui::InputTextMultiline(
        "readonly_multiline",
        buffer,
        sizeof(buffer),
        ImVec2(600, 200),
        ImGuiInputTextFlags_ReadOnly | ImGuiInputTextFlags_CallbackAlways,
        callback
    );
    frame_count++;
    if (frame_count > 2 * static_text.size())
        frame_count = 0;
}


int main()
{
    HelloImGui::Run(gui);
}

```

**Comment by ocornut** [comment] 2024-12-18 15:56
Thank you for your report and the repro, @bgribble and @pthom.

I have pushed a first fix: e900571 which uses a bit of a "live dangerously" approach, and I then extended and improved that work and removed the "live dangerously" bit by introducing an internal TextSrc pointer in 32f1140 and ensuring all read only operations used it.

Even though all tests are passing, statistically speaking I won't be surprised if this introduced a small issue _somewhere_. We will find out.

**Comment by pthom** [comment] 2024-12-18 17:31
Merci beaucoup Omar for your correction in a record time!

I like to live dangerously sometimes also :-) 
So, since you merged the correction to the docking branch, I applied the changes to Dear ImGui Bundle [in this commit](https://github.com/pthom/imgui_bundle/commit/bd7d37251e9950e3ed48bd6e3061312a162d5d51), and the issue is also solved in Python!

@bgribble : the Python wheels will be available shortly here: https://github.com/pthom/imgui_bundle/actions/runs/12398172321

**Closed** 2024-12-19 13:23 UTC
Labels: bug, inputtext

**Comment by ocornut** [comment] 2024-12-22 16:54
My apologies, https://github.com/ocornut/imgui/commit/32f11402f96f516be68b56f9eb338f382c544819 pushed on wednesday badly broke clipboard cut/copy.
Pushed fix https://github.com/ocornut/imgui/commit/6982ce43f5b143c5dce5fab0ce07dd4867b705ae

**Comment by pthom** [comment] 2024-12-22 17:11
Thanks for letting me know!

**Comment by pthom** [comment] 2024-12-22 20:11
I updated the python side too. Thanks !
