### ISSUE TITLE
BeginMenu() and IsItemClicked() inconsistency

### ISSUE THREAD

**Issue by wolfpld** [ocornut/imgui#5775] opened 2022-10-13 21:25 UTC
Consider the following example code:

```c++
static int val = 0;
ImGui::Begin("test");
ImGui::Text("%i", val);
// Option 1
if(ImGui::BeginMenu("selectable"))
{
    ImGui::Text("context");
    ImGui::EndMenu();
    if(ImGui::IsItemClicked()) val = 1;
}
// Option 2
if(ImGui::BeginMenu("outer"))
{
    if(ImGui::BeginMenu("selectable"))
    {
        ImGui::Text("context");
        ImGui::EndMenu();
        if(ImGui::IsItemClicked()) val = 2;
    }
    ImGui::EndMenu();
}
ImGui::End();
```

Here I am displaying some text value, `selectable`, which I want to be able to select. This entry has some additional context to be displayed when it's hovered over. I also want this context to be to the side of the displayed value, and with an indicator that there is something more to display. `BeginMenu()` seems to be fitting to these requirements. However, when the code is used, as presented in option 1, the `IsItemClicked()` call never returns true, and `val` is never set to 1.

If the same code would be wrapped into an encompassing `BeginMenu()` call, like in option 2, then `IsItemClicked()` is working as expected, and `val` can be set to 2.

What would be the correct course of action to take here?

**Comment by ocornut** [comment] 2022-10-14 11:42
I am not sure which item you mean to refer too when using IsItemClicked() ? It’s a little bit undefined behavior to call it after EndMenu() and without looking at the code I am not even sure which data it would get to. If you want IsItemClicked() to work for the inner-most Text() element it should be placed before EndMenu(). If you want IsItemClicked() to work on the BeginMenu() item it should be placed right after (meaning you may need a bool to hold return value of BeginMenu() before called IsItemClicked()).

I may be off the mark and maybe it already works after EndMenu() and the problem is elsewhere, I’ll check when back on a computer.

**Comment by wolfpld** [comment] 2022-10-14 11:53
The intention is to make the "selectable" item clickable. If `IsItemClicked()` is issued immediately after `BeginMenu()`, then the click detection does not work at all.

For more context, see the image below. When the user clicks on the file name, it is intended to navigate to the pointed-to line.

![obraz](https://user-images.githubusercontent.com/600573/195840327-7401be39-ab4d-4d2d-a152-1f657ca8e862.png)

**Comment by ocornut** [comment] 2022-10-14 15:19
Looking into this now.

Here's a testbed:
```cpp
if (ImGui::GetIO().KeyShift && ImGui::IsMouseClicked(0))
    printf(""); // breakpoint

ImGui::Begin("test");

// Option 1
bool menu_open = ImGui::BeginMenu("selectable");
if (ImGui::IsItemClicked())
    printf("#1A clicked (after BeginMenu)\n");
if (menu_open)
{
    ImGui::Text("context");
    ImGui::EndMenu();
    if (ImGui::IsItemClicked())
        printf("#1B clicked (after EndMenu)\n");
}
if (ImGui::IsItemClicked())
    printf("#1C clicked (after EndMenu, outside if)\n");

// Option 2
if (ImGui::BeginMenu("outer"))
{
    bool menu2b_open = ImGui::BeginMenu("selectable");
    if (ImGui::IsItemClicked())
        printf("#2A clicked (after BeginMenu)\n");
    if (menu2b_open)
    {
        ImGui::Text("context");
        ImGui::EndMenu();
        if (ImGui::IsItemClicked())
            printf("#2B clicked (after EndMenu)\n");
    }
    if (ImGui::IsItemClicked())
        printf("#2C clicked (after EndMenu, outside if)\n");

    ImGui::EndMenu();
}
ImGui::End();
```

Observing the working triggers:
```
#1A clicked (after BeginMenu)
#1C clicked (after EndMenu, outside if)
#2B clicked (after EndMenu)
#2C clicked (after EndMenu, outside if)
```
The ones you were using are surprisingly opposite, but if you use the "C" location it works with both.

----

This is a little difficult to explain, but we've been having several tricky-to-solve issues with first-level menus created from a window that is neither a popup neither a menu. The transition between a root/parent that is neither and a first-level menu requires specific hovering behavior. They have been creating a mess which I've been slowly untangling (several changes about this in past few versions).

**The reason #1B doesn't work is in that case** (first-level menu created from a window that is neither a popup neither a menu): an extra click will close the popup carrying the menu (you can see this when clicking), so in the click frame the menu popup gets closed. That's a known bug we should fix.

**The reason #2A doesn't work**:  when `BeginMenu()` succeed when get into the menu window, and IsItemXXXX after a begin-window applies to window titlebar or tabs.

You can use technique C but we should fix it so both A and B works, which will contractualize that IsItemXXX values will be the same after BeginMenu() and after EndMenu().

**Comment by wolfpld** [comment] 2022-10-14 15:39
Thanks. I can reproduce the results you get in the test application, but unfortunately not in Tracy. For now I will just use tooltips to provide the additional context information.

**Comment by ocornut** [comment] 2022-10-14 15:41
Amusingly this is a comment about exactly this in the code:
```cpp
if (menu_is_open)
{
    // FIXME: This technically breaks functions relying on LastItemData, somehow nobody complained yet. Should backup/restore LastItemData.
    [...]
    menu_is_open = BeginPopupEx(id, flags);
```
I pushed 8117673 now which should fix the B case. Can you confirm it works if temporarily cherry-picked? (before I merge to docking)

**Comment by ocornut** [comment] 2022-10-14 15:44
> For now I will just use tooltips to provide the additional context information.

From an UI affordance perspective it seems sensible to use Selectable + manually positioned tooltips.
But regardless the things should be fixed (B should be done now, A case still open)

**Comment by wolfpld** [comment] 2022-10-14 15:49
With current master I am getting 1AC, 2ABC in the test application. Cherry-pick is not clean for me, so can't easily test this.

**Comment by ocornut** [comment] 2022-10-14 15:50
Yes, sorry if was unclear, 1A is preventing 1B.  :(

**Comment by ocornut** [comment] 2022-10-14 16:53
I have pushed 08752b3 a (long-awaited) fix for 1A and merged into Docking.

**Comment by wolfpld** [comment] 2022-10-14 17:48
Confirming that the fix works.

**Closed** 2022-10-14 18:18 UTC
Labels: bug, menus
