### ISSUE TITLE
BeginChild doesn't respect ImGuiWindowFlags_AlwaysAutoResize

### ISSUE THREAD

**Issue by danbrown3** [ocornut/imgui#5148] opened 2022-03-30 16:35 UTC
**Version/Branch of Dear ImGui:**

Version: v1.79 WIP
Branch: Not sure

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp
Operating System: Windows

**My Issue/Question:**

When using BeginChild with the window flag ImGuiWindowFlags_AlwaysAutoResize, the window will not correctly resize to fit the content. 

In ImGui::BeginChildEx, we do some size calculation based on GetContentRegionAvail and then call SetNextWindowSize. The call to SetNextWindowSize is the problem. Calling SetNextWindowSize results in the following code in ImGui::Begin setting the set_by_api variables to true.

`if (g.NextWindowData.Flags & ImGuiNextWindowDataFlags_HasSize)
    {
        window_size_x_set_by_api = (window->SetWindowSizeAllowFlags & g.NextWindowData.SizeCond) != 0 && (g.NextWindowData.SizeVal.x > 0.0f);
        window_size_y_set_by_api = (window->SetWindowSizeAllowFlags & g.NextWindowData.SizeCond) != 0 && (g.NextWindowData.SizeVal.y > 0.0f);
        SetWindowSize(window, g.NextWindowData.SizeVal, g.NextWindowData.SizeCond);
    }`

This in turn causes this code further down in ImGui::Begin to not execute.

`        if ((flags & ImGuiWindowFlags_AlwaysAutoResize) && !window->Collapsed)
        {
            // Using SetNextWindowSize() overrides ImGuiWindowFlags_AlwaysAutoResize, so it can be used on tooltips/popups, etc.
            if (!window_size_x_set_by_api)
            {
                window->SizeFull.x = size_auto_fit.x;
                use_current_size_for_scrollbar_x = true;
            }
            if (!window_size_y_set_by_api)
            {
                window->SizeFull.y = size_auto_fit.y;
                use_current_size_for_scrollbar_y = true;
            }
        }`

You can easily reproduce this issue by changing the "scrolling" child in ImGuiSystemsGroup::Impl::showFilteredList() to the following:

ImGui::BeginChild("scrolling", ImVec2(0, 0), false, ImGuiWindowFlags_AlwaysAutoResize);

Make sure you have some systems with long names, launch, and open the systems menu.

The width of the systems menu will not resize to fit its contents. If you comment out SetNextWindowSize in BeginChildEx, the menu will be resized correctly, although it's safe to assume that's breaking something else.

**Comment by danbrown3** [comment] 2022-03-30 16:45
I just realized that the code I mentioned is our own. I had assumed that was default imgui. You should be able to do the same thing just by writing your own scrolling child.

**Comment by ocornut** [comment] 2022-03-30 16:59
The purpose of `BeginChild()` is to provide a scrolling region. Using `ImGuiWindowFlags_AlwaysAutoResize` defeat that purpose so they are pretty much contradictory concepts. What are you trying to do?

**Comment by ocornut** [comment] 2022-03-31 05:31
Well _AlwaysAutoResize won’t do that.
It should be possible eventually to make child windows be manually or automatically resizable on some axis but not possible yet.
However if you capture the contents size or calculate expected size before BeginChild(), using code analoguous to what BeginCombo() does to align its popup, you can set the child size manually yourself.

**Comment by ocornut** [comment] 2022-03-31 09:58
Closing as duplicate of #1710

**Closed by ocornut** 2022-03-31 09:58 UTC
