### ISSUE TITLE
InputTextCallbacks

### ISSUE THREAD

**Issue by Aborres** [ocornut/imgui#541] opened 2016-03-02 11:10 UTC
Using ImGuiInputTextFlags_CallbackAlways, data->EventKey and data->EventChar are never updated. But if you use ImGuiInputTextFlags_CallbackCharFilter data->EventChar is updated but data->Buf is NULL instead of your text buffer. That gives you few control over the buffer.
Would be also good have your filled size?

**Comment by ocornut** [comment] 2016-03-02 20:56
This is correct. The callback are for different events and processed in different spots, but if you pass both flags `ImGuiInputTextFlags_CallbackCharFilter|ImGuiInputTextFlags_CallbackAlways` you should get both events. You may receive multiple events back and you can identify event given the `EventFlag` member. Arguably CallbackAlways may be badly named here.

Does that solve your problem? What are you trying to do precisely?

> Would be also good have your filled size?

You mean the text-length? I will look into adding that.

**Comment by ocornut** [comment] 2016-03-02 22:36
I have added a BufTextLen field to spare the user from doing a strlen(). I am also now requesting the user to maintain this field if the buffer is modified. The provided helpers DeleteChars/InsertChars maintain this field and I have added a debug assert when returning from the callback that checks if the value is correct. Removing extraneous calls of strlen() has been useful with dealing with large blurbs of texts.

**Comment by ocornut** [comment] 2016-03-02 22:39
Your original post imply that you might want to modify the text buffer manually on a regular character input, which you can't at the moment (but you could if you recorded the key event and then did the processing when the following event comes, with the knowledge that characters events come before the Always event). It is something you really need, and if so could you describe what you need it for?

(I could refactor the code so that Key events allow raw buffer modification but that'll be more work)

**Comment by Aborres** [comment] 2016-03-03 09:58
Yesterday I was trying all the possible configurations to test it and this is what I found:
If you use something like:

    ImGuiInputTextFlags tflags = 0;
    tflags |= ImGuiInputTextFlags_AlwaysInsertMode;
    tflags |= ImGuiInputTextFlags_CallbackCharFilter;
    tflags |= ImGuiInputTextFlags_EnterReturnsTrue;
    tflags |= ImGuiInputTextFlags_AllowTabInput;

In my callback I was checking for:

    if  (data->EventKey == ImGuiKey_Enter)  {
    ...
    }
But that event key is never update and is always 0 which is tab on your enum. data->EventChar actually works but the     data->Buff is NULL.

So I tried for ImGuiInputTextFlags_CallbackAlways and I found there that neither of     data->EventChar and     data->EventKey were updated, but I was recieving the correct buffer.

I'm currently working on a small text editor for my game engine to edit some shaders and scripts that is why I asked you. I could change that part by my self If you don't mind.
Some advice to start? :)

**Comment by ocornut** [comment] 2016-03-03 10:13
Enter isn't a "character" it is a key.

What are you trying to do exactly? Its hard to help you without knowing that. Why do you need those callbacks?

With ImGuiInputTextFlags_EnterReturnsTrue the InputText function will return true as a convenience when enter is pressed.

**Comment by Aborres** [comment] 2016-03-03 10:31
yep and I started using it as a Key but as I said before, the EventKey never seems to be updated so I changed the Always for the CharFilter and the EventKey for the EventChar. I want some controll over the text every frame to controll what is happening for my text editor.

For example, controll when tab is pressed and replace /t to a X number of spaces, controll over the vertical size of the text to create line numbers, etc.

**Comment by ocornut** [comment] 2016-03-03 10:47
Which field are set by which event is documented in the declaration for the ImGuiTextEditCallbackData structure. So EventChar is set by the CharFilter event and EventKey is set by the Completion/History events (it is actually misdocumented as set for Always which may be the cause of your prejudice here, will fix).

> For example, controll when tab is pressed and replace /t to a X number of spaces,

So you are right this would require the CharFilter event to allow modifying the text buffer, so you could use InsertChars() and filter the tab out. So could POSSIBLY rely on catching both CharFilter and Always event, record the CharFilter tab character, filter it and store a boolean, then in the Always event submit the new character. It'll be a bit weird but it should work.

Not sure when I can do this extra development to allow CharFilter event to modify the text buffer.

> controll over the vertical size of the text to create line numbers

Not sure what that entails exactly.

**Comment by Aborres** [comment] 2016-03-03 11:29
Ok I have just tried it and seems to work but when the callback is called by the always event, the EventFLag is not updated (is equal to 0) but don't mind it works, quite strange and inefficient but works!

Thank you very much for your time and your support!

**Comment by ocornut** [comment] 2016-03-04 12:19
I have made it that the Always event set EventFlag to ImGuiInputTextFlags_CallbackAlways. 

The reason this is a little tricky to finish it (if anyone is inclined into looking at it) is that we provide a UTF-8 buffer and UTF-8 positions to the user. This requires conversions back and forth from internally used wchar and can be quite costly for large text. Those conversions are generally making the InputText() cost more complex and costly than it should be.

The plan is to modify stb_textedit.h to fully supports UTF-8 which I have roughly outline there https://github.com/nothings/stb/issues/188 That would allow to simplify InputText() by a large margin.

**Comment by ocornut** [comment] 2016-04-02 23:07
Closing this. I've added note in the todo list that we could allow CharFilter to modify the buffer, and that would be done I manage to remove all the UTF8-wchar conversion as stated above.

**Closed by ocornut** 2016-04-02 23:07 UTC
Labels: enhancement
