### ISSUE TITLE
Optional horizontal scrolling bar

### ISSUE THREAD

**Issue by digiorgi** [ocornut/imgui#312] opened 2015-08-30 13:49 UTC
Hi! Is possible to have a horizontal scrolling bar? I ask this, because in can't find it in the examples.

**Comment by ocornut** [comment] 2015-08-30 13:51
Duplicate of #246
I'm been working on it right now actually, should commit a first version soon.!

**Closed by ocornut** 2015-08-30 13:51 UTC

**Comment by ocornut** [comment] 2015-08-30 17:50
Horizontal scrolling added, see #246
