### ISSUE TITLE
How to change Multi Viewports window backgound  to transparency outside? set NoBackground,but in outside is black!  

### ISSUE THREAD

**Issue by kazhafeizhale** [ocornut/imgui#5282] opened 2022-05-04 04:49 UTC
Version: 1.8
Branch: viewport/docking

**dx11 win32**

**
i want make a transparence windows use muti viewports,
but nobackground cut no ice, when window in outside 
![image](https://user-images.githubusercontent.com/26515268/166624377-24d89341-d471-45fe-b9b3-d35432d5de9b.png)
![image](https://user-images.githubusercontent.com/26515268/166624415-b7c6c68f-b116-4dda-90f3-dc6e0c02f4e5.png)

can you give me some advice?
**

**Comment by ocornut** [comment] 2022-05-04 10:18
Closing as duplicate of #2766, #4629, #5218

**Closed by ocornut** 2022-05-04 10:18 UTC
Labels: multi-viewports
