### ISSUE TITLE
GLFW backend: PrevWndProc != NULL assertion fails on Windows

### ISSUE THREAD

**Issue by LDAP** [ocornut/imgui#7868] opened 2024-08-07 14:13 UTC
### Version/Branch of Dear ImGui:

Version 1.91/v1.90.9, Branch: master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp

### Compiler, OS:

Windows 11, MSVC

### Details:

**My Issue/Question:**

A Assertion in ImGUI fails:
```
Assertion failed: bd->PrevWndProc != nullptr, file ../subprojects/imgui/backends/imgui_impl_glfw.cpp, line 627
```

cause by https://github.com/ocornut/imgui/blob/3232070d3abaec531d75e060fab14a26cb36ab55/backends/imgui_impl_glfw.cpp#L640

If I am not mistaken this is a regression of 32f9dfc1261e4b8dd4a026588ee966c200b7f3f0

### Minimal, Complete and Verifiable Example code:

The issue is in the ImGui_ImplGlfw_Init, meaning the example_glfw_vulkan should reproduce (did not have time to test).

**Comment by ocornut** [comment] 2024-08-07 14:52
> If I am not mistaken this is a regression of https://github.com/ocornut/imgui/commit/32f9dfc1261e4b8dd4a026588ee966c200b7f3f0

This commit only renamed the field.
This assertion has been here since April 2023 (f070497cb).

> The issue is in the ImGui_ImplGlfw_Init, meaning the example_glfw_vulkan should reproduce (did not have time to test).

Please research it, I am pretty sure the example_glfw_vulkan doesn't exhibit this. The assertion is here to notify you of an issue.

It is largely abnormal that this value would be null here. I wonder if it is the `(HWND)PlatformHandleRaw` value is that incorrect, o if the HWND is correct but `GetWindowLongPtrW(...., GWLP_WNDPROC)` is actually NULL and why, since GLFW installs one.

Do please do more research because it is also likely that the issue is in your end.

**Comment by LDAP** [comment] 2024-08-07 16:04
You're completely right!

The issue was introduced by a simultaneous switch to a shared library (built according to the current Meson WrapDB https://wrapdb.mesonbuild.com/v2/imgui_1.89.9-2/imgui.wrap but with updated version numbers).

I am not quite sure how exactly, since I am only interacting with ImGUI from one "static boundary". But I might also misunderstand the notice here (and I don't know what I am doing when compiling for Windows): https://github.com/ocornut/imgui/blob/3232070d3abaec531d75e060fab14a26cb36ab55/imconfig.h#L24

**Comment by ocornut** [comment] 2024-08-21 12:29
I'll close this as a user issue.

**Closed by ocornut** 2024-08-21 12:29 UTC
Labels: backends
