### ISSUE TITLE
IsWindowHovered(ImGuiHoveredFlags_ChildWindows) does not work well with viewports

### ISSUE THREAD

**Issue by Hedanito** [ocornut/imgui#2432] opened 2019-03-19 11:34 UTC
**Version/Branch of Dear ImGui:**

Version: 1.69 (WIP)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: Custom
Operating System: Windows

**My Issue/Question:**

I am using `ImGui::IsWindowHovered(ImGuiHoveredFlags_ChildWindows)` right before `ImGui::EndPopup()` to manually check if the mouse is hovering a popup. This works fine when the entire popup stays within the same viewport. However, when the popup ends up outside of the viewport (and thus has to create new viewports for each submenu), hovering of the popup's submenus is not detected.

**Standalone, minimal, complete and verifiable example:**
```
bool is_hovered = false;
if (ImGui::BeginPopup("my_popup"))
{
	if (ImGui::BeginMenu("Edit"))
	{
		ImGui::MenuItem("Cut");
		ImGui::MenuItem("Copy");
		ImGui::MenuItem("Paste");
		ImGui::EndMenu();
	}

	// This always returns false for the menu items when they are in their own viewport!
	is_hovered = ImGui::IsWindowHovered(ImGuiHoveredFlags_ChildWindows);

	ImGui::EndPopup()
}
```

**Comment by ocornut** [comment] 2019-03-25 15:13
Hello @Hedanito, I have confirmed the issue and pushed a fix now.

I think the code is `IsWindowHovered()` unnecessarly called IsWindowContentHoverable() with `g.HoveredRootWindow` which leads to a mismatch in the viewport check, this block return false:

```
// Filter by viewport
if (window->Viewport != g.MouseViewport)
    if (g.MovingWindow == NULL || window->RootWindow != g.MovingWindow->RootWindow)
        return false;
```

We could look up the viewport hierarchy by following `g.MouseViewport->ParentViewportId` but I think the fact that `IsWindowContentHoverable()` was being called with `g.HoveredRootWindow` is a mistake and we can fix this directly. In the master branch it doesn't make a difference at all but it does in docking. 

Code has been like this since f421f2f47e632cbbc3259e2edd27aba6f5a8e594.

Pushed fix now.

**Closed by ocornut** 2019-03-25 15:13 UTC
Labels: bug, popups, viewport
