### ISSUE TITLE
Is there a way to disable a widget (shown but with a disabled state)?

### ISSUE THREAD

**Issue by haddock07** [ocornut/imgui#330] opened 2015-09-13 01:20 UTC
For example, I would like to have a check box, in a disabled state, where it couldn't be activated or hovered, and displayed with a darker color. Of course, the function ImGui::Checkbox would always return false.

I did a workaround by setting the same color for the 3 states (normal, hovered, active), but when the user clicks on the check box, the check mark is actually shown one frame before returning to the unchecked state.

**Comment by ocornut** [comment] 2015-09-13 09:15
Duplicate of #211,moving there

**Closed** 2015-09-14 10:48 UTC
