### ISSUE TITLE
InputText doesn't update its content

### ISSUE THREAD

**Issue by xzripper** [ocornut/imgui#6728] opened 2023-08-16 15:48 UTC
**Version/Branch of Dear ImGui:**

Version: v1.89.8
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: SFML, OpenGL (https://github.com/SFML/imgui-sfml)
Compiler: GCC (G++)
Operating System: Windows 10

**My Issue/Question:**

I observed that if the variable is declared as static (variable required: std::string* str in imgui_stdlib InputText, second argument), the content within InputText does not update, but it can be edited. Conversely, if the variable is not static, the content within InputText updates, but it cannot be edited.

**Screenshots/Video**

Reference on static variable:
![test_3HP2yuMaNx](https://github.com/ocornut/imgui/assets/94743980/03a15547-8269-4579-9f6b-66883edaae1e)

Reference on non-static variable:
![test_vILVVNTYoN](https://github.com/ocornut/imgui/assets/94743980/19236d2c-f4e1-4994-b58b-f6ec842235ce)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Includes.
#include "SFML\include\SFML\Graphics.hpp"

#include "imgui\include\imgui.h"
#include "imgui\include\imgui-SFML.h"
#include "imgui\include\imgui_stdlib.h"

#include <iostream>

int main() {
    sf::RenderWindow window(sf::VideoMode(500, 500), "Hello!");

    ImGui::SFML::Init(window);

    sf::Clock clock;

    while(window.isOpen()) {
        ImGui::SFML::Update(window, clock.restart());

        sf::Event event;

        ImGui::Begin("yummi");

        while(window.pollEvent(event)) {
            ImGui::SFML::ProcessEvent(event);

            if(event.type == sf::Event::Closed) {
                window.close();
            }
        }

        // Main issues begin.
        static bool check = true;

        ImGui::Checkbox("checkbox", &check);

        static std::string inputContent = check ? "hello world" : "bye world"; // remove / or add 'static' to see difference

        ImGui::InputText("input", &inputContent);
        // Main issues end.

        ImGui::End();

        window.clear();

        ImGui::SFML::Render(window);

        window.display();
    }

    return 0;
}
```

When `inputContent` is static, the content does not get updated. However, it is possible to edit the content inside the Input. Whereas when `inputContent` is not static, the content gets updated and, in that case, it is impossible to edit the content in the input. Any thoughts?

**Comment by ocornut** [comment] 2023-08-16 15:55
Things are behaving exactly as they should.

This is a C++ understanding issue and on your insistence to open issues without reading our answers I am going to close this.
Please investigate by yourself.

**Closed by ocornut** 2023-08-16 15:55 UTC

**Comment by xzripper** [comment] 2023-08-16 16:11
I've been trying to fix this for a few days. Is it that difficult to write a solution that, I wager, will take no more than one line?

**Comment by sakiodre** [comment] 2023-08-16 16:22
It seems like you don't understand the `static` keyword. If you use `static`, it's only initiated once, consider the following code:
```cpp
void increase(){
    static int value = 0;
    std::court << value << " ";
    value += 1;
}
increase();
increase();
increase();
```
Will output: `0 1 2`, this is because `value` is only set to `0` once.
Without the static keyword, the output would be: `0 0 0`, because `value` is set to 0 every time.

So with `static`, the text can be edited, but the checkbox doesn't work because `= check ? "hello world" : "bye world";` is only executed once. And without `static`, the text couldn't be edited because it'd reset every loop. This is expected behavior.

To achieve your goal, do this instead:
```cpp
static std::string inputContent = check ? "hello world" : "bye world";

// ImGui::Checkbox returns true if it was clicked on
if (ImGui::Checkbox("checkbox", &check))
{
    inputContent = check ? "hello world" : "bye world";
}

ImGui::InputText("input", &inputContent);
```

**Comment by GamingMinds-DanielC** [comment] 2023-08-16 18:12
There are many possible solutions depending on what you want exactly. The easiest way would be to ditch the apply button and edit your object directly. For that get rid of your static string, edit `object.lobjectname` directly and make your `object`into a reference (`LevelObject&`) instead of a copy. No need to explicitly copy back then.

If you want to keep your apply button to copy back the edited object, let `opject` remain a copy, but don't overwrite it every frame. Keep a persistent object that you update only when you f.e. change the selection and copy it back when you want to apply your changes. That's OK if you want to be able to discard changes and if your object data doesn't change elsewhere. It gets a lot more complicated if you want to support undo/redo.

Other than that, why is your `show`-method static? You won't have access to non-static members of your `ObjectEditorUI` instance that way, not good for a UI that usually involves a lot of persistent state.

Besides that, `SetWindowSize` and `SetWindowPos` are outdated and not recommended for use. See their header documentation for a better replacement.

**Comment by xzripper** [comment] 2023-08-16 19:30
I'd like to do ``InputText'' that has ```object.lobjectname``` in it's default content, and also with the ability to edit that input. As I'm trying to do. I also don't need access to ``ObjectEditorUI`` fields or anything.

**Comment by GamingMinds-DanielC** [comment] 2023-08-17 09:04
And? Have you tried the "easiest way" solution that I described? That one will work if you followed the steps correctly.

**Comment by xzripper** [comment] 2023-08-17 09:44
I don't rewrite ```object``` every frame, I just call ```show``` in the loop because it should be called in the loop. And I don't need undo/redo.

**Comment by xzripper** [comment] 2023-08-17 09:47
I just want to edit some values in Input and then apply the edited values by clicking the button

**Comment by GamingMinds-DanielC** [comment] 2023-08-17 10:08
That would be the second solution I described. The persistent copy of the object would best be placed as state in your ObjectEditorUI class, the one you think you don't need any member access to.

Why do you need the button? Why not edit the object directly? The first solution that I described (the one without the apply button) would be easier to implement because it requires less state handling. And seeing how you struggle with the editing, you should go for the easier way first.

**Comment by xzripper** [comment] 2023-08-17 10:47
How should I make persistent copy of object when I'm creating object in function and I need buffer and index to do it? I really don't understand the logic.

**Comment by xzripper** [comment] 2023-08-17 10:50
```cpp
        for(int _selectedObjectIndex=0; _selectedObjectIndex < objectsBuffer.getBufferSize(); ++_selectedObjectIndex) {
            LevelObject object = objectsBuffer.getWithIndex(_selectedObjectIndex);

            if(ImGui::Selectable(((std::to_string(_selectedObjectIndex + 1) + ". ") + object.lobjectname).c_str())) {
                selectedObjectIndex = _selectedObjectIndex;

                selectedObject = object;
            }
        }
```

```cpp
ObjectEditorUI::show(objectsBuffer.getReferenceBuffer(), selectedObjectIndex);
```

```
    static void show(std::vector<LevelObject> &buffer, int selectedObjectIndex) {
        bool open = true;

        ImGui::Begin(OBJECT_EDITOR_UI_TITLE, &open, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove);

        ImGui::SetWindowSize(ImVec2 {OBJECT_EDITOR_UI_WIDTH, ObjectEditorUI::dynHeight});

        ImGui::SetWindowPos(ImVec2 {ObjectEditorUI::dynX, OBJECT_EDITOR_UI_Y});

        if(selectedObjectIndex != -1) {
            LevelObject object = buffer.at(selectedObjectIndex);

            if(object.lobjecttype == LevelObjectType::RECTANGLE) {
                ImGui::Text("Editing...: LevelObjectType::RECTANGLE.");

                static std::string objectName = object.lobjectname;

...etc
```

**Comment by ocornut** [comment] 2023-08-17 10:56
> LevelObject object = objectsBuffer.getWithIndex(_selectedObjectIndex);
> LevelObject object = buffer.at(selectedObjectIndex)

You are making COPIES of your object and editing the COPIES of your object.

You should take pointers/references to your objects and edit their members directly.

**Comment by xzripper** [comment] 2023-08-17 11:11
Thanks, it finally works! I'd like to update values with a button, but it's better than nothing. Thank you all!

**Comment by xzripper** [comment] 2023-08-17 11:13
Thanks, it finally works! I'd like to update values with a button, but it's better than nothing. Thank you all!

**Comment by xzripper** [comment] 2023-08-17 11:15
One more thing: what if I do not have the field as an int, but as a std::optional<int>, how should I update this value?
```cpp
ImGui::InputInt("Object Rotation.##rect", &object.objectRotation); // error: cannot convert 'std::optional<int>*' to 'int*'
```

**Comment by ocornut** [comment] 2023-08-17 11:39
So you can use this:
```cpp
if (ImGui::InputInt("Object Rotation.##rect", &objectRotation))
    object.objectRotation = objectRotation;
````
To only copy when modified.

**Comment by GamingMinds-DanielC** [comment] 2023-08-17 11:44
> Thanks, it finally works!

So you didn't try when I told you to use a reference instead of a copy yesterday. Oh well...

> ```c++
> static int objectRotation = object.objectRotation.value_or(0);
> 
> ImGui::InputInt("Object Rotation.##rect", &objectRotation);
> 
> object.objectRotation = objectRotation;
> ```

I see you still have problems with the `static` modifier. You are running into the same problem again as you will see when you change the object selection.

**Comment by xzripper** [comment] 2023-08-17 11:50
> > Thanks, it finally works!
> 
> So you didn't try when I told you to use a reference instead of a copy yesterday. Oh well...
> 
> > ```c++
> > static int objectRotation = object.objectRotation.value_or(0);
> > 
> > ImGui::InputInt("Object Rotation.##rect", &objectRotation);
> > 
> > object.objectRotation = objectRotation;
> > ```
> 
> I see you still have problems with the `static` modifier. You are running into the same problem again as you will see when you change the object selection.

I also remove 'static' from 'objectRotation' and now it completely working, thanks!
