### ISSUE TITLE
ImGui::BeginCombo doesn't work when called inside a ModalPopup

### ISSUE THREAD

**Issue by SSBMTonberry** [ocornut/imgui#1755] opened 2018-04-18 20:46 UTC
Hey!
For some reason ImGui::BeginCombo doesn't give any result when pressing the combobox inside a ModalPopup. Doesn't seem to bother opening at all. This is when using ImGui 1.60. I rolled back to ImGui 1.53 and everything was fine again.
The code itself is simple:
```
        if (ImGui::BeginCombo(m_label.c_str(), m_currentItem))
        {
            for (int i = 0; i < m_list.size(); i++)
            {
                bool is_selected = (m_currentItem == nullptr) ? false : (m_list[i].compare(m_currentItem) == 0);
                if (ImGui::Selectable(m_list[i].c_str(), is_selected))
                {
                    m_currentItem = m_list[i].c_str();
                    valueChosen = true;
                }

                if (is_selected)
                    ImGui::SetItemDefaultFocus();
            }
            ImGui::EndCombo();
        }
```

![popupmodalbug_1 60](https://user-images.githubusercontent.com/26206421/38957145-0f3de3e8-435a-11e8-8eab-6ef08ff5e848.png)

It's supposed to have two results, but doesn't display anything in 1.60. Not sure what changes that have happened that may cause this.

**Comment by ocornut** [comment] 2018-04-19 08:43
Hello Robin,

The demo code has a combo inside a modal and it works:

![image](https://user-images.githubusercontent.com/8225057/38980751-f67ce5fc-43bd-11e8-970e-d5f2eddeec6f.png)

So your issue is probably caused by something else. It would be good if you try to narrow down your issues by creating a **stand-alone repro** that can be pasted in one of the examples/ that shows and includes all the code and data. Right now your snippet doesn't include enough context nor any of the data. Some things are clearly missing, as your screenshot shows a combo box aligned on the right side of the window, without a visible label etc. Your issue lies within one of the thing you omitted.

**Comment by SSBMTonberry** [comment] 2018-04-19 14:59
Thanks for the quick response!
The label is not there simply because it's disabled. I understand that the information I provided is a bit too narrow. I got quite a few objects that works like wrappers for ImGui, so I thought it would be a bit too much. The only thing I know for sure now is that I use the same code (with the required changes from either of the versions) but get different results in 1.53 and 1.60. The demo code with Combo uses ImGui::Combo("Combo", &item, "aaaa\0bbbb\0cccc\0dddd\0eeee\0\0"); and not ImGui::BeginCombo like I do. I think that's where the issue lies. I'll prepare some code as example and get back to you, but I believe ImGui::BeginCombo + Modal has issues in 1.60.

**Comment by ocornut** [comment] 2018-04-19 15:06
`Combo()` uses `BeginCombo()` pretty much exactly in the same way as you do above, and I even pasted and adapted your loop into the modal window of the demo (with dummy data) and it worked.

**Comment by ocornut** [comment] 2018-04-19 15:14
It's fine if your repro code stays in your language/wrapper - but trying to actually isolate the bug will probably allow us to find the cause. For example you may have code that directly or indirectly sets the focus on that modal window, and that will close all its child windows.

Do you get a reaction (e.g. a quick flicker) when you click on the combo?

**Comment by SSBMTonberry** [comment] 2018-04-19 15:27
Just tried it using the demo myself, replacing Combo with BeginCombo, and it seems to work just fine, like you say. I'll post some more of the actual code soon. Yes, I get flickering when pressing the combo box.

**Comment by SSBMTonberry** [comment] 2018-04-19 16:05
Ok, so here we go:

1.53 result (works like expected):
![image](https://user-images.githubusercontent.com/26206421/39003219-b010af08-43fa-11e8-978f-6c86afb83e92.png)

1.60 result (flickers when pressing, hover also lights up the combobox):
![image](https://user-images.githubusercontent.com/26206421/39003388-0d8ffab2-43fb-11e8-9c63-91b8816d711a.png)

The main code:
```
    unique_ptr<pme::Popup> popup = GuiFactory::CreatePopup("popup_test_id", "PopupModal 1.60", 922);
    unique_ptr<pme::Combobox> comborillo = GuiFactory::CreateCombobox("combo_test_id", "Combotest (flicker when pressed)");
    //comborillo->setHasLabel(false); //Removed not to make confusion
    comborillo->addValue("Robin's shitty code");
    comborillo->addValue("does not work :(");
    popup->add(move(comborillo));
    popup->setOpen(true);
```

The Popup:
Works like a container of control objects, basicly. The code for drawing looks like this:

```
void pme::Popup::draw()
{
    if(!m_isVisible)
        return;

    if(m_open)
    {
        ImGui::OpenPopup(getImguiId().c_str());

        if(m_positionHasBeenChanged || m_useLockedPosition)
        {
            ImGui::SetNextWindowPos(ImVec2(m_position));
            ImGui::SetNextWindowSize(ImVec2(m_size));
            m_positionHasBeenChanged = false;
        }
    }

    if (ImGui::BeginPopupModal(getImguiId().c_str(), &m_open, getFlagsAsImGuiFlags()))
    {
        for (auto const &item : m_controls)
            item->process();

        if (ImGui::Button("Close"))
        {
            ImGui::CloseCurrentPopup();
            m_open = false;
        }

        ImGui::EndPopup();
    }
}
```

Combobox.h:
```
namespace pme
{
    class Combobox : public Control
    {
        public:
            Combobox(const std::string &id, const std::string &label);

            virtual bool process();

            void addValue(const std::string &value);
            void addValueRange(const std::initializer_list<std::string> &values);
            void removeValue(const std::string &value);

            void setColor(const sf::Color &text, const sf::Color &background);
            void setHasLabel(bool hasLabel);

            bool hasLabel() const;
            const std::string &getValue() const;

        protected:
            void assignColors() override;

            const char* m_currentItem = nullptr;
            std::vector<std::string> m_list;
            std::string m_value;
            bool m_hasLabel = true;

            sf::Color m_textColor;
            sf::Color m_backgroundColor;

    };
}
```

Combobox.cpp (showing a inherited function process(), which does all the job):
```
bool pme::Combobox::process()
{
    if(Control::process())
    {
        bool popColors = false;
        if (m_colorIsChanged && !m_useDefaultColor)
        {
            assignColors();
            popColors = true;
        }

        bool valueChosen = false;
        if(!m_hasLabel)
            ImGui::PushItemWidth(-1);

        if (ImGui::BeginCombo(m_label.c_str(), m_currentItem))
        {
            for (int i = 0; i < m_list.size(); i++)
            {
                bool is_selected = (m_currentItem == nullptr) ? false : (m_list[i].compare(m_currentItem) == 0);
                if (ImGui::Selectable(m_list[i].c_str(), is_selected))
                {
                    m_currentItem = m_list[i].c_str();
                    valueChosen = true;
                }

                if (is_selected)
                    ImGui::SetItemDefaultFocus();
            }
            ImGui::EndCombo();
        }

        if(!m_hasLabel)
            ImGui::PopItemWidth();

        if (popColors && !m_useDefaultColor)
        {
            ImGui::PopStyleColor(2);
        }

        if (m_currentItem != NULL)
            m_value = *m_currentItem;

        return valueChosen;
    }

    return false;
}
```

While it doesn't show everything, I hope it gives an idea of what the issue can be. Thank you again for the quick response! :)

**Comment by ocornut** [comment] 2018-04-19 16:13
You are not supposed to call `OpenPopup()` every frame, by doing so you are reseting the popup state and therefore closing its children. The behavior was changed/fixed to allow e.g. context menu to be closed and recreated. I think previously it accidentally worked in some cases (probably for modals) but OpenPopup was always documented as a toggle/edge function and not a level function.

(Unrelated, but your code seems mostly dedicated to undoing all the benefits of the IMGUI paradigm, so it is a little puzzling to witness....)

**Comment by SSBMTonberry** [comment] 2018-04-19 18:48
Ok, so I figured it out:
![image](https://user-images.githubusercontent.com/26206421/39011564-166f7588-4412-11e8-90c1-a42f67147f00.png)

Inside the Popup's draw function:
   ```
 if(m_open)
    {
        if(!ImGui::IsPopupOpen(getImguiId().c_str()))
            ImGui::OpenPopup(getImguiId().c_str());

        if(m_positionHasBeenChanged || m_useLockedPosition)
        {
            ImGui::SetNextWindowPos(ImVec2(m_position));
            ImGui::SetNextWindowSize(ImVec2(m_size));
            m_positionHasBeenChanged = false;
        }
    }
```
Checking IsPopupOpen before calling OpenPopup did the job, and makes sure OpenPopup isn't called every frame. So the problem I was experiencing was probably due to "reseting the popup state and therefore closing its children", as you said, by calling OpenPopup every frame. 
Thank you for your dedication and help, Omar! Would be hard for me to find this one without your guidance :) But on the bottom line, it was due to my code being shit all along :toilet:

**Comment by ocornut** [comment] 2018-04-19 19:34
No problem, it's a common issue with `OpenPopup`. I don't know yet how to facilitate debugging that sort of problem, maybe a sort of simplified log of the frame (encoded with simple enum + id) would facilitate it. There are various other situation where focus stealing can be tricky to understand.

Closing this now!

**Closed by ocornut** 2018-04-19 19:34 UTC
Labels: popups
