### ISSUE TITLE
Creating an ImageButton is coming out with a blue background even though i set the bg_col to 0 0 0 0?

### ISSUE THREAD

**Issue by whiskasdietgirl** [ocornut/imgui#4216] opened 2021-06-11 21:55 UTC
Im sorry if there is something im not seeing well. But i tried it so many times and in many different ways. It always comes with this blue background in my transparent png.
The image renders properly as a png as a Image (not imagebutton).
Please help me.

```
if (ImGui::ImageButton(whiskas_cat_img, ImVec2((float)300, (float)50), ImVec2(0.0f, 0.0f), ImVec2(1.0f, 1.0f), 1, ImVec4(0.0f, 0.0f, 0.0f, 0.0f), ImVec4(1.0f, 1.0f, 1.0f, 1.0f))) {
Beep(400, 300);
catEating = true;
}
```

**Comment by PathogenDavid** [comment] 2021-06-12 06:21
Next time, please don't disregard the issue template. A screenshot would've been helpful to clarify what your issue was, and if this were a bug the extra details would've been helpful.

The issue you're running into is that `ImageButton` widgets basically have two backgrounds: The button frame and the image background. This becomes more apparent if you look at the demo, which uses a solid black opaque background color:

![image](https://user-images.githubusercontent.com/278957/121766768-f29e1780-cb19-11eb-9bb1-5be149122fe0.png)

The problem is you're removing the image background color, but not the button frame.

The color of the button frame is determined by `ImGuiCol_Button`, `ImGuiCol_ButtonActive`, or `ImGuiCol_ButtonHovered` depending on the state of the button. So you can remove it with `PushStyleColor`. IE:

```cpp
ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0.f, 0.f, 0.f, 0.f));
ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(0.f, 0.f, 0.f, 0.f));
ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(0.f, 0.f, 0.f, 0.f));

if (ImGui::ImageButton(whiskas_cat_img, ImVec2((float)300, (float)50), ImVec2(0.0f, 0.0f), ImVec2(1.0f, 1.0f), 1, ImVec4(0.0f, 0.0f, 0.0f, 0.0f), ImVec4(1.0f, 1.0f, 1.0f, 1.0f))) {
    Beep(400, 300);
    catEating = true;
}

ImGui::PopStyleColor(3);
```

Applied to the demo, this results in buttons with no background whatsoever:

![image](https://user-images.githubusercontent.com/278957/121766939-ea92a780-cb1a-11eb-9d5b-b319539dba81.png)

----------------

Note that you might not want to remove `ImGuiCol_ButtonActive`/`ImGuiCol_ButtonHovered` entirely since without them there's no feedback to the user that your button is a button.

If you wanted to adjust the image tint instead for aesthetic reasons, you can either:

* Use `IsItemHovered` and `IsItemActive` with some extra state tracking.
* Implement your own `ImageButton` variant based on [the official implementation](https://github.com/ocornut/imgui/blob/d0c6dd9bafcfb0845153080fe00d74e62ad28c86/imgui_widgets.cpp#L1024-L1048).

**Comment by whiskasdietgirl** [comment] 2021-06-12 09:25
Thank you so much. That solved the problem.

**Comment by ocornut** [comment] 2021-06-14 09:19
Closing an answered. Thank you @PathogenDavid for the amazing answer, will be useful for future reference.

**Closed by ocornut** 2021-06-14 09:19 UTC
