### ISSUE TITLE
Crash when adding multiple ImGui::PlotLines to a window

### ISSUE THREAD

**Issue by kucoman** [ocornut/imgui#2272] opened 2019-01-11 17:34 UTC
**Version/Branch of Dear ImGui:**

Version: 1.66b (16602)
Branch: master

**Back-end/Renderer/Compiler/OS** 

Back-ends: custom
Compiler: GCC 4.8.4
Operating System: Ubuntu 

I am experiencing a crash when adding multiple ImGui::PlotLines to a window, using large arrays of float values. The crash can be reproduced in a slightly modified version of imgui_demo.cpp that I have attached.
[imgui_demo.cpp.zip](https://github.com/ocornut/imgui/files/2750572/imgui_demo.cpp.zip)

In short, I have added this code in the ImGui::PlotLines section:

        static float values[500] = { 0 };
        static int values_offset = 0;
        ImGui::PlotLines("Lines1", values, IM_ARRAYSIZE(values), values_offset, "avg 0.0", -1.0f, 1.0f, ImVec2(0,80));
        ImGui::PlotLines("Lines2", values, IM_ARRAYSIZE(values), values_offset, "avg 0.0", -1.0f, 1.0f, ImVec2(0,80));
        ImGui::PlotLines("Lines3", values, IM_ARRAYSIZE(values), values_offset, "avg 0.0", -1.0f, 1.0f, ImVec2(0,80));
        ImGui::PlotLines("Lines4", values, IM_ARRAYSIZE(values), values_offset, "avg 0.0", -1.0f, 1.0f, ImVec2(0,80));
        ImGui::PlotLines("Lines5", values, IM_ARRAYSIZE(values), values_offset, "avg 0.0", -1.0f, 1.0f, ImVec2(0,80));
        ImGui::PlotLines("Lines6", values, IM_ARRAYSIZE(values), values_offset, "avg 0.0", -1.0f, 1.0f, ImVec2(0,80));
        ImGui::PlotLines("Lines7", values, IM_ARRAYSIZE(values), values_offset, "avg 0.0", -1.0f, 1.0f, ImVec2(0,80));
        ImGui::PlotLines("Lines8", values, IM_ARRAYSIZE(values), values_offset, "avg 0.0", -1.0f, 1.0f, ImVec2(0,80));
        ImGui::PlotLines("Lines9", values, IM_ARRAYSIZE(values), values_offset, "avg 0.0", -1.0f, 1.0f, ImVec2(0,80));

The crash happens when all the widgets are shown in the running window. It happens inside while rendering. I have tried adding a different amount of extra PlotLines and using different array sizes with variable results.

Here is the drawing function I am using and the crash is happening in the glDrawElements() line :

void ImGui_RenderDrawLists(ImDrawData* draw_data){
  // Avoid rendering when minimized, scale coordinates for retina displays (screen coordinates != framebuffer coordinates)
  ImGuiIO& io = ImGui::GetIO();
  int fb_width = (int)(io.DisplaySize.x * io.DisplayFramebufferScale.x);
  int fb_height = (int)(io.DisplaySize.y * io.DisplayFramebufferScale.y);
  if (fb_width == 0 || fb_height == 0)
    return;
  draw_data->ScaleClipRects(io.DisplayFramebufferScale);

  // We are using the OpenGL fixed pipeline to make the example code simpler to read!
  // Setup render state: alpha-blending enabled, no face culling, no depth testing, scissor enabled, vertex/texcoord/color pointers.
  GLint last_texture; glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture);
  GLint last_viewport[4]; glGetIntegerv(GL_VIEWPORT, last_viewport);
  glPushAttrib(GL_ENABLE_BIT | GL_COLOR_BUFFER_BIT | GL_TRANSFORM_BIT);
  glPushClientAttrib(GL_CLIENT_ALL_ATTRIB_BITS);
  glEnable(GL_BLEND);
  glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
  glDisable(GL_CULL_FACE);
  glDisable(GL_DEPTH_TEST);
  glEnable(GL_SCISSOR_TEST);
  glDisable(GL_LIGHTING);
  glEnableClientState(GL_VERTEX_ARRAY);
  glEnableClientState(GL_TEXTURE_COORD_ARRAY);
  glEnableClientState(GL_COLOR_ARRAY);
  glEnable(GL_TEXTURE_2D);
  //glUseProgram(0); // You may want this if using this code in an OpenGL 3+ context

  // Setup viewport, orthographic projection matrix
  glViewport(0, 0, (GLsizei)fb_width, (GLsizei)fb_height);
  glMatrixMode(GL_PROJECTION);
  glPushMatrix();
  glLoadIdentity();
  glOrtho(0.0f, io.DisplaySize.x, io.DisplaySize.y, 0.0f, -1.0f, +1.0f);
  glMatrixMode(GL_MODELVIEW);
  glPushMatrix();
  glLoadIdentity();

  // Render command lists
#define OFFSETOF(TYPE, ELEMENT) ((size_t)&(((TYPE *)0)->ELEMENT))
  for (int n = 0; n < draw_data->CmdListsCount; n++){
    const ImDrawList* cmd_list = draw_data->CmdLists[n];
    const unsigned char* vtx_buffer = (const unsigned char*)&cmd_list->VtxBuffer.front();
    const ImDrawIdx* idx_buffer = &cmd_list->IdxBuffer.front();
    glVertexPointer(2, GL_FLOAT, sizeof(ImDrawVert), (void*)(vtx_buffer + OFFSETOF(ImDrawVert, pos)));
    glTexCoordPointer(2, GL_FLOAT, sizeof(ImDrawVert), (void*)(vtx_buffer + OFFSETOF(ImDrawVert, uv)));
    glColorPointer(4, GL_UNSIGNED_BYTE, sizeof(ImDrawVert), (void*)(vtx_buffer + OFFSETOF(ImDrawVert, col)));

    for (int cmd_i = 0; cmd_i < cmd_list->CmdBuffer.size(); cmd_i++){
      const ImDrawCmd* pcmd = &cmd_list->CmdBuffer[cmd_i];
      if (pcmd->UserCallback){
        pcmd->UserCallback(cmd_list, pcmd);
      } else {
        glBindTexture(GL_TEXTURE_2D, (GLuint)(intptr_t)pcmd->TextureId);
        glScissor((int)pcmd->ClipRect.x, (int)(fb_height - pcmd->ClipRect.w), (int)(pcmd->ClipRect.z - pcmd->ClipRect.x), (int)(pcmd->ClipRect.w - pcmd->ClipRect.y));
        glDrawElements(GL_TRIANGLES, (GLsizei)pcmd->ElemCount, sizeof(ImDrawIdx) == 2 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, idx_buffer);// Here the crash is happening.
      }
      idx_buffer += pcmd->ElemCount;
    }
  }
#undef OFFSETOF

  glBindTexture(GL_TEXTURE_2D, (GLuint)last_texture);
  glMatrixMode(GL_MODELVIEW);
  glPopMatrix();
  glMatrixMode(GL_PROJECTION);
  glPopMatrix();
  glPopAttrib();
  glPopClientAttrib();
  glViewport(last_viewport[0], last_viewport[1], (GLsizei)last_viewport[2], (GLsizei)last_viewport[3]);
}

I am not sure if this is reproducible in other machines/oss.

**Comment by ocornut** [comment] 2019-01-11 18:33
Hello,

I cannot reproduce an issue on my machine.
Does it reproduce **within the unmodified example app** (only modifying the demo code) and unmodified renderer e.g. imgui_impl_opengl2.cpp ?
Your renderer code above seems to be based on an old version of the GL2 renderer.

`glDrawElement()` would crash if indices were out of bound but I don't see a reason for this happening. unless there was a memory corruption or other changes in your app.
Even if you overflow the debug size of ImDrawIdx (>64k vertices per mesh), which should be caught by the IM_ASSERT call in `AddDrawListToDrawData()`, the mesh will be corrupted but still valid from GL point of view.

I would say it is probably a problem with your app or OpenGL driver.

**Comment by kucoman** [comment] 2019-01-11 20:03
True. I cannot reproduce the problem when modifying freeglut_opengl2 example.
I'll keep looking.
Thanks for checking.

**Comment by ocornut** [comment] 2019-01-12 10:38
Closing this for this.
You can reopen when you have a repro within one of the examples application.

**Closed by ocornut** 2019-01-12 10:38 UTC
Labels: plot/graph

**Comment by ocornut** [comment] 2019-01-12 14:33
Do you have asserts enabled? It looks like it the assert I mentioned and you can define ImDrawIdx to unsigned int to increase the maximum mesh size. But it should not crash OpenGL either way.

**Comment by kucoman** [comment] 2019-01-12 15:47
Yeah, the crash is very strange. It happens using ImDrawIdx as either short or int. I just started using OSG as a rendering engine, and I am probably missing something. I'll have to look deeper into the issue.

I get the assert triggered in OSX but not in Linux. I'll have to check my compiler settings. I'll post more info when I get to the cause of this.

Any input is welcome, though.
