### ISSUE TITLE
The first column of the table is overwritten when scrolling x.

### ISSUE THREAD

**Issue by coolxv** [ocornut/imgui#3389] opened 2020-08-06 08:36 UTC
**Version/Branch of Dear ImGui:**

Version: 1.78 WIP 
Branch: table + docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp

Operating System: Windows

**My Issue/Question:**

More than 10 columns

![20200806161849](https://user-images.githubusercontent.com/12321831/89508508-96cf7780-d800-11ea-9c34-d9d988cf4155.jpg)

![1](https://user-images.githubusercontent.com/12321831/89510165-d13a1400-d802-11ea-819d-4dcf2724043f.jpg)

![2](https://user-images.githubusercontent.com/12321831/89509152-853a9f80-d801-11ea-99b9-d3377b9cef4b.jpg)

**Comment by ocornut** [comment] 2020-08-06 09:23
Please provide code that I can paste into the demo to reproduce the issue.

**Comment by ocornut** [comment] 2020-08-06 12:23
I will close this now, and re-open if you can provide code to show the issue. Right now I can't reproduce it.

**Closed by ocornut** 2020-08-06 12:23 UTC
Labels: tables/columns
