### ISSUE TITLE
Modal window can not display when called by clicking menu item

### ISSUE THREAD

**Issue by maxint** [ocornut/imgui#1134] opened 2017-05-05 08:23 UTC
Using the latest code from master branch, the following code does not work.
```cpp
if (ImGui::BeginMainMenuBar())
{
    if (ImGui::BeginMenu("Help"))
    {
        if (ImGui::MenuItem("About...", "F1"))
            ImGui::OpenPopup("About");
        if (ImGui::BeginPopupModal("About", NULL, ImGuiWindowFlags_AlwaysAutoResize))
        {
            if (ImGui::Button("OK", ImVec2(120, 0))) { ImGui::CloseCurrentPopup(); }
            ImGui::EndPopup();
        }
        ImGui::EndMenu();
    }
    ImGui::EndMainMenuBar();
}
```
I check the source code of imgui. When "About..." menu item is clicked.
```cpp
// Automatically close popups
if (pressed && !(flags & ImGuiSelectableFlags_DontClosePopups) && (window->Flags & ImGuiWindowFlags_Popup))
    CloseCurrentPopup();
```
Then `IsPopupOpen()` check failed. as `g.OpenPopupStack.Size == g.CurrentPopupStack.Size` right now.
```cpp
static bool IsPopupOpen(ImGuiID id)
{
    ImGuiContext& g = *GImGui;
    return g.OpenPopupStack.Size > g.CurrentPopupStack.Size && g.OpenPopupStack[g.CurrentPopupStack.Size].PopupId == id;
}
```

**Comment by ocornut** [comment] 2017-05-05 08:49
1. The menu will be closed when you click the MenuItem(), so you cannot put BeginPopupModal() instead the menu `if` block.

2. There's another problem with mismatching ID which is not fully solved, see:
https://github.com/ocornut/imgui/issues/331

For now you should call OpenPopup() from the same scope you are calling BeginPopup().

Closing because duplicate of #331.

**Closed by ocornut** 2017-05-05 08:49 UTC

**Comment by maxint** [comment] 2017-05-05 11:34
Hi omar,
Thanks for your fast replay 😄  I will follow #331.
