### ISSUE TITLE
Combo box too large

### ISSUE THREAD

**Issue by jellythedoge** [ocornut/imgui#1342] opened 2017-09-29 07:34 UTC
I recently upgraded IMGUI and now i have an issue

https://gyazo.com/974bb4ce793ed5f4c0b012be6eae7b47

This never happened before the upgrade

**Comment by ocornut** [comment] 2017-09-29 13:10
Hello,
I did indeed made changes to the combo box code, but I cannot reproduce your bug.
Could you post a repro with your bug?
-Omar

Also please use the github attachment system when posting images (and not gyazo or other temporary hosting service), so discussions and bug reports are useful to others in the future.

**Comment by jellythedoge** [comment] 2017-10-01 22:26
I do not know what a Repro is but i can provide the code i used

`else if (tabSelected == 7) // Config
			{
				static int iConfigSelect = 0;
				static int iMenuTheme = 1;
				static char ConfigName[64] = { 0 };

				//ImGui::ShowTestWindow(); //DEBUG

				ImGui::ComboBoxArray("Select Config", &iConfigSelect, ConfigList);

				ImGui::Separator();

				if (ImGui::Button("Load Config"))
				{
					Settings::LoadSettings(BaseDir + "\\" + ConfigList[iConfigSelect]);
				}
				ImGui::SameLine();
				if (ImGui::Button("Save Config"))
				{
					Settings::SaveSettings(BaseDir + "\\" + ConfigList[iConfigSelect]);
				}
				ImGui::SameLine();
				if (ImGui::Button("Refresh Config List"))
				{
					RefreshConfigs();
				}

				ImGui::Separator();

				ImGui::InputText("Config Name", ConfigName, 64);

				if (ImGui::Button("Create & Save new Config"))
				{
					string ConfigFileName = ConfigName;

					if (ConfigFileName.size() < 1)
					{
						ConfigFileName = "settings";
					}

					Settings::SaveSettings(BaseDir + "\\" + ConfigFileName + ".ini");
					RefreshConfigs();
				}

				ImGui::Separator();

				const char* ThemesList[] = { "Default" , "Red" , "Pink", "Blue" };

				ImGui::Combo("Menu Color Theme", &iMenuTheme, ThemesList, IM_ARRAYSIZE(ThemesList));

				ImGui::Separator();

				if (ImGui::Button("Apply Theme"))
				{
					if (iMenuTheme == 0)
					{
						g_pGui->DefaultTheme();
					}
					else if (iMenuTheme == 1)
					{
						g_pGui->RedTheme();
					}
					else if (iMenuTheme == 2)
					{
						g_pGui->PinkTheme();
					}
					else if (iMenuTheme == 3)
					{
						g_pGui->BlueTheme();
					}
				}
			}

			ImGui::End();
		}
	}
}`

[IMGUI.tar.gz](https://github.com/ocornut/imgui/files/1347581/IMGUI.tar.gz) // This is the versions new and old

**Comment by ocornut** [comment] 2017-10-01 22:30
A repro is a way for us to reliably reproduce your issue, if possible trimmed down to the bare minimum needed to exhibit the issue.

**Comment by ocornut** [comment] 2017-10-26 14:36
@jellythedoge I have been unable to reproduce that bug locally.
If I use:

```
        ImGui::Begin("Bug #1342");
        int iMenuTheme = 0;
        const char* ThemesList[] = { "Default" , "Red" , "Pink", "Blue" };
        ImGui::Combo("Menu Color Theme", &iMenuTheme, ThemesList, 4);
        ImGui::End();
```

I get a correct height.
Does it still happen for you?
Could you post a GIF (you can use gifcam to capture) or video of the events leading to it?
Thanks.

**Comment by Bulb4** [comment] 2017-10-30 16:57
combo has the same size as `ImGui::GetStyle().WindowMinSize`.
i hope it will help.
sorry for my bad english.

**Comment by wi1h** [comment] 2017-10-30 16:59
use ImGui::PushItemWidth(num_pixels) and ImGui::PopItemWidth()

**Comment by ocornut** [comment] 2017-11-07 10:40
@jellythedoge Closing as missing repro.

**Closed by ocornut** 2017-11-07 10:40 UTC
