### ISSUE TITLE
Windows with ImGuiWindowFlags_AlwaysAutoResize stretch and resize when OS window is moved

### ISSUE THREAD

**Issue by chreden** [ocornut/imgui#5057] opened 2022-02-25 12:34 UTC
Firstly thanks for Dear ImGui - I have just switched my project over from my homemade UI and it's been incredibly easy to use and always seems to have an answer for everything I throw at it.

```
Dear ImGui 1.88 WIP (18709)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1930
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,708.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp 
Compiler: MSVC 2022
Operating System: Windows 10

**My Issue/Question:**

On the docking branch if an ImGui window has the flag `ImGuiWindowFlags_AlwaysAutoResize` and is contained within the host window (the Windows window) then when the host window is moved up or left then the window auto size calculation jumps to a large size and then shrinks back down to the correct size over the next frame or two. The same doesn't occur when moving down or right.

I have tried this on GLFW as well and reproduced it. I couldn't reproduce this on the master branch.

I have been trying to fix it but I haven't managed to yet. At this point the `IdealMaxPos` is the old bottom right of the ImGui window in screen coordinates before the host window was moved. I haven't been able to figure out where I would need to 'fix' this value by adjusting it - I suppose it would require ImGui to know that the window has been moved and that the coordinate system needs updating.

https://github.com/ocornut/imgui/blob/64519c6875fde64796aa1d098c02e1b346ac99fe/imgui.cpp#L5726-L5729

**Screenshots/Video**

I couldn't get it to appear on any recording as it happens too quickly, but it's visible to the eye and looks jarring especially when there are a lot of windows. I've added an artificial 1000ms sleep before each render in example in the video:

https://user-images.githubusercontent.com/4263940/155713595-62380450-f49e-4828-8916-451ee7ab94ba.mp4

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

The following example will be visible to the eye - a `Sleep` can be added if required to make it easier to track.

```
ImGui::Begin("Hello, world!", nullptr, ImGuiWindowFlags_AlwaysAutoResize);
const auto window = ImGui::GetCurrentWindow();
ImGui::Text("Current Window Size: %.3f, %.3f", window->Size.x, window->Size.y);
ImGui::End();
```

**Comment by ocornut** [comment] 2022-02-25 15:44
Thank you for reporting this!
This was caused by a missing offset in `TranslateWindow()`. In theory `TranslateWindow()` and `SetWindowPos()` should share more code but there are subtleties that needs verification, so for now I added a fix + commentary.
Fixed by 8639a2f

Amend 6af92b0 and a3f03933

**Closed by ocornut** 2022-02-25 15:44 UTC
Labels: bug, multi-viewports
