### ISSUE TITLE
Issues with docking in window with no padding

### ISSUE THREAD

**Issue by leiradel** [ocornut/imgui#2717] opened 2019-08-07 21:30 UTC
**Version/Branch of Dear ImGui:**

Version: v1.72b
Branch: docking

```
Dear ImGui 1.72b (17202)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201103
define: __linux__
define: __GNUC__=7
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl2
io.ConfigFlags: 0x00000040
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.BackendFlags: 0x00001402
 HasMouseCursors
 PlatformHasViewports
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 1024,2048
io.DisplaySize: 1213.00,665.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl2.cpp
Compiler: gcc 7.4.0
Operating System: Ubuntu 18.04.2 LTS 64-bit

**My Issue/Question:**

I'm trying to make an invible window that stays in the background and takes the entire app window size to serve as a base where other windows can dock.

Everything works fine but when I try to remove the padding from that window, the first window that is docked is maximized instead.

**Screenshots/Video**

1. Drag a window by the title

![Screenshot from 2019-08-07 22-20-12](https://user-images.githubusercontent.com/357536/62659171-8ae97500-b962-11e9-844a-6e331c81dcf7.png)

2. Dock it anywhere

![Screenshot from 2019-08-07 22-20-28](https://user-images.githubusercontent.com/357536/62659183-93da4680-b962-11e9-8ff4-e75e81875844.png)

3. It will become maximized instead of docked

![Screenshot from 2019-08-07 22-20-32](https://user-images.githubusercontent.com/357536/62659194-9c328180-b962-11e9-868a-0da320248a09.png)

**Standalone, minimal, complete and verifiable example:**

[Here](https://gist.github.com/leiradel/658d2225898b12c0be399dcd4af1d4a8).

**Comment by leiradel** [comment] 2019-08-07 21:38
What I'm trying to accomplish with that window is just having a dock space that covers the entire app window. I know I can dock windows into one another, but then I have to manually resize everything to try to cover the entire client area of the app window.

**Comment by ocornut** [comment] 2019-08-07 21:44
Thanks Andre, i don’t have the code in front of me so full answer is probably going to have to wait a few days. At a glance your code seems right so I wouldn’t rule out the possibility of a bug.

Please note that there is a function, i think called DockspaceOverViewport() function that does essentially what you are trying to do, and looking at it you may discover some meaningful difference.

**Comment by leiradel** [comment] 2019-08-07 22:36
The code is similar but uses `PushStyleVar` instead of messing with things in `GetStyle()`. However, `DockSpaceOverViewport()` does exactly what I need and works like a charm. Thanks!

I'll leave this open since there may be a bug, like you said.

**Comment by ocornut** [comment] 2020-10-15 18:24
This got fixed by @Black-Cat in #3519, apologies for not reacting on this since you found `DockSpaceOverViewport().

The reason I couldn't immediately understand the issue is that it would only happen if the host window doesn't have the `ImGuiWindowFlags_NoDocking` flags, which is kind of a user-error. But as you showed the resulting error was quite confusing and could be misleading.

I will also alter the Demo to point users toward `DockSpaceOverViewport()`. Since 1.76 it plays nicely with main menu bar and I think the only reason the demo doesn't use it right now is because it wants a local menu bar. Going to try to see if I can simply use DockSpaceOverViewport() directly..

**Closed by ocornut** 2020-10-15 18:24 UTC
Labels: docking, drag drop

**Comment by ocornut** [comment] 2020-10-15 18:39
I will be adding this comment at the top of `ShowExampleAppDockSpace()`:

```
// In 99% case you should be able to just call DockSpaceOverViewport() and ignore all the code below!
// In this specific demo, we are not using DockSpaceOverViewport() because:
// - we allow the host window to be floating/moveable instead of filling the viewport (when opt_fullscreen == false)
// - we allow the host window to have padding (when opt_padding == true)
// - we have a local menu bar in the host window (vs. you could use BeginMainMenuBar() + DockSpaceOverViewport() in your code!)
// TL;DR; this demo is more complicated than what you would normally use.
// If we removed all the options we are showcasing, this demo would become:
//     void ShowExampleAppDockSpace()
//     {
//         ImGui::DockSpaceOverViewport(ImGui::GetMainViewport());
//     }
```

**Comment by leiradel** [comment] 2020-10-16 07:42
> apologies for not reacting on this since you found `DockSpaceOverViewport().

No problem, I'm glad it's fixed.
