### ISSUE TITLE
Dual screen HiDPI and regular DPI

### ISSUE THREAD

**Issue by hateom** [ocornut/imgui#1693] opened 2018-03-24 13:04 UTC
Hi,

I have an issue on mac with dual screen setup where one screen is retina display (HiDPI) and the other one is regular DPI.
When the window with ImGUI is moved to the other display the UI get scaled 50% down to the lower bottom corner.
How to properly handle this? I'm using QT and OpenGL3 custom implementation.

**Comment by ocornut** [comment] 2018-03-24 13:11
Hello,
Closing as duplicate of #1676, please post your questions or feedback there.
As the moment with the current master branch (single viewport) you can handle this on the application side. Check the current DPI and when it changes you can recreate the fonts are a different size and recreate the style using a base style + `ImGuiStyle::ScaleAllSizes()`.

**Closed by ocornut** 2018-03-24 13:11 UTC
