### ISSUE TITLE
Viewports: windows detach from the main viewport when not fitting

### ISSUE THREAD

**Issue by r-lyeh** [ocornut/imgui#2369] opened 2019-02-20 12:50 UTC
Is this as designed?

Repro steps: Resize quickly client window from bottom-right corner to a smaller dimension. Notice all floating tabs get undocked automatically. 

Also, they dock automatically too if you do inverse actions. See end of gif.

Environment: 1.68 wip + docking + viewports + example application + glfw3 (master) + gl3.

![gif](https://user-images.githubusercontent.com/35402248/53093015-7fba9e00-3516-11e9-9bb0-a2f6542e1743.gif)

**Comment by ocornut** [comment] 2019-02-20 13:20
This has nothing to do with "docking" / "undocking". It is the behavior of the multi-viewport feature to treat floating windows as independant of the main window.

**Comment by ocornut** [comment] 2019-02-25 14:16
Closing this as "by design". We could potentially design newer feature to lock specific window to a given host viewport (ideally via a end-user interface), which would work better than the early design which had harder-to-comprehent state (a simple click on a window would get it temporarily out of the viewport).

**Closed by ocornut** 2019-02-25 14:16 UTC
Labels: viewport
