### ISSUE TITLE
Modal is closed when doing an Alt-Tab to another window not in its hierarchy

### ISSUE THREAD

**Issue by arnaud-neny** [ocornut/imgui#6357] opened 2023-04-21 14:11 UTC
**Version/Branch of Dear ImGui:**

Version: 1.89.5
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx12.cpp
Compiler: VS 2022
Operating System: Windows 10

**My Issue/Question:**

When having a popup modal opened in a separate window, and it has not having the focus, doing a alt-tab to another window not in its hierarchy is getting it closed.
(Open the demo, open a "Delete..." modal, make all windows popped out, click on the main window, Alt-Tab to "Dear ImGui Window", and the modal get closed).

**Comment by ocornut** [comment] 2023-04-21 14:20
Seems like a regression caused by https://github.com/ocornut/imgui/issues/6299#issuecomment-1499174189
Working on it!

**Comment by ocornut** [comment] 2023-04-21 17:21
I have pushed a fix for this, it comes a series of commits, mainly 30eceaf, 01ca196, 4d42450, ending with d76699b.

There was a much needed refactor of whose responsibility it is to check for the presence of blocking modal before a focus change and this allowed me to start doing this refactor. I think there's more to do on that topic (other than your specific issue) but I will need to wait until we have a more serious battery of regression tests around this.

Specifically, my general plan is:
- The newly added `ImGuiFocusRequestFlags_UnlessBelowModal` flag should probably be made opposite to be opt-out instead of opt-in. But we'll need to double check and add regression tests for as many `FocusWindow()` calling paths as possible before.
- This should eventually be exposed into public facing API such as `SetNextWindowFocus()`.

**Closed by ocornut** 2023-04-21 17:21 UTC
Labels: bug, focus, multi-viewports
