### ISSUE TITLE
GetContentRegionMaxAbs / GetContentRegionAvail incorrect when within end column

### ISSUE THREAD

**Issue by deltars** [ocornut/imgui#2666] opened 2019-07-14 09:17 UTC
It's me again,

Really minor issue, GetContentRegionAvail returns a region that is a touch too narrow when inside the end column, as padding is removed from the back edge.

I would suggest simply checking we are not in the end column.

I hope this helps!

thanks

```
ImVec2 ImGui::GetContentRegionMaxAbs()
{
    ImGuiWindow* window = GImGui->CurrentWindow;
    ImVec2 mx = window->ContentsRegionRect.Max;
    if (window->DC.CurrentColumns)
        mx.x = window->Pos.x + GetColumnOffset(window->DC.CurrentColumns->Current + 1) - window->WindowPadding.x;
    return mx;
}
```

Please consider changing to:

```
ImVec2 ImGui::GetContentRegionMaxAbs()
{
    ImGuiWindow* window = GImGui->CurrentWindow;
    ImVec2 mx = window->ContentsRegionRect.Max;
    if (window->DC.CurrentColumns && window->DC.CurrentColumns->Current + 1 < window->DC.CurrentColumns->Count)
        mx.x = window->Pos.x + GetColumnOffset(window->DC.CurrentColumns->Current + 1) - window->WindowPadding.x;
    return mx;
}
```

**Comment by ocornut** [comment] 2019-07-14 16:40
Hello,

As with your previous issue, please clarify what you expect is "correct" and why.

The current behavior is designed so that all columns are of equal width and have equal amount of available space.
If we add a `ImGui::Text("Avail %.2f", ImGui::GetContentRegionAvail().x);` in the Column demo you can see it:

![image](https://user-images.githubusercontent.com/8225057/61186502-15b4a980-a61b-11e9-9cf7-069f64756b1a.png)

Based on this criteria, your proposed fix would be incorrect.

It may be misleading because Columns currently don't have an easy way to display outer borders (on the left and the right), something with the upcoming Tables/ColumnV2 system will allow more easily.

**Comment by deltars** [comment] 2019-07-15 17:43
Hello,

Yes I understand, I could be much clearer.

Just to clarify, I think this is a minor issue / perhaps just a taste thing and doesn't necessarily need changing, depending on your view. Also, maybe I am using the wrong layout mechanism for what I am trying to do.

What i would expect:

![imgui_gif](https://user-images.githubusercontent.com/15377930/61236480-04a98c80-a730-11e9-9b94-1867fa392012.gif)

My actual use case (with the suggested code change as above):

![Screenshot (22)](https://user-images.githubusercontent.com/15377930/61236510-125f1200-a730-11e9-8204-cbee120a197b.png)

Perhaps the problem is more that I am using column layout and thats not really the best way to achieve what I am trying to do?

**Comment by ocornut** [comment] 2019-07-17 22:16
Let me investigate, I looked at this and there's definitively a larger bug than that with how `WindowPadding` is presently affecting columns (I think this is a bug added in 1.71 while refactoring the contents/work rectangle system).

**Comment by ocornut** [comment] 2019-07-18 01:53
One of the problem this was trying to solve was to ensure that the clipping rectangle width would match. So if you have large (too wide) items in every column, they would appear clipped the same way. 
The problem is that without this padding, the right side of right-most column would start overlapping beyond the current window clipping rectangle (which is generally WindowPadding*0.5f within the InnerRect).

I made two fixes now, and one pushes the right-most up to the clipping region so we're saving WindowPadding.x*0.5 (4 pixels with the default style). 

There's still another gap of WindowPadding.x*0.5 (4 pixels) + the fact that if you have a scrollbar and your ScrollbarBg is transparent it looks like there's a little more space on the right side (2-3 pixels) + the fact that with a scrollbar the outer window border will cover the left side of the contents area but not the right side (an extra +1 pixel). 

I would like to get rid fo the half-window-padding-clipping thing eventually but that'll require other changes.

(I like your screenshot but I have absolutely no idea what to look for in it. I cannot even see a column delimiter in that screenshot.)

**Comment by deltars** [comment] 2019-07-18 23:36
thank you for the fixes.

(My screenshot is our skeletal animation / pose editor. The styling has some lines hidden and most margins set quite small. We have custom icon buttons, and render target widget which uses a persistent render target object for containing the actual render target and input callbacks but otherwise runs as intermediate.)

![Screenshot (24)](https://user-images.githubusercontent.com/15377930/61498944-400cbb00-a9bd-11e9-849d-566522fd701a.png)

**Comment by ocornut** [comment] 2019-07-19 02:06
One of the project i'm working with seems to have detected a regression caused by the changes I made yesterday, so I'm opening this again until they are fixed.

**Comment by ocornut** [comment] 2019-07-19 21:35
Should be fixed now!

**Closed by ocornut** 2019-07-19 21:35 UTC
Labels: bug, columns
