### ISSUE TITLE
"Infinite" drag on ::Drag*(..)

### ISSUE THREAD

**Issue by phed** [ocornut/imgui#1053] opened 2017-03-03 03:42 UTC
This is a very platform dependent issue, and also complicated with regards to making the bookkeeping work fine. I haven't done any deep experiments myself, but I don't think it should be too tricky to do myself. But I am just fishing to see if anyone else has thought about it.

When using a drag-widget, you will easily hit the edge of the screen if the widget is placed on the edge. The natural thing would be to hide and lock the cursor in place. Some environments supports this, while I believe Wayland famously doesn't. When releasing the button you would show the cursor again. A corner-case is that you would have to release the lock if the widget is not drawn on a subsequent frame (and there might be other cases as well).

So, I have been thinking of a way ways to implement this on the user-side, but I haven't quite managed to decide if it is even worth trying since I could easily create cases where the widget is not drawn anymore and it all gets hairy. Anyone else done this?

I am sorry if this is a dupe, but I did a cursory review.

**Comment by ocornut** [comment] 2017-03-13 17:51
Duplicate of #821

After merging the gamepad branch we could consider adding something like that, it may need some subsequent IO to let the application know we are dragging and give it a chance to hide the cursor.

(Note that you can use Shift/Alt to fasten/slow down the dragging, and ctrl+click or double-click to input a text value with the keyboard as well!)

**Comment by ocornut** [comment] 2017-03-16 08:56
Closing duplicate.

**Closed by ocornut** 2017-03-16 08:56 UTC
