### ISSUE TITLE
CloseCurrentPopup() closes all stacked modal Popups when left mouse button is clicked on non-widget space

### ISSUE THREAD

**Issue by elvissteinjr** [ocornut/imgui#2880] opened 2019-11-03 02:38 UTC
**Version/Branch of Dear ImGui:**

Version: 1.73
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Compiler: MSVC15
Operating System: Windows 10

**My Issue/Question:**

I realize what I'm doing might be considered too specialized and there's a workaround, but I still found the behavior odd.

My goal is to have a modal popup, which was opened from another modal popup, take any keyboard/mouse input, then close it. For input binding purposes.
This works fine unless the left mouse click is used on the popup window itself and no widget takes the input. In that case, all popups are closed.

A workaround is to delay closing to the next frame, so it's not a huge deal. Still thought I should perhaps report it anyways. I'm also somewhat new to Dear ImGui, so I hope I didn't miss something obvious here.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
ImGui::Begin("Stacked Modal Popups");

    if (ImGui::Button("Open Modal Popup 1"))
    {
        ImGui::OpenPopup("Popup1");
    }

    if (ImGui::BeginPopupModal("Popup1"))
    {
        if (ImGui::Button("Open Modal Popup 2"))
        {
            ImGui::OpenPopup("Popup2");
        }

        if (ImGui::BeginPopupModal("Popup2"))
        {
            ImGui::Text("Click anywhere");

            if (ImGui::IsMouseClicked(0))
            {
                ImGui::CloseCurrentPopup();
            }

            ImGui::EndPopup();
        }

        ImGui::EndPopup();
    }

ImGui::End();
```

**Comment by ocornut** [comment] 2020-06-16 13:37
I looked into it and the problem is that `CloseCurrentPopup()` does mark "Popup2" as closed in `g.OpenPopupStack`, but at the same time at the end of frame we detect the click on `Popup2` which leads to `StartMouseMovingWindow` > `FocusWindow` > `ClosePopupsOverWindow` and at that point Popup2 is not marked as an open popup so considered a regular window and therefore it consider `Popup1` as a popup to close.

Trying to think of a fix.

**Comment by ocornut** [comment] 2020-06-16 15:13
I explored various way and found a suitable fix for it, now pushed.
Thanks for reporting this!

**Closed by ocornut** 2020-06-16 15:13 UTC
Labels: popups
