### ISSUE TITLE
Conflicted inputs can't use ctrl+click

### ISSUE THREAD

**Issue by Sven-vh** [ocornut/imgui#8092] opened 2024-10-23 14:57 UTC
### Version/Branch of Dear ImGui:

Version 1.88, Branch: docking

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp

### Compiler, OS:

Windows 10 + MSVC 2022

### Details:

When you have an ID conflict, ctrl+click doesn't work. It only allows you to edit it on the last one.

I use ID conflicts for my game engine so that if I have multiple entities selected, and you change the value of one of them, they all change.

### Screenshots/Video:

![github issue](https://github.com/user-attachments/assets/3db1af38-0ac3-4355-9193-b6e6a52305e1)

### Minimal, Complete and Verifiable Example code:

```cpp
ImGui::Begin("Example Bug");
static int test = 0;
ImGui::DragInt("test", &test);
ImGui::DragInt("test", &test);
ImGui::DragInt("test", &test);
ImGui::End();
```

**Comment by ocornut** [comment] 2024-10-23 16:43
> i use ID conflicts for my game engine so that if I have multiple entities selected, and you change the value of one of them, they all change.

This is incorrect use and was never formally supported.
How about exposing one widget and looping to copy the value to all your selection?

**Comment by ocornut** [comment] 2024-11-07 14:01
Closing this as by design. You shouldn't ever need to use conflicted inputs.

**Closed by ocornut** 2024-11-07 14:01 UTC
Labels: label/id and id stack
