### ISSUE TITLE
Can't compile ImGui::GetWindowFont because of Windows.h conflict

### ISSUE THREAD

**Issue by nguillemot** [ocornut/imgui#340] opened 2015-09-19 02:07 UTC
The following function declaration in `imgui.h`

    IMGUI_API ImFont*       GetWindowFont();

cannot be compiled if `Windows.h` was included before `imgui.h`, because `Windows.h` defines a macro with the name `GetWindowFont`.

I suggest renaming it so it doesn't conflict, for the convenience of Windows users.

**Comment by paulsapps** [comment] 2015-09-19 09:19
Or just have some #ifdefs to undefine GetWindowFont and then restore it after the definition

**Comment by ocornut** [comment] 2015-09-19 10:15
I'm not sure how to fix that without renaming. Are you including windows.h in LEAN_AND_MEAN mode?
Trying to undef and redef to whatever is done in windows.h is asking for trouble with different versions of the standard librairies, their declaration aren't trivial.

That said I was considering renaming this function..

**Comment by paulsapps** [comment] 2015-09-20 10:55
Couldn't you do something like:

// Save the old macro value
#define TEMP_GetWindowFont  GetWindowFont 

// Remove windows.h conflict
#undef GetWindowFont 

// Now this should work
void GetWindowFont () {} 

// Put it back
#define GetWindowFont TEMP_GetWindowFont  

// Remove temp macro
#undef TEMP_GetWindowFont  

The problem is that every winapi has a macro like this to define GetWindowFont  as GetWindowFontA or GetWindowFontW and a lot of the names are very generic.

**Comment by ocornut** [comment] 2015-09-20 11:16
That wouldn't work with the C/C++ preprocessor.

**Comment by adam4813** [comment] 2015-09-20 11:20
The simplest solution is to include imgui before windows.h or whatever else
is including it, or isolate your gui code away from the others and just
include your gui class into where you use it. Then in your gui class file
you include only imgui.

**Comment by ongamex** [comment] 2015-10-18 18:18
Renaming is the only real option to me.. otherwise you could change the declaration and the definition of the function in order to keep the same name to:

IMGUI_API ImFont*       (GetWindowFont)();
ImFont* (ImGui::GetWindowFont)() {

This will prevent the preprocessor to expand the GetWindowFont macro becase it has arguments and it's not followed by '('

**Comment by ocornut** [comment] 2015-10-18 19:03
Where is this macro exactly defined?
Including Windows.h work for me here (MSVC10).
Looking for GetWindowFont I don't mind references to it.. this issue is NUMBER 2 on Google for this name.

**Comment by ocornut** [comment] 2015-10-18 19:06
OK it's in <windowsx.h> for me in Windows SDK 5.0, 7.0A and 7.1A. Not in 8.0 8.0A 8.1 8.1A.
I suppose it is a rarely used old macro. Couldn't you just undef it ?

**Comment by ongamex** [comment] 2015-10-18 19:18
GetWindowFont is defined in windowsx.h

**Comment by ocornut** [comment] 2015-10-18 19:19
#undef GetWindowFont
You don't need, it's an old macro.

**Comment by ongamex** [comment] 2015-10-18 22:57
This is a wrong decision in my opinion, but after all the code is yours.

**Comment by adam4813** [comment] 2015-10-18 23:28
Could it simply be renamed to GetFont() ?

**Comment by ocornut** [comment] 2015-10-19 08:42
I can and I want to rename it but i'll still need to keep a legacy redirect so not to break people programs, so that won't solve your problem.

**Comment by nguillemot** [comment] 2015-10-20 00:36
My current workaround is just to undef it. Yeah, it's coming from windowsx.h.
FWIW, I don't actually use GetWindowFont(). It's just slightly ugly to have to undef it manually.

**Comment by ocornut** [comment] 2015-10-21 09:42
I agree. When I rename the function and had a temporary redirect I'll do the #undef in imgui (at least the uglyness won't be felt by the users - and nearly no one uses this old Windows helper macro it seems).

**Comment by brainiac** [comment] 2015-10-22 06:27
I've used something like this in in other projects. Not specifically for GetWindowFont, so not sure if it'll work in this exact case.

    #ifdef GetWindowFont
    #undef GetWindowFont
    inline HFONT GetWindowFont(WHND hWnd)
    {
        return FORWARD_WM_GETFONT(hWnd, SNDMSG)
    }
    #endif

basically its just replacing the macro with an inline function.

**Comment by ocornut** [comment] 2015-11-29 22:02
Closing this now (need to keep the issue list manageable), as the work-around is acceptable and newer windows/sdk don't have this function afaik. I kept note to do the renaming but that will come with larger renaming.

**Closed by ocornut** 2015-11-29 22:02 UTC
