### ISSUE TITLE
Decimal char '.' and ','

### ISSUE THREAD

**Issue by adamsepp** [ocornut/imgui#6719] opened 2023-08-14 16:47 UTC
Hello,

Version:  v1.89 WIP
Branch: Docking
Operating System: Win10 / Win11

Question / Suggestion:
I support both inputs: english '.' and german ',' decimal signs
but output always to english '.' decimal sign.

My current solution is the line:
`if ((c == '.') || (c == ',')) *p_char = c = c_decimal_point; // cheeting for both decimal sign types...`

Complete code part:
```
// Allow 0-9 . - + * /
if (flags & ImGuiInputTextFlags_CharsDecimal)
{
     if ((c == '.') || (c == ',')) *p_char = c = c_decimal_point; // cheeting for both decimal sign types...
       if (!(c >= '0' && c <= '9') && (c != c_decimal_point) && (c != '-') && (c != '+') && (c != '*') && (c != '/'))
          return false;
}

// Allow 0-9 . - + * / e E
if (flags & ImGuiInputTextFlags_CharsScientific)
{
     if ((c == '.') || (c == ',')) *p_char = c = c_decimal_point; // cheeting for both decimal sign types...
        if (!(c >= '0' && c <= '9') && (c != c_decimal_point) && (c != '-') && (c != '+') && (c != '*') && (c != '/') && (c != 'e') && (c != 'E'))
         return false;
}
```

So far this is working out great for both user types (german and english keyboard).

@ocornut 
first of all: ImGui is really awesome!
It would be nice if something like this already in the ImGui project, but I also understand that this might be too specific...?

_Originally posted by @adamsepp in https://github.com/ocornut/imgui/issues/2278#issuecomment-1662863362_

**Comment by ocornut** [comment] 2023-08-15 08:58
> but output always to english '.' decimal sign.

I think the problem is that `scanf()` also uses the local decimal point but it cannot be that, but your code seems to do the right thing on that.

I would need to think a little more in-depth about all possible side-effects of enabling this behavior, your help there would be appreciated.

**Comment by GamingMinds-DanielC** [comment] 2023-08-15 09:47
That would be very useful indeed. Also a German keyboard layout here, and the number block on the right side of the keyboard only has the comma, not the point. And there is good reason to not switch the locale to match.

> I would need to think a little more in-depth about all possible side-effects of enabling this behavior, your help there would be appreciated.

There is a simple way to mitigate side effects entirely and make it even more flexible for users of other locales. As a suggestion for `imconfig.h`:
```c++
// Uncomment to add an alternate char that will automatically be replaced by the current locale's decimal point
// when entered into a text field using ImGuiInputTextFlags_CharsDecimal or ImGuiInputTextFlags_CharsScientific.
//#define IMGUI_ALTERNATE_DECIMAL_POINT ','
```

**Comment by ocornut** [comment] 2023-08-15 10:05
> There is a simple way to mitigate side effects entirely and make it even more flexible for users of other locales. As a suggestion for imconfig.h:

Adding that can be configured at runtime is best in ImGuiIO so I guess that would work as an ImGuiIO flag.

But I believe it would be greater if we can just auto-solve it for everyone, and maybe the suggested change is the best one we can do. We have to consider e.g. non German developers shipping apps that German layout users would run.

I just need us to think a little harder as how it might affect all sorts of users, to find if there are any negative side-effects to it.

For example, in French or other languages there is a tendency to separate thousands using `,` e.g. one million is `1,000,000`.
While technically that's not how we input values in InputText(), in which scenario would this interact with suggested change?

Stuff like this also apparently exists:
https://stackoverflow.com/questions/28744647/set-thousands-separator-for-c-printf
But it's not supported by Visual Studio's printf apparently, which tells us that it's unlikely that dear imgui users have been using it.

**Comment by GamingMinds-DanielC** [comment] 2023-08-15 11:25
> For example, in French or other languages there is a tendency to separate thousands using `,` e.g. one million is `1,000,000`.

Worse still: in Germany we officially separate thousands with the decimal point, one million would be `1.000.000` (or `1.000.000,0` as a float) if we actually used our locale.

**Comment by adamsepp** [comment] 2023-08-15 16:45
> But I believe it would be greater if we can just auto-solve it for everyone
Yes this would be the ideal case. Or at least this was the idea of the changes I posted.

On my side it worked out great since ~1year and as @GamingMinds-DanielC mentioned it is quite handy if you have german layout with numblock...
(From technical side I'm working with people from North America, Europe and Asia and usually they all use the US way without a thousand separator for any communication/documentation)

In my opinion the only side effect to be concerned about is the thousand separator (as you 2 already mentioned).
Thx @ocornut for this link. I didn't know that on linux you can use the apostrophe flag to print the thousand separator.
(I tried it on windows `snprintf(test, sizeof(test),"test = %'d", testValue);,` and there it is not possible, I get:
`warning C4476: 'snprintf' : unknown type field character ''' in format specifier`
The only page I could find the apostrophe description: https://en.wikipedia.org/wiki/Printf
([cplusplus.com/reference/cstdio/printf/](https://cplusplus.com/reference/cstdio/printf/) does not list that)

Thees 2 points might help for the decision:
- ImGui does not support thousand separator in any control (so far as I know)
  -> And since ImGui::ImFormatStringV() is using vsnprintf() it will most likes remain this way. (which is good :-))
- The proposal code is only converting ',' and '.' to the default separator. (so the default separator is still in use like before)
  (Using another decimal separator other than '.' is possible, but since printf() is in use, ImGui will always display '.' anyhow)

**Comment by ocornut** [comment] 2023-08-17 11:13
That [stb_printf](https://github.com/nothings/stb/blob/master/stb_sprintf.h) also supports the `'` format flag.
But using `'` would need a sscanf implementation that supports it.

I applied your change (a1a7a1bc03) as an attempt to find out if this could cause problems.
I also moved `PlatformLocaleDecimalPoint` to the public ImGuiIO structure, allowing backends to potentially better support it.

**Comment by GamingMinds-DanielC** [comment] 2024-03-11 14:08
Just noticed that we lost this functionality again with https://github.com/ocornut/imgui/commit/4a2426449a4c65028c65c68ed9426495dec251e4, as the decimal point substitution was implemented in the now removed filtering. When tracking down which commit "broke" it, I was hoping to find a fixable bug. Instead I found a deliberate change to fix other (also valid) issues. Well, I hope to see this neat little feature again someday.

**Comment by ocornut** [comment] 2024-03-11 14:14
I am happy to reinstate the call for the purpose of that specific swapping (with no other filter), do you think you could do a PR for it?

**Comment by GamingMinds-DanielC** [comment] 2024-03-11 14:44
I did take a look at the code after tracking down the relevant commit, but I don't see a clean way to do it. I can make a PR soon, but I will need to extend `ImGuiInputTextFlagsPrivate_` (not many bits left) by one entry to do this without braking something else.

**Comment by ocornut** [comment] 2024-04-03 02:42
Fixed by 4a2426449a4c65028c65c68ed9426495dec251e4, thank you @GamingMinds-DanielC

**Closed by ocornut** 2024-04-03 02:42 UTC
Labels: inputtext

**Comment by ocornut** [comment] 2024-08-22 18:46
FYI in today's change the storage of `io.PlatformLocaleDecimalPoint` has moved:
`GetIO().PlatformLocaleDecimalPoint` --> `GetPlatformIO().Platform_LocaleDecimalPoint`

**Comment by iiinjoy** [comment] 2024-09-02 06:42
Addition: when using [stb_printf](https://github.com/nothings/stb/blob/master/stb_sprintf.h), the decimal separator is set as follows:
```c++
    char decimal_point = *localeconv()->decimal_point;
    platform_io.Platform_LocaleDecimalPoint = decimal_point;

    stbsp_set_separators(',', decimal_point);
```
