### ISSUE TITLE
Docking the window changes it's alpha value

### ISSUE THREAD

**Issue by gamehacker1999** [ocornut/imgui#3767] opened 2021-01-29 00:41 UTC
Version: 1.8
Branch: docking

Back-ends: imgui_impl_DX12_cpp + imgui_impl_Win32.cpp 
Operating System: Windows

I set a flag NoBackgroundColor for a window. However when another window is docked to it, it completely ignores that flag and inherites the alpha value from the docked window. Is there a solution or workaround for that?

**Comment by Jamesmorgan0233** [comment] 2021-01-29 00:43
What are you talking about

**Comment by PathogenDavid** [comment] 2021-01-29 02:50
If I'm not mistaken this is related to https://github.com/ocornut/imgui/issues/2700#issuecomment-762851523

**Comment by Jamesmorgan0233** [comment] 2021-01-29 06:59
Ok

**Comment by ocornut** [comment] 2021-02-01 15:15
Closing as duplicate of #2700

**Closed by ocornut** 2021-02-01 15:15 UTC
