### ISSUE TITLE
Need help integrating ImGui into a Win32 application

### ISSUE THREAD

**Issue by Supabyte** [ocornut/imgui#1196] opened 2017-06-22 17:01 UTC
Hey,

I'm not sure if this is the right place to post this, but I couldn't find a more appropriate forum.

I've been using ImGui for a good while now and really enjoy using it, but I've come across a problem with integrating it into an existing Win32 application of mine, a sort of framework for creating physics & biology animations, frame by frame, and allowing you to export different simulations as AVI's and GIF's.

Each simulation is different, and requires it's own customisable 'Control Panel' window for tweaking all the different variables involved for each simulation, and I think ImGui would be the **perfect** tool for the job - i.e. Rapid UI development for each individual simulation. which will consist of mostly sliders, numeric input boxes, adjustable graphs, check-boxes, lists, trees, collapsible headers, etc.

Now, I've had an attempt at this already, but have not found a working solution yet. I have looked at the examples, and can create a standalone Win32 application with OpenGL &  ImGui, but **my problem is this:** How do I create a **child** Win32 Window, and initializing OpenGL & ImGui to run on it.?

Stripped down code example:

```
void MySimulation1::RenderControlPanel()
{
	ImGui::Begin();

	// GUI for this simulation, to be rendered in child window

	ImGui::End();
}

int CALLBACK ChildProc( HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam )
{
	switch ( msg )
	{
		case WM_INITDIALOG:
		{
			// How do I initialize OpenGL & ImGui here?
    		}
    		break;

    		default:
        		return 0;
	}
	return 1;
}

LRESULT CALLBACK WndProc(
	HWND hwnd,
	UINT msg,
	WPARAM wParam,
	LPARAM lParam )
{
	switch ( msg )
	{
		case WM_CREATE:
		{
			// Create New Child window here...
			g_hControlPanel = CreateDialog( g_hInstance, MAKEINTRESOURCE( IDD_CONTROL_PANEL ), hwnd, ChildProc );
		}
		break;

		case WM_CLOSE:
		{
			DestroyWindow( hwnd );
		}
		break;

		case WM_DESTROY:
		{
			PostQuitMessage( 0 );
		}
		break;

		default:
		{
			return DefWindowProc( hwnd, msg, wParam, lParam );
		}
	}
	return 0;
}

```

**Comment by ocornut** [comment] 2017-06-22 17:07
1.
> "The main problem is this: How do I create a child Win32 window, initialize that child window to use OpenGL or SDL or whatever,"

this question has nothing to do with imgui. Rather OpenGL or SDL.

2.
We provide example to do exactly that for both GLFW+GL or SDL. Just create more GL windows if you need more windows.

**Comment by Supabyte** [comment] 2017-06-22 17:48
I edited my original post a bit to include a stripped down example of what I'm trying to do, I hit submit by mistake before having time to finish my post.

I'll keep trying at it. I was able to create a window, set up and render ImGui with no problems, I just can't seem to make it a popup child of my main window, and I don't really know the best way to accomplish that. Any examples which demonstrate a child window running ImGui would be really helpful.

Also, just out of curiosity, have there been any attempts to free ImGui from all being contained in a single widow? It would be really cool to have free floating ImGui windows without any ugly window borders around the already sleek-looking ImGui windows. Could you perhaps render each ImGuiWindow on a new HWND with transparency enabled, or something along those lines?

Having it seamlessly integrate into windows, or other operating systems, would be amazing. If there was an easy-to-use header which offered this kind of native support, I'd start using it for nearly all my software development.

Here's an example of my dream development environment:

```
#include <imgui_win32.h>

int WINAPI WinMain
(	HINSTANCE hInstance,
	HINSTANCE hPrevInstance,
	LPSTR lpCmd,
	int nShowCmd )
{
	ImGui::Begin();

	// Entire app UI rendered here. Each ImGuiWindow rendered on a new transparent HWND

	ImGui::End();

	return 0;
}
```

Thanks for the help.

**Comment by ocornut** [comment] 2017-06-23 22:27
> I'll keep trying at it. I was able to create a window, set up and render ImGui with no problems, I just can't seem to make it a popup child of my main window, and I don't really know the best way to accomplish that. Any examples which demonstrate a child window running ImGui would be really helpful.

In this paragraph you can replace "ImGui" with OpenGL everywhere in this sentence and notice that for this part of the question nothing of your problem is related with ImGui. I can't be providing OpenGL or Windows API support here unfortunately.

> Also, just out of curiosity, have there been any attempts to free ImGui from all being contained in a single widow? It would be really cool to have free floating ImGui windows without any ugly Windows borders around the already sleek-looking ImGui windows. Could you perhaps render each ImGuiWindow on a new HWND with transparency enabled, or something along those lines?

Yes some people have been doing that, for example:
https://github.com/thennequin/ImWindow/
And maybe some of the comments here https://github.com/ocornut/imgui/issues/351

It's not really how imgui was designed so you'll be pushing many walls - it's not easy to setup and probably not worth investigating if you aren't already very familiar with both dear imgui and Windows.

> Having it seamlessly integrate into windows, or other operating systems, would be amazing. If there was an easy-to-use header which offered this kind of native support, I'd start using it for nearly all my software development.

Yes it would be great, unfortunately we're not there yet. The library is developed on free time and there are a hundreds of other things that would come higher priority that attempting to make that easy to use. But supporting a native Docking extension (probably derived from one of the existing one in the thread above) will hopefully happens in the following months and that would be one of the step toward this.

**Comment by ocornut** [comment] 2017-06-23 22:31
I seem to recall that @bkaradzic for bgfx made a simplified version of https://github.com/thennequin/ImWindow/ because ImWindow is rather verbose in size and style, but I couldn't find it in bgfx right now.

**Comment by thennequin** [comment] 2017-06-29 16:39
A simple project starter using ImWindow/imgui/bgfx is available here https://github.com/thennequin/ImWindowProgramSample

**Comment by bkaradzic** [comment] 2017-06-29 16:48
See dock.inl here: https://github.com/bkaradzic/bgfx/tree/master/3rdparty/ocornut-imgui/widgets

ImWindow has more functionality than this dock, but I switched from it because I didn't use multiple windows functionality (planning to add it again at some later point), and this dock is much easier to integrate with ImGui (it's just drop in).

**Comment by nem0** [comment] 2017-06-29 17:52
@bkaradzic https://github.com/nem0/LumixEngine/commit/7ef7cc7f4550601f46c52d491ea076594d163116

**Comment by ocornut** [comment] 2018-04-11 09:41
Closing this old topic. FYI @Supabyte the feature you discussed is currently being worked on as under the "multi-viewports" term and tentatively aimed for a 1.70 release. See #1542 for details, there's an experimental public branch already!

**Closed by ocornut** 2018-04-11 09:41 UTC
