### ISSUE TITLE
Drag and drop problems with multiple platform windows

### ISSUE THREAD

**Issue by azonenberg** [ocornut/imgui#7922] opened 2024-08-27 15:45 UTC
### Version/Branch of Dear ImGui:

1.91.1 19104 docking

### Back-ends:

Vulkan

### Compiler, OS:

gcc, Linux X11 (Debian stable)

### Details:

This might be a couple of bugs or just one, I'm still investigating, but I'm seeing drag-and-drop behave weirdly with multiple platform windows. We can split into separate issues if it turns out to be separate bugs.

## Dragging outside a platform window creates spurious drop events

Steps to reproduce:

1. Create an imgui_demo window
2. Drag the demo window outside the main application so it spawns a separate platform window and does not overlap the main window (this last part is important)
3. Open the "tooltip at target location" drag and drop example
4. Attempt to drag the red box into the main application window
5. Observe the drag-and-drop ending as soon as the mouse cursor leaves an ImGui window

It appears that "leave all imgui windows" is the trigger for this failing. If the source and destination windows partially overlap (separate platform windows, but cursor is always over an imgui window) drag and drop appears to work as expected.

## Tooltips leaving the source platform window create spurious drop events

Steps to reproduce:

1. Create an imgui demo window
2. Drag the demo window outside the main application
3. Open the "tooltip at target location" example
4. Resize the demo window so that it's tall and skinny (in my example I have "tooltip at target loc" then the window is cropped)
5. Attempt to drag the red box and observe that as soon as the tooltip spawns, the drag-and-drop ends

### Minimal, Complete and Verifiable Example code:

Unmodified imgui_demo.cpp

**Comment by azonenberg** [comment] 2024-08-28 00:20
The workaround I'm using in ngscopeclient for the second issue is to suppress the tooltip if the left mouse button is down. I don't currently have a workaround for the first.

**Comment by ocornut** [comment] 2024-09-03 13:35
Please specify the platform backend and if SDL or GLFW specify their version.

**Comment by azonenberg** [comment] 2024-09-03 14:20
GLFW 3.3.8-1 (Debian bookworm) is what I'm testing on. Unsure if this happens on others as well as it's all I have readily available.

**Comment by azonenberg** [comment] 2024-10-22 09:07
Also happens with example_glfw_opengl3, so not Vulkan specific.

**Comment by JamesWrigley** [comment] 2024-11-02 23:07
I think this a duplicate of https://github.com/ocornut/imgui/issues/3158. Also see: https://github.com/ocornut/imgui/issues/7733#issuecomment-2197439405

**Comment by ocornut** [comment] 2024-11-05 10:27
This is now fixed by c347d69. Thanks everyone for the help, and @rokups, and sorry for taking so long to look at this workaround.

**Closed by ocornut** 2024-11-05 10:27 UTC
Labels: backends, drag drop, multi-viewports, linux/bsd
